In [1]:
import pandas as pd
THREAT_ACTORS = r'Z:\HTOC\Data_Analytics\Data\Observed_Tags\htoc_observed_indicator_tags.csv'
production_output = pd.read_csv(r'C:\Users\jaskew\Documents\project_repository\notebooks\observationEventForecasting\production_output.csv')

In [2]:
# Load threat actor tag data from the specified CSV file
threat_actor_tags = pd.read_csv(THREAT_ACTORS)
display(threat_actor_tags)

,indicator,type,tag,threat_category
0,003@tagmode-search.com,EmailAddress,Malspam,TECHNIQUE
1,0secure.ru,Host,Reconnaissance,TECHNIQUE
2,0secure.ru,Host,Phishing,MITRE_TECHNIQUE
3,1-you.njalla.no,Host,Malspam,TECHNIQUE
4,1-you.njalla.no,Host,CVE-2017-0199,VULNERABILITY
...,...,...,...,...
9161,zerocap.com,Host,SocGholish,MALWARE
9162,zerocap.com,Host,Ransomware/Ransomware-as-a-Service (RaaS),MALWARE TYPE
9163,zimbra@infinigi.com,EmailAddress,Health-ISAC,SOURCE
9164,zimbra@infinigi.com,EmailAddress,Phishing,MITRE_TECHNIQUE
9165,zimbra@infinigi.com,EmailAddress,Agent Tesla,MALWARE

In [3]:
# Extract a list of unique threat actor tags from threat_actor_tags
threat_actor_tag_list = threat_actor_tags[
    threat_actor_tags['threat_category'].str.contains('THREAT ACTOR', case=False, na=False)
]['tag'].unique().tolist()
threat_actor_tag_list

['Wicked Panda',
 'Refined Kitten',
 'Rocket Kitten',
 'Cozy Bear',
 'UNC5537',
 'ShadowSyndicate',
 'thedarkoverlord',
 'UNC4841',
 'UNC5807',
 'Fancy Bear',
 'Primitive Bear',
 'Volt Typhoon',
 'Seashell Blizzard',
 'Star Blizzard',
 'Scattered Spider',
 'Morphing Meerkat',
 'UNC3973',
 'Mustang Panda',
 'Indrik Spider',
 'UNC5986',
 'Pay-Per-Install Service',
 'Mustard Tempest',
 'Initial Access Broker',
 'Cold River',
 'Static Kitten',
 'UNC5439',
 'UNC5221',
 'Charming Kitten',
 'Play Ransomware Group',
 'storm-0558',
 'UNC5266',
 'Lace Tempest',
 'ALPHV',
 'UNC4936',
 'Flax Typhoon',
 'Storm-1849',
 'Venomous Bear',
 'Unc5175',
 'Unc5435',
 'UNC5435',
 'UNC5175',
 'Asylum Ambuscade',
 'Velvet Chollima',
 'Machete',
 '8220 Gang',
 'UNC3313',
 'UNC4487',
 'UNC1714',
 'Kryptonite Panda',
 'Prophet Spider',
 'storm-0494',
 'Affiliates',
 'UNC5837',
 'Carbon Spider',
 'Strawberry Tempest',
 'noname(057)16',
 'Storm-0866',
 'UAT-4820',
 'LilacSquid',
 'LABRAT',
 'TA582',
 'Rhysida',
 'Storm-2077',
 'TAG-100',
 'UNC4509',
 'Deep Panda',
 'UNC4536',
 'Apothecary Spider',
 'Storm-1113',
 'UNC5174',
 'Helix Kitten',
 'Unfurling Hemlock',
 'UNC4698',
 'UNC3594',
 'Crystalray',
 'Ghostwriter',
 'UNC1151',
 'TA577',
 'Circuit Panda',
 'Anchor Panda',
 'UNC3953',
 'Boriselchin',
 'Unc4681',
 'UNC4899',
 'TA578',
 'Dynamite Panda',
 'Hippo Team',
 'Revolver Rabbit',
 'Stardust Chollima',
 'UNC5148',
 'XeGroup']

In [4]:
matched_indicators = production_output['Indicator'].isin(threat_actor_tags['indicator'])
production_output_with_tags = production_output[matched_indicators]
# Merge in tags and threat categories from threat_actor_tags
production_output_with_tags = production_output_with_tags.merge(
    threat_actor_tags[['indicator', 'tag', 'threat_category']],
    left_on='Indicator',
    right_on='indicator',
    how='left'
)

display(production_output_with_tags)

,Indicator,Observed Today,Frequency (7d),Frequency (30d),Probability: Today,Confidence: Today,Probability: 7-Day,Confidence: 7-Day,Probability: 14-Day,Confidence: 14-Day,Probability: 30-Day,Confidence: 30-Day,indicator,tag,threat_category
0,1-you.njalla.no,0,1.0,1.0,3.07%,Today: Low confidence,56.58%,7-Day: Possibly active,65.42%,14-Day: Possibly active,74.36%,30-Day: Possibly active,1-you.njalla.no,Malspam,TECHNIQUE
1,1-you.njalla.no,0,1.0,1.0,3.07%,Today: Low confidence,56.58%,7-Day: Possibly active,65.42%,14-Day: Possibly active,74.36%,30-Day: Possibly active,1-you.njalla.no,CVE-2017-0199,VULNERABILITY
2,1-you.njalla.no,0,1.0,1.0,3.07%,Today: Low confidence,56.58%,7-Day: Possibly active,65.42%,14-Day: Possibly active,74.36%,30-Day: Possibly active,1-you.njalla.no,Cobalt Strike,MALWARE
3,1-you.njalla.no,0,1.0,1.0,3.07%,Today: Low confidence,56.58%,7-Day: Possibly active,65.42%,14-Day: Possibly active,74.36%,30-Day: Possibly active,1-you.njalla.no,Acquire Infrastructure,MITRE_TECHNIQUE
4,1-you.njalla.no,0,1.0,1.0,3.07%,Today: Low confidence,56.58%,7-Day: Possibly active,65.42%,14-Day: Possibly active,74.36%,30-Day: Possibly active,1-you.njalla.no,Account Manipulation,MITRE_TECHNIQUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1819,www.filemail.com,0,0.0,1.0,0.34%,Today: Low confidence,14.73%,7-Day: Low confidence,75.29%,14-Day: Low confidence,98.55%,30-Day: Low confidence,www.filemail.com,Helix Kitten,THREAT ACTOR
1820,www.filemail.com,0,0.0,1.0,0.34%,Today: Low confidence,14.73%,7-Day: Low confidence,75.29%,14-Day: Low confidence,98.55%,30-Day: Low confidence,www.filemail.com,Remote Management and Monitoring,TECHNIQUE
1821,www.filemail.com,0,0.0,1.0,0.34%,Today: Low confidence,14.73%,7-Day: Low confidence,75.29%,14-Day: Low confidence,98.55%,30-Day: Low confidence,www.filemail.com,MOIS,SPONSOR ORGANIZATION
1822,www.filemail.com,0,0.0,1.0,0.34%,Today: Low confidence,14.73%,7-Day: Low confidence,75.29%,14-Day: Low confidence,98.55%,30-Day: Low confidence,www.filemail.com,Iran,COUNTRY
1823,www.filemail.com,0,0.0,1.0,0.34%,Today: Low confidence,14.73%,7-Day: Low confidence,75.29%,14-Day: Low confidence,98.55%,30-Day: Low confidence,www.filemail.com,Social Engineering,TECHNIQUE

In [5]:
production_output_with_tags[production_output_with_tags['tag'] == 'UNC5537']

,Indicator,Observed Today,Frequency (7d),Frequency (30d),Probability: Today,Confidence: Today,Probability: 7-Day,Confidence: 7-Day,Probability: 14-Day,Confidence: 14-Day,Probability: 30-Day,Confidence: 30-Day,indicator,tag,threat_category
10,103.108.231.67,0,0.0,0.0,0.02%,Today: Low confidence,0.11%,7-Day: Low confidence,0.16%,14-Day: Low confidence,8.89%,30-Day: Low confidence,103.108.231.67,UNC5537,THREAT ACTOR
35,104.129.24.124,0,0.0,0.0,0.01%,Today: Low confidence,0.36%,7-Day: Low confidence,1.92%,14-Day: Low confidence,11.4%,30-Day: Low confidence,104.129.24.124,UNC5537,THREAT ACTOR
76,129.227.46.163,1,2.0,2.0,11.07%,Today: Possibly active,90.23%,7-Day: Highly likely,98.08%,14-Day: Highly likely,100.0%,30-Day: Highly likely,129.227.46.163,UNC5537,THREAT ACTOR
79,138.199.43.92,0,0.0,3.0,0.52%,Today: Low confidence,31.99%,7-Day: Low confidence,85.49%,14-Day: Low confidence,100.0%,30-Day: Low confidence,138.199.43.92,UNC5537,THREAT ACTOR
80,138.199.6.221,0,0.0,0.0,0.0%,Today: Low confidence,0.01%,7-Day: Low confidence,0.0%,14-Day: Low confidence,0.52%,30-Day: Low confidence,138.199.6.221,UNC5537,THREAT ACTOR
102,143.244.47.66,0,1.0,4.0,2.57%,Today: Low confidence,85.41%,7-Day: Possibly active,100.0%,14-Day: Possibly active,100.0%,30-Day: Possibly active,143.244.47.66,UNC5537,THREAT ACTOR
124,146.70.117.210,1,6.0,6.0,88.42%,Today: Highly likely,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,146.70.117.210,UNC5537,THREAT ACTOR
132,146.70.119.24,0,0.0,1.0,0.38%,Today: Low confidence,10.42%,7-Day: Low confidence,56.02%,14-Day: Low confidence,73.46%,30-Day: Low confidence,146.70.119.24,UNC5537,THREAT ACTOR
133,146.70.128.227,0,0.0,0.0,0.0%,Today: Low confidence,0.01%,7-Day: Low confidence,0.01%,14-Day: Low confidence,0.81%,30-Day: Low confidence,146.70.128.227,UNC5537,THREAT ACTOR
135,146.70.165.227,0,2.0,5.0,4.65%,Today: Low confidence,93.05%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,146.70.165.227,UNC5537,THREAT ACTOR
143,146.70.166.131,0,0.0,2.0,0.03%,Today: Low confidence,12.18%,7-Day: Low confidence,22.98%,14-Day: Low confidence,89.54%,30-Day: Low confidence,146.70.166.131,UNC5537,THREAT ACTOR
145,146.70.166.176,0,1.0,2.0,2.57%,Today: Low confidence,77.53%,7-Day: Possibly active,97.48%,14-Day: Possibly active,100.0%,30-Day: Possibly active,146.70.166.176,UNC5537,THREAT ACTOR
153,146.70.168.195,0,0.0,1.0,0.58%,Today: Low confidence,12.87%,7-Day: Low confidence,60.93%,14-Day: Low confidence,73.82%,30-Day: Low confidence,146.70.168.195,UNC5537,THREAT ACTOR
155,146.70.171.112,0,1.0,3.0,2.1%,Today: Low confidence,77.43%,7-Day: Possibly active,100.0%,14-Day: Possibly active,100.0%,30-Day: Possibly active,146.70.171.112,UNC5537,THREAT ACTOR
163,146.70.171.67,0,0.0,1.0,0.05%,Today: Low confidence,6.53%,7-Day: Low confidence,11.9%,14-Day: Low confidence,62.46%,30-Day: Low confidence,146.70.171.67,UNC5537,THREAT ACTOR
165,146.70.171.99,0,1.0,3.0,2.5%,Today: Low confidence,77.16%,7-Day: Possibly active,100.0%,14-Day: Possibly active,100.0%,30-Day: Possibly active,146.70.171.99,UNC5537,THREAT ACTOR
177,146.70.200.3,0,0.0,0.0,0.02%,Today: Low confidence,0.09%,7-Day: Low confidence,0.12%,14-Day: Low confidence,7.54%,30-Day: Low confidence,146.70.200.3,UNC5537,THREAT ACTOR
178,146.70.211.67,0,1.0,6.0,1.73%,Today: Low confidence,89.04%,7-Day: Possibly active,100.0%,14-Day: Possibly active,100.0%,30-Day: Possibly active,146.70.211.67,UNC5537,THREAT ACTOR
188,149.102.246.16,0,0.0,0.0,0.01%,Today: Low confidence,0.02%,7-Day: Low confidence,0.02%,14-Day: Low confidence,1.93%,30-Day: Low confidence,149.102.246.16,UNC5537,THREAT ACTOR
189,149.40.50.113,0,0.0,0.0,0.01%,Today: Low confidence,0.02%,7-Day: Low confidence,0.01%,14-Day: Low confidence,1.25%,30-Day: Low confidence,149.40.50.113,UNC5537,THREAT ACTOR
190,149.88.22.130,0,0.0,0.0,0.01%,Today: Low confidence,0.01%,7-Day: Low confidence,0.01%,14-Day: Low confidence,1.01%,30-Day: Low confidence,149.88.22.130,UNC5537,THREAT ACTOR
205,154.47.30.137,0,4.0,5.0,36.77%,Today: Possibly active,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,154.47.30.137,UNC5537,THREAT ACTOR
214,154.47.30.150,0,4.0,5.0,33.53%,Today: Possibly active,99.33%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,154.47.30.150,UNC5537,THREAT ACTOR
333,169.150.203.29,1,2.0,7.0,8.54%,Today: Possibly active,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,169.150.203.29,UNC5537,THREAT ACTOR
336,169.150.223.208,1,5.0,23.0,45.15%,Today: Possibly active,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,169.150.223.208,UNC5537,THREAT ACTOR
418,178.249.214.3,0,1.0,1.0,4.02%,Today: Low confidence,57.88%,7-Day: Possibly active,65.81%,14-Day: Possibly active,74.56%,30-Day: Possibly active,178.249.214.3,UNC5537,THREAT ACTOR
450,185.156.46.144,0,0.0,5.0,0.58%,Today: Low confidence,40.83%,7-Day: Low confidence,100.0%,14-Day: Low confidence,100.0%,30-Day: Low confidence,185.156.46.144,UNC5537,THREAT ACTOR
458,185.156.46.157,0,0.0,1.0,0.29%,Today: Low confidence,9.24%,7-Day: Low confidence,26.81%,14-Day: Low confidence,73.1%,30-Day: Low confidence,185.156.46.157,UNC5537,THREAT ACTOR
603,185.188.61.196,0,0.0,0.0,0.02%,Today: Low confidence,0.09%,7-Day: Low confidence,0.12%,14-Day: Low confidence,7.54%,30-Day: Low confidence,185.188.61.196,UNC5537,THREAT ACTOR
606,185.213.155.241,0,5.0,5.0,71.95%,Today: Highly likely,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,185.213.155.241,UNC5537,THREAT ACTOR
633,185.248.85.14,0,1.0,3.0,2.07%,Today: Low confidence,79.34%,7-Day: Possibly active,100.0%,14-Day: Possibly active,100.0%,30-Day: Possibly active,185.248.85.14,UNC5537,THREAT ACTOR
679,193.138.7.158,0,0.0,1.0,0.38%,Today: Low confidence,10.42%,7-Day: Low confidence,56.02%,14-Day: Low confidence,73.46%,30-Day: Low confidence,193.138.7.158,UNC5537,THREAT ACTOR
687,194.110.115.3,0,1.0,1.0,4.6%,Today: Low confidence,58.41%,7-Day: Possibly active,65.95%,14-Day: Possibly active,74.67%,30-Day: Possibly active,194.110.115.3,UNC5537,THREAT ACTOR
688,194.127.199.3,0,0.0,1.0,0.29%,Today: Low confidence,9.24%,7-Day: Low confidence,26.81%,14-Day: Low confidence,73.1%,30-Day: Low confidence,194.127.199.3,UNC5537,THREAT ACTOR
695,194.230.144.50,0,0.0,0.0,0.01%,Today: Low confidence,0.02%,7-Day: Low confidence,0.02%,14-Day: Low confidence,1.93%,30-Day: Low confidence,194.230.144.50,UNC5537,THREAT ACTOR
704,194.230.148.99,1,2.0,2.0,11.5%,Today: Possibly active,83.64%,7-Day: Highly likely,98.05%,14-Day: Highly likely,100.0%,30-Day: Highly likely,194.230.148.99,UNC5537,THREAT ACTOR
713,194.230.158.107,0,0.0,0.0,0.0%,Today: Low confidence,0.01%,7-Day: Low confidence,0.01%,14-Day: Low confidence,0.81%,30-Day: Low confidence,194.230.158.107,UNC5537,THREAT ACTOR
722,194.230.158.178,0,1.0,1.0,3.51%,Today: Low confidence,57.28%,7-Day: Possibly active,65.64%,14-Day: Possibly active,74.45%,30-Day: Possibly active,194.230.158.178,UNC5537,THREAT ACTOR
731,194.230.160.5,0,0.0,0.0,0.02%,Today: Low confidence,0.09%,7-Day: Low confidence,0.12%,14-Day: Low confidence,7.54%,30-Day: Low confidence,194.230.160.5,UNC5537,THREAT ACTOR
762,198.44.129.82,0,5.0,6.0,60.22%,Today: Highly likely,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,198.44.129.82,UNC5537,THREAT ACTOR
770,198.44.129.99,0,3.0,5.0,17.75%,Today: Possibly active,99.54%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,198.44.129.99,UNC5537,THREAT ACTOR
771,198.44.136.35,0,0.0,0.0,0.01%,Today: Low confidence,0.25%,7-Day: Low confidence,1.26%,14-Day: Low confidence,10.51%,30-Day: Low confidence,198.44.136.35,UNC5537,THREAT ACTOR
772,198.44.136.99,0,0.0,0.0,0.01%,Today: Low confidence,0.02%,7-Day: Low confidence,0.01%,14-Day: Low confidence,1.25%,30-Day: Low confidence,198.44.136.99,UNC5537,THREAT ACTOR
816,206.217.206.68,0,0.0,8.0,0.26%,Today: Low confidence,40.13%,7-Day: Low confidence,62.52%,14-Day: Low confidence,100.0%,30-Day: Low confidence,206.217.206.68,UNC5537,THREAT ACTOR
866,37.19.200.131,0,0.0,0.0,0.02%,Today: Low confidence,0.49%,7-Day: Low confidence,2.37%,14-Day: Low confidence,23.11%,30-Day: Low confidence,37.19.200.131,UNC5537,THREAT ACTOR
870,37.19.210.2,1,4.0,7.0,40.12%,Today: Possibly active,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,37.19.210.2,UNC5537,THREAT ACTOR
872,38.240.225.37,0,1.0,1.0,4.6%,Today: Low confidence,58.41%,7-Day: Possibly active,65.95%,14-Day: Possibly active,74.67%,30-Day: Possibly active,38.240.225.37,UNC5537,THREAT ACTOR
873,43.225.189.132,0,1.0,11.0,2.03%,Today: Low confidence,100.0%,7-Day: Possibly active,100.0%,14-Day: Possibly active,100.0%,30-Day: Possibly active,43.225.189.132,UNC5537,THREAT ACTOR
874,43.225.189.163,0,1.0,8.0,2.39%,Today: Low confidence,100.0%,7-Day: Possibly active,100.0%,14-Day: Possibly active,100.0%,30-Day: Possibly active,43.225.189.163,UNC5537,THREAT ACTOR
877,45.134.140.131,0,0.0,2.0,0.08%,Today: Low confidence,13.56%,7-Day: Low confidence,29.38%,14-Day: Low confidence,99.25%,30-Day: Low confidence,45.134.140.131,UNC5537,THREAT ACTOR
878,45.134.212.80,0,0.0,2.0,0.36%,Today: Low confidence,21.19%,7-Day: Low confidence,85.43%,14-Day: Low confidence,100.0%,30-Day: Low confidence,45.134.212.80,UNC5537,THREAT ACTOR
879,45.134.79.98,0,0.0,1.0,0.04%,Today: Low confidence,6.9%,7-Day: Low confidence,14.34%,14-Day: Low confidence,76.9%,30-Day: Low confidence,45.134.79.98,UNC5537,THREAT ACTOR
915,46.19.136.227,0,0.0,2.0,0.21%,Today: Low confidence,18.22%,7-Day: Low confidence,51.0%,14-Day: Low confidence,100.0%,30-Day: Low confidence,46.19.136.227,UNC5537,THREAT ACTOR
1384,79.127.217.35,0,0.0,1.0,0.11%,Today: Low confidence,8.15%,7-Day: Low confidence,22.09%,14-Day: Low confidence,91.8%,30-Day: Low confidence,79.127.217.35,UNC5537,THREAT ACTOR
1481,93.115.0.49,1,6.0,6.0,91.59%,Today: Highly likely,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,93.115.0.49,UNC5537,THREAT ACTOR

In [6]:
# Condense tags for each indicator into a single row with lists of tags and threat categories
condensed = (
    production_output_with_tags
    .groupby('Indicator')
    .agg({
        'Observed Today': 'first',
        'Frequency (7d)': 'first',
        'Frequency (30d)': 'first',
        'Probability: Today': 'first',
        'Confidence: Today': 'first',
        'Probability: 7-Day': 'first',
        'Confidence: 7-Day': 'first',
        'Probability: 14-Day': 'first',
        'Confidence: 14-Day': 'first',
        'Probability: 30-Day': 'first',
        'Confidence: 30-Day': 'first',
        'tag': lambda x: list(x.unique()),
        'threat_category': lambda x: list(x.dropna().unique())
    })
    .reset_index()
)

display(condensed)

,Indicator,Observed Today,Frequency (7d),Frequency (30d),Probability: Today,Confidence: Today,Probability: 7-Day,Confidence: 7-Day,Probability: 14-Day,Confidence: 14-Day,Probability: 30-Day,Confidence: 30-Day,tag,threat_category
0,1-you.njalla.no,0,1.0,1.0,3.07%,Today: Low confidence,56.58%,7-Day: Possibly active,65.42%,14-Day: Possibly active,74.36%,30-Day: Possibly active,"[Malspam, CVE-2017-0199, Cobalt Strike, Acquir...","[TECHNIQUE, VULNERABILITY, MALWARE, MITRE_TECH..."
1,103.108.231.67,0,0.0,0.0,0.02%,Today: Low confidence,0.11%,7-Day: Low confidence,0.16%,14-Day: Low confidence,8.89%,30-Day: Low confidence,[UNC5537],[THREAT ACTOR]
2,103.149.249.226,0,0.0,0.0,0.0%,Today: Low confidence,0.03%,7-Day: Low confidence,0.13%,14-Day: Low confidence,1.14%,30-Day: Low confidence,"[CVE-2024-4040, CrushFTP]",[VULNERABILITY]
3,103.77.192.88,0,0.0,1.0,0.08%,Today: Low confidence,6.85%,7-Day: Low confidence,13.37%,14-Day: Low confidence,67.96%,30-Day: Low confidence,"[ghostloot, UNC5807, Reconnaissance, STOWAWAY,...","[MALWARE, THREAT ACTOR, TECHNIQUE, MITRE_TECHN..."
4,104.128.161.233,0,3.0,26.0,8.7%,Today: Possibly active,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,"[Cozy Bear, Fancy Bear, GRU, GRIZZLY STEPPE, G...","[THREAT ACTOR, SPONSOR ORGANIZATION, CAMPAIGN,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,vtext.com,1,7.0,30.0,81.53%,Today: Highly likely,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,"[Phishing, Gootloader Malware]","[MITRE_TECHNIQUE, MALWARE]"
314,ws.onehub.com,0,3.0,6.0,17.45%,Today: Possibly active,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,"[SyncroMSP, Unified Endpoint Management, Stati...","[THREAT ACTOR, MALWARE, TECHNIQUE, SPONSOR ORG..."
315,www.3u.com,0,0.0,0.0,0.0%,Today: Low confidence,0.0%,7-Day: Low confidence,0.0%,14-Day: Low confidence,0.09%,30-Day: Low confidence,[multiverze],[]
316,www.deepseek.com.cdn.cloudflare.net,1,7.0,24.0,85.12%,Today: Highly likely,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,[DeepSeek],[VULNERABILITY]
317,www.filemail.com,0,0.0,1.0,0.34%,Today: Low confidence,14.73%,7-Day: Low confidence,75.29%,14-Day: Low confidence,98.55%,30-Day: Low confidence,"[SyncroMSP, Unified Endpoint Management, Stati...","[THREAT ACTOR, TECHNIQUE, SPONSOR ORGANIZATION..."

In [7]:
filtered_df = condensed[condensed['tag'].apply(lambda tags: any(tag in threat_actor_tag_list for tag in tags))].copy()

# Create column of related threat actor
filtered_df.loc[:, 'related_threat_actors'] = filtered_df['tag'].apply(
    lambda tags: [tag for tag in tags if tag in threat_actor_tag_list]
)
filtered_df = filtered_df.drop(columns=['tag', 'threat_category'])
display(filtered_df)

,Indicator,Observed Today,Frequency (7d),Frequency (30d),Probability: Today,Confidence: Today,Probability: 7-Day,Confidence: 7-Day,Probability: 14-Day,Confidence: 14-Day,Probability: 30-Day,Confidence: 30-Day,related_threat_actors
0,1-you.njalla.no,0,1.0,1.0,3.07%,Today: Low confidence,56.58%,7-Day: Possibly active,65.42%,14-Day: Possibly active,74.36%,30-Day: Possibly active,[Wicked Panda]
1,103.108.231.67,0,0.0,0.0,0.02%,Today: Low confidence,0.11%,7-Day: Low confidence,0.16%,14-Day: Low confidence,8.89%,30-Day: Low confidence,[UNC5537]
3,103.77.192.88,0,0.0,1.0,0.08%,Today: Low confidence,6.85%,7-Day: Low confidence,13.37%,14-Day: Low confidence,67.96%,30-Day: Low confidence,"[UNC5807, UNC4841]"
4,104.128.161.233,0,3.0,26.0,8.7%,Today: Possibly active,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,"[Cozy Bear, Fancy Bear]"
5,104.129.24.124,0,0.0,0.0,0.01%,Today: Low confidence,0.36%,7-Day: Low confidence,1.92%,14-Day: Low confidence,11.4%,30-Day: Low confidence,[UNC5537]
...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,prosinthecity.com,0,0.0,0.0,0.03%,Today: Low confidence,0.13%,7-Day: Low confidence,0.22%,14-Day: Low confidence,10.37%,30-Day: Low confidence,[Mustard Tempest]
305,r3.o.lencr.org,0,0.0,1.0,0.14%,Today: Low confidence,8.68%,7-Day: Low confidence,25.13%,14-Day: Low confidence,94.73%,30-Day: Low confidence,[Mustard Tempest]
308,summerwaterhall.com,0,0.0,2.0,0.14%,Today: Low confidence,15.71%,7-Day: Low confidence,40.75%,14-Day: Low confidence,100.0%,30-Day: Low confidence,[Cozy Bear]
314,ws.onehub.com,0,3.0,6.0,17.45%,Today: Possibly active,100.0%,7-Day: Highly likely,100.0%,14-Day: Highly likely,100.0%,30-Day: Highly likely,"[Static Kitten, Helix Kitten]"
317,www.filemail.com,0,0.0,1.0,0.34%,Today: Low confidence,14.73%,7-Day: Low confidence,75.29%,14-Day: Low confidence,98.55%,30-Day: Low confidence,"[Static Kitten, Helix Kitten]"

In [8]:
from collections import Counter

# Count frequency of each related threat actor in filtered_df

# Flatten the list of related threat actors
all_actors = [actor for actors in filtered_df['related_threat_actors'] for actor in actors]
actor_counts = Counter(all_actors)

# Convert to DataFrame for display
actor_freq_df = pd.DataFrame(actor_counts.items(), columns=['Threat Actor', 'Frequency']).sort_values('Frequency', ascending=False)

# Merge in 7d, 14d, 30d probabilities for each threat actor
# For each threat actor, compute the mean probability across all related indicators

# First, create a mapping from indicator to 7d/14d/30d probability
indicator_prob = filtered_df[['Indicator']].copy()
indicator_prob['7d_prob'] = production_output.set_index('Indicator').loc[indicator_prob['Indicator'], 'Probability: 7-Day'].values
indicator_prob['14d_prob'] = production_output.set_index('Indicator').loc[indicator_prob['Indicator'], 'Probability: 14-Day'].values
indicator_prob['30d_prob'] = production_output.set_index('Indicator').loc[indicator_prob['Indicator'], 'Probability: 30-Day'].values

# Explode related_threat_actors to associate each indicator with each actor
exploded = filtered_df[['Indicator', 'related_threat_actors']].explode('related_threat_actors')
exploded = exploded.merge(indicator_prob, left_on='Indicator', right_on='Indicator', how='left')

# Group by threat actor and aggregate mean probability (as string, so convert to float first)
def pct_to_float(s):
    return s.str.rstrip('%').astype(float)

actor_probs = (
    exploded.groupby('related_threat_actors')
    .agg(
        indicators=('Indicator', 'nunique'),
        mean_7d_prob=('7d_prob', lambda x: f"{pct_to_float(x).mean():.2f}%"),
        mean_14d_prob=('14d_prob', lambda x: f"{pct_to_float(x).mean():.2f}%"),
        mean_30d_prob=('30d_prob', lambda x: f"{pct_to_float(x).mean():.2f}%")
    )
    .reset_index()
    .rename(columns={
        'related_threat_actors': 'Threat Actor',
        'mean_7d_prob': 'Mean 7-Day Probability (%)',
        'mean_14d_prob': 'Mean 14-Day Probability (%)',
        'mean_30d_prob': 'Mean 30-Day Probability (%)'
    })
)

# Add most common confidence for 7, 14, and 30 days for each threat actor
exploded_conf = filtered_df[['Indicator', 'related_threat_actors', 'Confidence: 7-Day', 'Confidence: 14-Day', 'Confidence: 30-Day']].explode('related_threat_actors')

def most_common(series):
    return series.mode().iloc[0] if not series.mode().empty else None

# Define ranking for confidence tags (higher is better)
confidence_rank = {
    'Highly likely': 3,
    'Possibly active': 2,
    'Low confidence': 1
}

def extract_ranked_confidence(series, window_label):
    # Extract the confidence string after the colon (e.g., "7-Day: Highly likely" -> "Highly likely")
    confs = series.dropna().astype(str).str.extract(rf'{window_label}:\s*(.*)')[0]
    if confs.empty:
        return None
    # Count occurrences
    counts = confs.value_counts()
    max_count = counts.max()
    # Get all tied values
    tied = counts[counts == max_count].index.tolist()
    # Pick the highest ranked
    ranked = sorted(tied, key=lambda x: -confidence_rank.get(x, 0))
    return f"{window_label}: {ranked[0]}" if ranked else None

"""actor_conf = (
    exploded_conf.groupby('related_threat_actors')
    .agg(
        confidence_7d=('Confidence: 7-Day', lambda x: extract_ranked_confidence(x, '7-Day')),
        confidence_14d=('Confidence: 14-Day', lambda x: extract_ranked_confidence(x, '14-Day')),
        confidence_30d=('Confidence: 30-Day', lambda x: extract_ranked_confidence(x, '30-Day'))
    )
    .reset_index()
    .rename(columns={
        'related_threat_actors': 'Threat Actor',
        'confidence_7d': 'Most Common 7-Day Confidence',
        'confidence_14d': 'Most Common 14-Day Confidence',
        'confidence_30d': 'Most Common 30-Day Confidence'
    })
)"""

# Merge with actor_freq_df
#actor_freq_df = actor_freq_df.merge(actor_conf, on='Threat Actor', how='left')
actor_freq_df = actor_freq_df.merge(actor_probs, on='Threat Actor', how='left')
actor_freq_df.drop(columns=['indicators'], inplace=True)
display(actor_freq_df)

,Threat Actor,Frequency,Mean 7-Day Probability (%),Mean 14-Day Probability (%),Mean 30-Day Probability (%)
0,UNC5537,55,44.31%,55.91%,68.57%
1,Cozy Bear,21,46.76%,61.63%,71.98%
2,Fancy Bear,20,49.96%,65.37%,75.57%
3,Scattered Spider,15,64.16%,74.13%,85.12%
4,Static Kitten,7,72.58%,84.38%,97.08%
5,Seashell Blizzard,6,44.68%,52.32%,70.23%
6,UNC5221,6,62.73%,69.86%,79.25%
7,Wicked Panda,4,44.10%,52.17%,72.14%
8,UNC5174,3,69.59%,74.87%,90.95%
9,Primitive Bear,3,0.21%,0.69%,13.12%
10,UNC5837,3,2.44%,5.32%,23.83%
11,Carbon Spider,3,23.53%,31.45%,58.16%
12,Mustard Tempest,3,2.94%,8.47%,35.23%
13,Helix Kitten,3,69.66%,91.76%,99.52%
14,UNC5807,2,12.27%,24.59%,83.98%
15,Revolver Rabbit,2,0.20%,0.95%,10.50%
16,Flax Typhoon,2,44.32%,70.89%,100.00%
17,UNC4841,2,25.69%,54.34%,83.98%
18,Charming Kitten,1,0.09%,0.12%,7.54%
19,UNC3313,1,100.00%,100.00%,100.00%
20,Lace Tempest,1,12.35%,23.79%,92.18%
21,Venomous Bear,1,12.35%,23.79%,92.18%
22,Mustang Panda,1,6.66%,12.44%,65.47%
23,Play Ransomware Group,1,0.09%,0.12%,7.54%
24,UNC4936,1,67.54%,94.22%,100.00%
25,Morphing Meerkat,1,0.08%,0.46%,2.96%
26,UNC4487,1,32.99%,53.96%,100.00%
27,TAG-100,1,0.00%,0.00%,0.00%
28,Storm-2077,1,0.00%,0.00%,0.00%
29,UNC1714,1,0.09%,0.38%,5.16%
30,Kryptonite Panda,1,0.09%,0.38%,5.16%
31,UNC5439,1,0.06%,0.29%,2.63%
32,Circuit Panda,1,89.41%,100.00%,100.00%
33,Dynamite Panda,1,20.78%,84.17%,100.00%
34,TA578,1,20.78%,84.17%,100.00%