In [2]:
import os
import pandas as pd

folder_path = r"Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Full Daily Reports"
files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]
files

['full_daily_report_20250616.csv',
 'full_daily_report_20250617.csv',
 'full_daily_report_20250618.csv',
 'full_daily_report_20250623.csv',
 'full_daily_report_20250624.csv',
 'full_daily_report_20250625.csv',
 'full_daily_report_20250626.csv',
 'full_daily_report_20250627.csv',
 'full_daily_report_20250630.csv',
 'full_daily_report_20250701.csv']

In [3]:
from datetime import datetime

# Get today's date in the same format as the file names (YYYYMMDD)
today_str = datetime.now().strftime('%Y%m%d')

# Filter files that contain today's date
current_date_files = [f for f in files if today_str in f]
current_date_files

['full_daily_report_20250701.csv']

In [4]:
dfs = {}
for file_name in files:
    file_path = os.path.join(folder_path, file_name)
    var_name = os.path.splitext(file_name)[0]  # Remove .csv extension
    dfs[var_name] = pd.read_csv(file_path)
    print(f"Loaded {file_name} into dfs['{var_name}'], shape: {dfs[var_name].shape}")

# Example of accessing a specific DataFrame
df_example = dfs['full_daily_report_20250616']

Loaded full_daily_report_20250616.csv into dfs['full_daily_report_20250616'], shape: (6395, 12)
Loaded full_daily_report_20250617.csv into dfs['full_daily_report_20250617'], shape: (6751, 12)
Loaded full_daily_report_20250618.csv into dfs['full_daily_report_20250618'], shape: (7082, 12)
Loaded full_daily_report_20250623.csv into dfs['full_daily_report_20250623'], shape: (7408, 12)
Loaded full_daily_report_20250624.csv into dfs['full_daily_report_20250624'], shape: (7509, 12)
Loaded full_daily_report_20250625.csv into dfs['full_daily_report_20250625'], shape: (7533, 12)
Loaded full_daily_report_20250626.csv into dfs['full_daily_report_20250626'], shape: (8007, 12)
Loaded full_daily_report_20250627.csv into dfs['full_daily_report_20250627'], shape: (8433, 12)
Loaded full_daily_report_20250630.csv into dfs['full_daily_report_20250630'], shape: (8514, 12)
Loaded full_daily_report_20250701.csv into dfs['full_daily_report_20250701'], shape: (9050, 12)

In [5]:
display(df_example.head())

,Indicator,Observed Today,Frequency (7d),Frequency (30d),Probability: 7-Day,Confidence: 7-Day,Probability: 14-Day,Confidence: 14-Day,Probability: 30-Day,Confidence: 30-Day,Partner,FileDate
0,102.129.153.158,0,0.0,1.0,6.88%,7-Day: Low confidence,13.68%,14-Day: Low confidence,68.66%,30-Day: Possibly active,CDC,20250616
1,102.129.153.43,0,0.0,0.0,0.38%,7-Day: Low confidence,0.93%,14-Day: Low confidence,18.11%,30-Day: Low confidence,CDC,20250616
2,102.129.153.71,0,0.0,2.0,12.39%,7-Day: Low confidence,24.8%,14-Day: Low confidence,86.71%,30-Day: Highly likely,CDC,20250616
3,102.165.16.161,0,0.0,0.0,0.01%,7-Day: Low confidence,0.01%,14-Day: Low confidence,0.17%,30-Day: Low confidence,CDC,20250616
4,103.133.107.28,0,0.0,1.0,9.14%,7-Day: Low confidence,59.14%,14-Day: Possibly active,73.35%,30-Day: Possibly active,CDC,20250616

In [6]:
# List all subfolders in folder_path
logs_folder = r'Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs'

subfolders = [f.path for f in os.scandir(logs_folder) if f.is_dir()]
for subfolder in subfolders:
    print(f"Folder: {os.path.basename(subfolder)}")
    subfolder_files = [f for f in os.listdir(subfolder) if os.path.isfile(os.path.join(subfolder, f))]
    print(f"  Files: {subfolder_files}")

Folder: CDC
  Files: ['CDC_forecast_log.xlsx', 'forecast_log.xlsx', '~$forecast_log_2025-06-23.xlsx']
Folder: CMS
  Files: ['CMS_forecast_log.xlsx', 'forecast_log.xlsx']
Folder: DHA
  Files: ['DHA_forecast_log.xlsx', 'forecast_log.xlsx']
Folder: FDA
  Files: ['FDA_forecast_log.xlsx', 'forecast_log.xlsx']
Folder: HHS
  Files: ['forecast_log.xlsx', 'HHS_forecast_log.xlsx']
Folder: HRSA
  Files: ['forecast_log.xlsx', 'HRSA_forecast_log.xlsx']
Folder: IHS
  Files: ['forecast_log.xlsx', 'IHS_forecast_log.xlsx']
Folder: NIH
  Files: ['forecast_log.xlsx', 'NIH_forecast_log.xlsx']
Folder: OS
  Files: ['forecast_log.xlsx', 'OS_forecast_log.xlsx']
Folder: VA
  Files: ['forecast_log.xlsx', 'VA_forecast_log.xlsx']

In [7]:
excel_dfs = {}
for subfolder in subfolders:
    subfolder_files = [f for f in os.listdir(subfolder) if os.path.isfile(os.path.join(subfolder, f))]
    for file in subfolder_files:
        # Skip temporary Excel files (usually start with '~$')
        if file.endswith('.xlsx') and not file.startswith('~$'):
            file_full_path = os.path.join(subfolder, file)
            var_base = os.path.splitext(file)[0]
            excel_dfs[var_base] = pd.read_excel(file_full_path, engine='openpyxl')
            print(f"Loaded {file} from {os.path.basename(subfolder)} into excel_dfs['{var_base}'], shape: {excel_dfs[var_base].shape}")

Loaded CDC_forecast_log.xlsx from CDC into excel_dfs['CDC_forecast_log'], shape: (9438, 6)
Loaded forecast_log.xlsx from CDC into excel_dfs['forecast_log'], shape: (9438, 6)
Loaded CMS_forecast_log.xlsx from CMS into excel_dfs['CMS_forecast_log'], shape: (33375, 6)
Loaded forecast_log.xlsx from CMS into excel_dfs['forecast_log'], shape: (33375, 6)
Loaded DHA_forecast_log.xlsx from DHA into excel_dfs['DHA_forecast_log'], shape: (25758, 6)
Loaded forecast_log.xlsx from DHA into excel_dfs['forecast_log'], shape: (25758, 6)
Loaded FDA_forecast_log.xlsx from FDA into excel_dfs['FDA_forecast_log'], shape: (22989, 6)
Loaded forecast_log.xlsx from FDA into excel_dfs['forecast_log'], shape: (22989, 6)
Loaded forecast_log.xlsx from HHS into excel_dfs['forecast_log'], shape: (12519, 6)
Loaded HHS_forecast_log.xlsx from HHS into excel_dfs['HHS_forecast_log'], shape: (12519, 6)
Loaded forecast_log.xlsx from HRSA into excel_dfs['forecast_log'], shape: (20913, 6)
Loaded HRSA_forecast_log.xlsx from HRSA into excel_dfs['HRSA_forecast_log'], shape: (20913, 6)
Loaded forecast_log.xlsx from IHS into excel_dfs['forecast_log'], shape: (20097, 6)
Loaded IHS_forecast_log.xlsx from IHS into excel_dfs['IHS_forecast_log'], shape: (20097, 6)
Loaded forecast_log.xlsx from NIH into excel_dfs['forecast_log'], shape: (35955, 6)
Loaded NIH_forecast_log.xlsx from NIH into excel_dfs['NIH_forecast_log'], shape: (35955, 6)
Loaded forecast_log.xlsx from OS into excel_dfs['forecast_log'], shape: (20358, 6)
Loaded OS_forecast_log.xlsx from OS into excel_dfs['OS_forecast_log'], shape: (20358, 6)
Loaded forecast_log.xlsx from VA into excel_dfs['forecast_log'], shape: (23880, 6)
Loaded VA_forecast_log.xlsx from VA into excel_dfs['VA_forecast_log'], shape: (23880, 6)

In [8]:
display(excel_dfs['VA_forecast_log'].head())

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome
0,1-you.njalla.no,2025-06-16,14-Day,Possibly active,2025-06-30,Not Seen
1,1-you.njalla.no,2025-06-16,30-Day,Possibly active,2025-07-16,Pending
2,1-you.njalla.no,2025-06-16,7-Day,Low confidence,2025-06-23,Not Seen
3,1-you.njalla.no,2025-06-17,14-Day,Possibly active,2025-07-01,Pending
4,1-you.njalla.no,2025-06-17,30-Day,Possibly active,2025-07-17,Pending

In [25]:
import os
import shutil
from datetime import datetime
from typing import Dict
import pandas as pd
from IPython.display import display

# ---------------------------------------------------------------------
# Normalize helper
CONFIDENCE_MAP = {
    '30-day: highly likely': 'Highly Likely',
    '30-day: possibly active': 'Possibly Active',
    '30-day: low confidence': 'Low Confidence',
    '14-day: highly likely': 'Highly Likely',
    '14-day: possibly active': 'Possibly Active',
    '14-day: low confidence': 'Low Confidence',
    '7-day: highly likely': 'Highly Likely',
    '7-day: possibly active': 'Possibly Active',
    '7-day: low confidence': 'Low Confidence',
    'highly likely': 'Highly Likely',
    'possibly active': 'Possibly Active',
    'low confidence': 'Low Confidence'
}

# ---------------------------------------------------------------------
# Normalize daily reports by FileDate

dfs_by_date: Dict[pd.Timestamp, pd.DataFrame] = {}
print("\n✅ Daily files successfully parsed by FileDate:")

for key, df in dfs.items():
    df.columns = df.columns.str.strip()
    if 'FileDate' not in df.columns:
        continue

    df = df.copy()
    if pd.api.types.is_datetime64_any_dtype(df['FileDate']):
        df['FileDate'] = pd.to_datetime(df['FileDate']).dt.normalize()
    else:
        df['FileDate'] = pd.to_datetime(
            df['FileDate'].astype(str).str.zfill(8),
            format='%Y%m%d', errors='coerce'
        ).dt.normalize()

    valid_dates = df['FileDate'].dropna().unique()
    if len(valid_dates) > 0:
        dfs[key] = df
        for dt in valid_dates:
            dfs_by_date[dt] = df
        print(f"- {key} → {[d.strftime('%Y-%m-%d') for d in valid_dates]}")

# ---------------------------------------------------------------------
# Backup and clean forecast logs

backup_folder = r'Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup'
os.makedirs(backup_folder, exist_ok=True)
print("\n🔄 Backing up and cleaning existing forecast logs...")

for subfolder in subfolders:
    partner_name = os.path.basename(subfolder).strip()
    log_path = os.path.join(subfolder, "forecast_log.xlsx")
    if os.path.exists(log_path):
        backup_path = os.path.join(backup_folder, f"{partner_name}_forecast_log_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx")
        shutil.copy2(log_path, backup_path)
        print(f"  Backed up {partner_name} → {backup_path}")
        os.remove(log_path)
        print(f"   Deleted original {partner_name} log")

print("\n" + "="*60)
print(" Starting fresh data processing with clean normalization...")
print("="*60)

# ---------------------------------------------------------------------
# Process forecast logs per partner

for subfolder in subfolders:
    partner_name = os.path.basename(subfolder).strip()
    partner_clean = partner_name.lower()
    log_key = f"{partner_name}_forecast_log"
    log_path = os.path.join(subfolder, "forecast_log.xlsx")

    if log_key not in excel_dfs:
        print(f" Skipping {partner_name}: No forecast log found.")
        continue

    log_df = excel_dfs[log_key].copy()
    log_df.columns = log_df.columns.str.strip()

    log_df['Forecasted Check Date'] = pd.to_datetime(log_df['Forecasted Check Date'], errors='coerce').dt.normalize()
    log_df['Outcome'] = log_df.get('Outcome', '')
    log_df['Indicator_norm'] = log_df['Indicator'].astype(str).str.strip().str.lower()

    # Normalize confidence
    log_df['Confidence'] = (
        log_df['Confidence']
        .astype(str)
        .str.strip()
        .str.lower()
        .map(CONFIDENCE_MAP)
        .fillna(log_df['Confidence'])
    )

    # Normalize forecast type
    log_df['Forecast Type'] = (
        log_df['Forecast Type']
        .astype(str)
        .str.split(':')
        .str[-1]
        .str.strip()
        .str.title()
    )

    for idx, row in log_df.iterrows():
        check_date = row['Forecasted Check Date']
        indicator_norm = row['Indicator_norm']
        daily_df = dfs_by_date.get(check_date)
        if daily_df is None:
            continue

        if 'Indicator_norm' not in daily_df.columns:
            daily_df['Indicator_norm'] = daily_df['Indicator'].astype(str).str.strip().str.lower()
        if 'Partner_norm' not in daily_df.columns:
            daily_df['Partner_norm'] = daily_df['Partner'].astype(str).str.strip().str.lower()

        subset = daily_df[
            (daily_df['Partner_norm'] == partner_clean) &
            (daily_df['Indicator_norm'] == indicator_norm)
        ]
        seen = subset['Observed Today'].eq(1).any()
        log_df.at[idx, 'Outcome'] = 'Seen' if seen else 'Not Seen'

    print(f"\n {partner_name} – Outcome counts:")
    print(log_df['Outcome'].value_counts(dropna=False).to_string())
    display(log_df[log_df['Outcome'] == 'Seen'].head(50))

    # Merge with existing file if exists
    if os.path.exists(log_path):
        try:
            existing_df = pd.read_excel(log_path)
            existing_df.columns = existing_df.columns.str.strip()
            existing_df['Confidence'] = (
                existing_df['Confidence']
                .astype(str)
                .str.strip()
                .str.lower()
                .map(CONFIDENCE_MAP)
                .fillna(existing_df['Confidence'])
            )
            existing_df['Forecast Type'] = (
                existing_df['Forecast Type']
                .astype(str)
                .str.split(':')
                .str[-1]
                .str.strip()
                .str.title()
            )
        except Exception as e:
            print(f" Could not read existing file for {partner_name}: {e}")
            existing_df = pd.DataFrame(columns=log_df.columns)
    else:
        existing_df = pd.DataFrame(columns=log_df.columns)

    combined_df = pd.concat([existing_df, log_df], ignore_index=True)
    combined_df['Forecast Date'] = pd.to_datetime(combined_df['Forecast Date'], errors='coerce')

    combined_df['Confidence'] = (
        combined_df['Confidence']
        .astype(str)
        .str.strip()
        .str.lower()
        .map(CONFIDENCE_MAP)
        .fillna(combined_df['Confidence'])
    )
    combined_df['Forecast Type'] = (
        combined_df['Forecast Type']
        .astype(str)
        .str.split(':')
        .str[-1]
        .str.strip()
        .str.title()
    )

    combined_df.drop_duplicates(
        subset=['Indicator', 'Forecast Date', 'Forecast Type', 'Confidence'],
        keep='last', inplace=True
    )

    combined_df.sort_values(by=['Indicator', 'Forecasted Check Date'], inplace=True)
    if 'Indicator_norm' in combined_df.columns:
        combined_df.drop(columns='Indicator_norm', inplace=True)

    try:
        combined_df.to_excel(log_path, index=False)
        print(f" Updated and saved: {log_path}")
    except Exception as e:
        print(f" Failed to save log for {partner_name}: {e}")

✅ Daily files successfully parsed by FileDate:
- full_daily_report_20250616 → ['2025-06-16']
- full_daily_report_20250617 → ['2025-06-17']
- full_daily_report_20250618 → ['2025-06-18']
- full_daily_report_20250623 → ['2025-06-23']
- full_daily_report_20250624 → ['2025-06-24']
- full_daily_report_20250625 → ['2025-06-25']
- full_daily_report_20250626 → ['2025-06-26']
- full_daily_report_20250627 → ['2025-06-27']
- full_daily_report_20250630 → ['2025-06-30']
- full_daily_report_20250701 → ['2025-07-01']

🔄 Backing up and cleaning existing forecast logs...
  Backed up CDC → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\CDC_forecast_log_backup_20250701_141257.xlsx
   Deleted original CDC log
  Backed up CMS → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\CMS_forecast_log_backup_20250701_141257.xlsx
   Deleted original CMS log
  Backed up DHA → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\DHA_forecast_log_backup_20250701_141257.xlsx
   Deleted original DHA log
  Backed up FDA → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\FDA_forecast_log_backup_20250701_141257.xlsx
   Deleted original FDA log
  Backed up HHS → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\HHS_forecast_log_backup_20250701_141257.xlsx
   Deleted original HHS log
  Backed up HRSA → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\HRSA_forecast_log_backup_20250701_141257.xlsx
   Deleted original HRSA log
  Backed up IHS → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\IHS_forecast_log_backup_20250701_141257.xlsx
   Deleted original IHS log
  Backed up NIH → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\NIH_forecast_log_backup_20250701_141257.xlsx
   Deleted original NIH log
  Backed up OS → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\OS_forecast_log_backup_20250701_141257.xlsx
   Deleted original OS log
  Backed up VA → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\VA_forecast_log_backup_20250701_141257.xlsx
   Deleted original VA log

============================================================
 Starting fresh data processing with clean normalization...
============================================================

 CDC – Outcome counts:
Outcome
Pending     7422
Not Seen    1948
Seen          68

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
210,104.21.48.1,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.21.48.1
212,104.21.48.1,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.21.48.1
213,104.21.48.1,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.21.48.1
215,104.21.48.1,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.21.48.1
218,104.21.48.1,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.21.48.1
221,104.21.48.1,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.21.48.1
222,104.21.54.132,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.21.54.132
230,104.21.54.132,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.21.54.132
233,104.21.54.132,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.21.54.132
411,148.153.189.62,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,148.153.189.62
422,148.153.189.62,2025-06-23,7-Day,Possibly Active,2025-06-30,Seen,148.153.189.62
557,156.146.63.133,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,156.146.63.133
782,156.146.63.180,2025-06-16,7-Day,Low Confidence,2025-06-23,Seen,156.146.63.180
848,162.142.125.242,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,162.142.125.242
851,162.142.125.242,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,162.142.125.242
854,162.142.125.242,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,162.142.125.242
858,162.142.125.247,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,162.142.125.247
863,162.142.125.247,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,162.142.125.247
866,162.142.125.247,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,162.142.125.247
869,162.142.125.247,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,162.142.125.247
870,162.142.125.255,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,162.142.125.255
872,162.142.125.255,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,162.142.125.255
873,162.142.125.255,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,162.142.125.255
878,162.142.125.255,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,162.142.125.255
881,162.142.125.255,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,162.142.125.255
996,172.240.108.68,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,172.240.108.68
999,172.240.108.68,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,172.240.108.68
1001,172.240.108.68,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,172.240.108.68
1007,172.240.108.68,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,172.240.108.68
1094,176.65.148.250,2025-06-16,7-Day,Possibly Active,2025-06-23,Seen,176.65.148.250
1097,176.65.148.250,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,176.65.148.250
1109,176.65.149.182,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,176.65.149.182
1136,178.175.129.37,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,178.175.129.37
1253,190.92.174.36,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,190.92.174.36
1379,193.163.125.108,2025-06-17,7-Day,Low Confidence,2025-06-24,Seen,193.163.125.108
1389,193.163.125.109,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,193.163.125.109
1542,195.3.221.137,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,195.3.221.137
1571,196.251.70.216,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,196.251.70.216
1691,196.251.84.199,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,196.251.84.199
1842,204.76.203.206,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,204.76.203.206
1998,23.205.105.180,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,23.205.105.180
2000,23.205.105.180,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,23.205.105.180
2070,34.160.111.145,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,34.160.111.145
2073,34.160.111.145,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,34.160.111.145
2081,34.160.111.145,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,34.160.111.145
2220,45.142.193.91,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,45.142.193.91
2718,51.158.205.47,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,51.158.205.47
2723,51.158.205.47,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,51.158.205.47
2744,61.95.255.74,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,61.95.255.74
2871,64.64.112.157,2025-06-17,14-Day,Low Confidence,2025-07-01,Seen,64.64.112.157

C:\Users\jaskew\AppData\Local\Temp\ipykernel_26812\1209747276.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

✅ Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\CDC\forecast_log.xlsx

 CMS – Outcome counts:
Outcome
Pending     26458
Not Seen     5421
Seen         1496

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
24,101.89.174.236,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,101.89.174.236
26,101.89.174.236,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,101.89.174.236
27,101.89.174.236,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,101.89.174.236
29,101.89.174.236,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,101.89.174.236
32,101.89.174.236,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,101.89.174.236
35,101.89.174.236,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,101.89.174.236
108,103.149.86.208,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.149.86.208
111,103.149.86.208,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.149.86.208
119,103.149.86.208,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.149.86.208
177,103.203.59.0,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
179,103.203.59.0,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,103.203.59.0
180,103.203.59.0,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.203.59.0
182,103.203.59.0,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.203.59.0
185,103.203.59.0,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,103.203.59.0
188,103.203.59.0,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
213,103.61.44.100,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.61.44.100
224,103.61.44.100,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.61.44.100
383,104.152.52.238,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.238
444,104.156.155.35,2025-06-17,14-Day,Low Confidence,2025-07-01,Seen,104.156.155.35
467,104.18.32.191,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.18.32.191
477,104.18.68.40,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.18.68.40
479,104.18.68.40,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.18.68.40
482,104.18.68.40,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.18.68.40
488,104.18.68.40,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.18.68.40
494,104.18.69.40,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.18.69.40
497,104.18.69.40,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.18.69.40
504,104.192.3.74,2025-06-17,14-Day,Low Confidence,2025-07-01,Seen,104.192.3.74
506,104.192.3.74,2025-06-17,7-Day,Low Confidence,2025-06-24,Seen,104.192.3.74
549,104.21.48.1,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.21.48.1
551,104.21.48.1,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.21.48.1
552,104.21.48.1,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.21.48.1
554,104.21.48.1,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.21.48.1
557,104.21.48.1,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.21.48.1
560,104.21.48.1,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.21.48.1
600,104.234.115.162,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.234.115.162
605,104.234.115.162,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.234.115.162
623,104.234.115.77,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.234.115.77
624,104.234.115.77,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.234.115.77
626,104.234.115.77,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.234.115.77
635,104.237.131.164,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.131.164
636,104.237.131.164,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.237.131.164
638,104.237.131.164,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.237.131.164
645,104.237.151.205,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.237.151.205
647,104.237.151.205,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.151.205
648,104.237.151.205,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.237.151.205
650,104.237.151.205,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.237.151.205
656,104.237.151.205,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.237.151.205
681,106.54.32.10,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,106.54.32.10
683,106.54.32.10,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,106.54.32.10
684,106.54.32.10,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,106.54.32.10

C:\Users\jaskew\AppData\Local\Temp\ipykernel_26812\1209747276.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

✅ Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\CMS\forecast_log.xlsx

 DHA – Outcome counts:
Outcome
Pending     20420
Not Seen     4284
Seen         1054

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
29,103.108.229.67,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.108.229.67
41,103.108.231.51,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.108.231.51
53,103.108.231.67,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.108.231.67
77,103.136.147.130,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.136.147.130
89,103.136.147.4,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.136.147.4
159,103.203.59.0,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
162,103.203.59.0,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.203.59.0
164,103.203.59.0,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.203.59.0
170,103.203.59.0,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
188,103.214.20.131,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.214.20.131
212,103.216.220.19,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,103.216.220.19
224,103.216.220.35,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,103.216.220.35
231,103.61.44.100,2025-06-16,14-Day,Possibly Active,2025-06-30,Seen,103.61.44.100
242,103.61.44.100,2025-06-23,7-Day,Low Confidence,2025-06-30,Seen,103.61.44.100
260,103.75.11.51,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.75.11.51
272,103.75.11.67,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.75.11.67
305,104.131.6.219,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.131.6.219
315,104.160.6.2,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.160.6.2
317,104.160.6.2,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.160.6.2
318,104.160.6.2,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.160.6.2
320,104.160.6.2,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.160.6.2
323,104.160.6.2,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.160.6.2
326,104.160.6.2,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.160.6.2
375,104.234.115.77,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.234.115.77
383,104.234.115.77,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.234.115.77
386,104.234.115.77,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.234.115.77
387,104.237.131.164,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.237.131.164
390,104.237.131.164,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.237.131.164
392,104.237.131.164,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.237.131.164
398,104.237.131.164,2025-06-23,7-Day,Possibly Active,2025-06-30,Seen,104.237.131.164
399,104.237.151.205,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.237.151.205
404,104.237.151.205,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.237.151.205
410,104.237.151.205,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.237.151.205
423,107.174.224.18,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,107.174.224.18
425,107.174.224.18,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,107.174.224.18
426,107.174.224.18,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,107.174.224.18
428,107.174.224.18,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,107.174.224.18
431,107.174.224.18,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,107.174.224.18
434,107.174.224.18,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,107.174.224.18
459,111.67.197.113,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,111.67.197.113
461,111.67.197.113,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,111.67.197.113
470,111.67.197.113,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,111.67.197.113
522,118.193.59.10,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,118.193.59.10
530,118.193.59.10,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,118.193.59.10
533,118.193.59.10,2025-06-23,7-Day,Low Confidence,2025-06-30,Seen,118.193.59.10
548,118.26.111.94,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,118.26.111.94
551,118.26.111.94,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,118.26.111.94
584,120.48.45.123,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,120.48.45.123
639,123.58.209.112,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,123.58.209.112
642,123.58.209.112,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,123.58.209.112

C:\Users\jaskew\AppData\Local\Temp\ipykernel_26812\1209747276.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

✅ Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\DHA\forecast_log.xlsx

 FDA – Outcome counts:
Outcome
Pending     18418
Not Seen     3565
Seen         1006

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
24,101.89.174.236,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,101.89.174.236
26,101.89.174.236,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,101.89.174.236
27,101.89.174.236,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,101.89.174.236
29,101.89.174.236,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,101.89.174.236
32,101.89.174.236,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,101.89.174.236
35,101.89.174.236,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,101.89.174.236
75,103.149.86.208,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,103.149.86.208
132,103.203.59.0,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
134,103.203.59.0,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,103.203.59.0
135,103.203.59.0,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.203.59.0
137,103.203.59.0,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.203.59.0
140,103.203.59.0,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,103.203.59.0
143,103.203.59.0,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
341,104.156.155.31,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.156.155.31
344,104.156.155.31,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.156.155.31
401,104.234.115.77,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.234.115.77
411,104.237.131.164,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.237.131.164
413,104.237.131.164,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.237.131.164
422,104.237.151.205,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.151.205
423,104.237.151.205,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.237.151.205
444,106.54.32.10,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,106.54.32.10
446,106.54.32.10,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,106.54.32.10
447,106.54.32.10,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,106.54.32.10
449,106.54.32.10,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,106.54.32.10
452,106.54.32.10,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,106.54.32.10
455,106.54.32.10,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,106.54.32.10
480,107.174.224.18,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,107.174.224.18
482,107.174.224.18,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,107.174.224.18
483,107.174.224.18,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,107.174.224.18
485,107.174.224.18,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,107.174.224.18
488,107.174.224.18,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,107.174.224.18
491,107.174.224.18,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,107.174.224.18
563,112.102.196.2,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,112.102.196.2
606,115.190.15.27,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,115.190.15.27
608,115.190.15.27,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,115.190.15.27
609,115.190.15.27,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,115.190.15.27
611,115.190.15.27,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,115.190.15.27
614,115.190.15.27,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,115.190.15.27
617,115.190.15.27,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,115.190.15.27
660,118.193.59.10,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,118.193.59.10
668,118.193.59.10,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,118.193.59.10
671,118.193.59.10,2025-06-23,7-Day,Low Confidence,2025-06-30,Seen,118.193.59.10
684,118.26.111.94,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,118.26.111.94
686,118.26.111.94,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,118.26.111.94
692,118.26.111.94,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,118.26.111.94
695,118.26.111.94,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,118.26.111.94
705,119.96.59.16,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,119.96.59.16
707,119.96.59.16,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,119.96.59.16
708,119.96.59.16,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,119.96.59.16
710,119.96.59.16,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,119.96.59.16

C:\Users\jaskew\AppData\Local\Temp\ipykernel_26812\1209747276.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

✅ Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\FDA\forecast_log.xlsx

 HHS – Outcome counts:
Outcome
Pending     9571
Not Seen    2761
Seen         187

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
26,103.125.146.77,2025-06-16,7-Day,Possibly Active,2025-06-23,Seen,103.125.146.77
32,103.125.146.77,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,103.125.146.77
116,104.21.54.132,2025-06-18,7-Day,Low Confidence,2025-06-25,Seen,104.21.54.132
194,107.189.3.94,2025-06-16,7-Day,Low Confidence,2025-06-23,Seen,107.189.3.94
224,107.189.8.16,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,107.189.8.16
257,118.193.72.187,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,118.193.72.187
260,118.193.72.187,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,118.193.72.187
276,119.200.13.201,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,119.200.13.201
278,119.200.13.201,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,119.200.13.201
279,119.200.13.201,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,119.200.13.201
281,119.200.13.201,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,119.200.13.201
284,119.200.13.201,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,119.200.13.201
287,119.200.13.201,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,119.200.13.201
326,136.144.43.81,2025-06-16,7-Day,Possibly Active,2025-06-23,Seen,136.144.43.81
332,136.144.43.81,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,136.144.43.81
353,138.199.21.209,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,138.199.21.209
356,138.199.21.209,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,138.199.21.209
408,141.98.11.57,2025-06-16,14-Day,Low Confidence,2025-06-30,Seen,141.98.11.57
410,141.98.11.57,2025-06-16,7-Day,Low Confidence,2025-06-23,Seen,141.98.11.57
411,141.98.11.57,2025-06-17,14-Day,Low Confidence,2025-07-01,Seen,141.98.11.57
413,141.98.11.57,2025-06-17,7-Day,Low Confidence,2025-06-24,Seen,141.98.11.57
416,141.98.11.57,2025-06-18,7-Day,Low Confidence,2025-06-25,Seen,141.98.11.57
419,141.98.11.57,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,141.98.11.57
488,146.70.112.126,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,146.70.112.126
515,146.70.165.227,2025-06-18,7-Day,Low Confidence,2025-06-25,Seen,146.70.165.227
560,146.70.192.174,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,146.70.192.174
575,146.70.204.164,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,146.70.204.164
578,146.70.204.164,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,146.70.204.164
602,146.70.204.166,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,146.70.204.166
671,146.70.204.172,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,146.70.204.172
686,146.70.204.173,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,146.70.204.173
848,146.70.45.166,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,146.70.45.166
851,146.70.45.166,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,146.70.45.166
854,146.70.45.166,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,146.70.45.166
932,149.102.224.187,2025-06-16,7-Day,Low Confidence,2025-06-23,Seen,149.102.224.187
1163,149.88.27.197,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,149.88.27.197
1199,149.88.27.200,2025-06-17,7-Day,Low Confidence,2025-06-24,Seen,149.88.27.200
1235,149.88.27.205,2025-06-17,7-Day,Low Confidence,2025-06-24,Seen,149.88.27.205
1280,149.88.27.211,2025-06-16,7-Day,Possibly Active,2025-06-23,Seen,149.88.27.211
1482,152.32.128.214,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,152.32.128.214
1484,152.32.128.214,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,152.32.128.214
1485,152.32.128.214,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,152.32.128.214
1487,152.32.128.214,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,152.32.128.214
1490,152.32.128.214,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,152.32.128.214
1493,152.32.128.214,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,152.32.128.214
1562,156.146.63.133,2025-06-17,7-Day,Low Confidence,2025-06-24,Seen,156.146.63.133
1697,156.146.63.174,2025-06-18,7-Day,Low Confidence,2025-06-25,Seen,156.146.63.174
1845,162.142.125.242,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,162.142.125.242
1847,162.142.125.242,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,162.142.125.242
1848,162.142.125.242,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,162.142.125.242

C:\Users\jaskew\AppData\Local\Temp\ipykernel_26812\1209747276.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

✅ Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\HHS\forecast_log.xlsx

 HRSA – Outcome counts:
Outcome
Pending     16333
Not Seen     4441
Seen          139

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
14,101.89.174.236,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,101.89.174.236
119,103.203.59.0,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,103.203.59.0
215,104.152.52.139,2025-06-16,7-Day,Low Confidence,2025-06-23,Seen,104.152.52.139
227,104.152.52.148,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.148
287,104.152.52.237,2025-06-16,7-Day,Possibly Active,2025-06-23,Seen,104.152.52.237
446,104.237.131.164,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.131.164
458,104.237.151.205,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.151.205
500,106.54.32.10,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,106.54.32.10
521,107.174.224.18,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,107.174.224.18
674,115.190.15.27,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,115.190.15.27
791,119.96.59.16,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,119.96.59.16
836,121.196.237.27,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,121.196.237.27
893,124.156.231.182,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,124.156.231.182
908,124.205.213.108,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,124.205.213.108
920,124.239.153.90,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,124.239.153.90
1121,14.103.172.199,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,14.103.172.199
1217,142.93.115.5,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,142.93.115.5
1367,148.113.206.49,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,148.113.206.49
1391,148.153.189.62,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,148.153.189.62
1403,149.102.229.181,2025-06-16,7-Day,Low Confidence,2025-06-23,Seen,149.102.229.181
1463,152.32.128.214,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,152.32.128.214
1550,157.245.227.101,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,157.245.227.101
1721,165.154.135.215,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,165.154.135.215
1838,167.99.13.19,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,167.99.13.19
1898,169.150.223.208,2025-06-16,7-Day,Low Confidence,2025-06-23,Seen,169.150.223.208
2171,176.65.148.234,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,176.65.148.234
2183,176.65.148.236,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,176.65.148.236
2195,176.65.148.250,2025-06-16,7-Day,Possibly Active,2025-06-23,Seen,176.65.148.250
2252,178.128.84.112,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,178.128.84.112
2324,18.117.57.162,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,18.117.57.162
2348,18.221.137.47,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,18.221.137.47
2360,18.223.104.85,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,18.223.104.85
2420,183.224.237.233,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,183.224.237.233
2450,185.12.59.118,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,185.12.59.118
2504,185.129.62.63,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,185.129.62.63
2540,185.169.4.150,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,185.169.4.150
2741,185.241.208.204,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,185.241.208.204
2825,188.166.106.38,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,188.166.106.38
2909,192.155.84.28,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,192.155.84.28
3152,193.163.125.103,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.103
3164,193.163.125.107,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.107
3176,193.163.125.108,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.108
3188,193.163.125.109,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.109
3200,193.163.125.115,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.115
3212,193.163.125.117,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.117
3224,193.163.125.121,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.121
3236,193.163.125.127,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.127
3248,193.163.125.132,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.132
3260,193.163.125.143,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.143
3272,193.163.125.149,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.149

C:\Users\jaskew\AppData\Local\Temp\ipykernel_26812\1209747276.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

✅ Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\HRSA\forecast_log.xlsx

 IHS – Outcome counts:
Outcome
Pending     16012
Not Seen     3226
Seen          859

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
36,103.203.59.0,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
38,103.203.59.0,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,103.203.59.0
39,103.203.59.0,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.203.59.0
41,103.203.59.0,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.203.59.0
44,103.203.59.0,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,103.203.59.0
47,103.203.59.0,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
192,104.192.3.74,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.192.3.74
195,104.192.3.74,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.192.3.74
200,104.192.3.74,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.192.3.74
203,104.192.3.74,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.192.3.74
207,104.21.20.66,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,104.21.20.66
228,104.234.115.162,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.234.115.162
233,104.234.115.162,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.234.115.162
239,104.234.115.162,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.234.115.162
245,104.234.115.167,2025-06-17,7-Day,Low Confidence,2025-06-24,Seen,104.234.115.167
248,104.234.115.167,2025-06-18,7-Day,Low Confidence,2025-06-25,Seen,104.234.115.167
255,104.234.115.77,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.234.115.77
266,104.237.131.164,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.131.164
267,104.237.131.164,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.237.131.164
269,104.237.131.164,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.237.131.164
272,104.237.131.164,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.237.131.164
276,104.237.151.205,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.237.151.205
278,104.237.151.205,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.151.205
279,104.237.151.205,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.237.151.205
281,104.237.151.205,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.237.151.205
287,104.237.151.205,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.237.151.205
290,104.244.73.193,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.244.73.193
291,104.244.79.50,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.244.79.50
294,104.244.79.50,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.244.79.50
299,104.244.79.50,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.244.79.50
302,104.244.79.50,2025-06-23,7-Day,Possibly Active,2025-06-30,Seen,104.244.79.50
327,107.174.224.18,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,107.174.224.18
329,107.174.224.18,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,107.174.224.18
330,107.174.224.18,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,107.174.224.18
332,107.174.224.18,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,107.174.224.18
335,107.174.224.18,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,107.174.224.18
338,107.174.224.18,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,107.174.224.18
353,107.189.3.148,2025-06-18,7-Day,Possibly Active,2025-06-25,Seen,107.189.3.148
359,107.189.3.94,2025-06-18,7-Day,Possibly Active,2025-06-25,Seen,107.189.3.94
362,107.189.3.94,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,107.189.3.94
363,107.189.31.187,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,107.189.31.187
365,107.189.31.187,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,107.189.31.187
368,107.189.31.187,2025-06-18,7-Day,Possibly Active,2025-06-25,Seen,107.189.31.187
371,107.189.31.187,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,107.189.31.187
377,107.189.6.124,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,107.189.6.124
378,107.189.8.16,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,107.189.8.16
383,107.189.8.16,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,107.189.8.16
434,118.193.59.10,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,118.193.59.10
435,118.193.59.10,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,118.193.59.10
437,118.193.59.10,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,118.193.59.10

C:\Users\jaskew\AppData\Local\Temp\ipykernel_26812\1209747276.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

✅ Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\IHS\forecast_log.xlsx

 NIH – Outcome counts:
Outcome
Pending     28067
Not Seen     7556
Seen          332

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
192,103.203.59.0,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
194,103.203.59.0,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,103.203.59.0
200,103.203.59.0,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,103.203.59.0
203,103.203.59.0,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
285,103.53.40.64,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,103.53.40.64
426,104.18.32.191,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.18.32.191
429,104.18.32.191,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.18.32.191
431,104.18.32.191,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.18.32.191
437,104.18.32.191,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.18.32.191
536,104.21.3.76,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.21.3.76
539,104.21.3.76,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.21.3.76
542,104.21.3.76,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.21.3.76
765,104.234.115.167,2025-06-17,14-Day,Low Confidence,2025-07-01,Seen,104.234.115.167
917,107.174.224.18,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,107.174.224.18
1671,148.113.206.49,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,148.113.206.49
1673,148.113.206.49,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,148.113.206.49
1674,148.113.206.49,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,148.113.206.49
1676,148.113.206.49,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,148.113.206.49
1679,148.113.206.49,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,148.113.206.49
1682,148.113.206.49,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,148.113.206.49
1794,15.156.234.60,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,15.156.234.60
1799,15.156.234.60,2025-06-18,7-Day,Low Confidence,2025-06-25,Seen,15.156.234.60
2321,159.203.98.153,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,159.203.98.153
2469,161.35.53.231,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,161.35.53.231
2471,161.35.53.231,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,161.35.53.231
2474,161.35.53.231,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,161.35.53.231
2477,161.35.53.231,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,161.35.53.231
2490,162.142.125.242,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,162.142.125.242
2492,162.142.125.242,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,162.142.125.242
2493,162.142.125.242,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,162.142.125.242
2495,162.142.125.242,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,162.142.125.242
2498,162.142.125.242,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,162.142.125.242
2501,162.142.125.242,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,162.142.125.242
2684,165.154.217.112,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,165.154.217.112
2747,165.232.138.158,2025-06-16,7-Day,Low Confidence,2025-06-23,Seen,165.232.138.158
2852,170.64.166.144,2025-06-23,7-Day,Possibly Active,2025-06-30,Seen,170.64.166.144
2879,172.203.234.251,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,172.203.234.251
2882,172.203.234.251,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,172.203.234.251
2913,172.240.108.68,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,172.240.108.68
2915,172.240.108.68,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,172.240.108.68
2916,172.240.108.68,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,172.240.108.68
2918,172.240.108.68,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,172.240.108.68
2921,172.240.108.68,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,172.240.108.68
2924,172.240.108.68,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,172.240.108.68
3170,176.65.148.234,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,176.65.148.234
3191,176.65.148.250,2025-06-16,7-Day,Low Confidence,2025-06-23,Seen,176.65.148.250
3194,176.65.148.250,2025-06-17,7-Day,Low Confidence,2025-06-24,Seen,176.65.148.250
3197,176.65.148.250,2025-06-18,7-Day,Low Confidence,2025-06-25,Seen,176.65.148.250
3218,176.65.149.182,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,176.65.149.182
3230,178.128.84.112,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,178.128.84.112

C:\Users\jaskew\AppData\Local\Temp\ipykernel_26812\1209747276.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

✅ Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\NIH\forecast_log.xlsx

 OS – Outcome counts:
Outcome
Pending     16440
Not Seen     3068
Seen          850

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
12,101.89.174.236,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,101.89.174.236
117,103.203.59.0,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
119,103.203.59.0,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,103.203.59.0
120,103.203.59.0,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.203.59.0
122,103.203.59.0,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.203.59.0
125,103.203.59.0,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,103.203.59.0
189,104.152.52.110,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.110
198,104.152.52.139,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.139
203,104.152.52.139,2025-06-18,7-Day,Possibly Active,2025-06-25,Seen,104.152.52.139
242,104.152.52.225,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.225
279,104.152.52.242,2025-06-17,14-Day,Low Confidence,2025-07-01,Seen,104.152.52.242
305,104.156.155.35,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.156.155.35
306,104.156.155.35,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.156.155.35
341,104.237.131.164,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.131.164
350,104.237.151.205,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.151.205
351,104.237.151.205,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.237.151.205
353,104.237.151.205,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.237.151.205
366,106.54.32.10,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,106.54.32.10
374,106.54.32.10,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,106.54.32.10
384,107.174.224.18,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,107.174.224.18
387,107.174.224.18,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,107.174.224.18
389,107.174.224.18,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,107.174.224.18
392,107.174.224.18,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,107.174.224.18
405,107.189.30.69,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,107.189.30.69
416,109.70.100.5,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,109.70.100.5
422,109.70.100.6,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,109.70.100.6
491,118.193.59.10,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,118.193.59.10
494,118.193.59.10,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,118.193.59.10
500,118.193.72.187,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,118.193.72.187
512,118.26.111.94,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,118.26.111.94
545,120.48.45.123,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,120.48.45.123
548,120.48.45.123,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,120.48.45.123
558,121.196.237.27,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,121.196.237.27
560,121.196.237.27,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,121.196.237.27
635,124.156.231.182,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,124.156.231.182
642,124.198.131.108,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,124.198.131.108
662,124.239.153.90,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,124.239.153.90
734,136.144.43.81,2025-06-18,7-Day,Possibly Active,2025-06-25,Seen,136.144.43.81
864,142.93.115.5,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,142.93.115.5
866,142.93.115.5,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,142.93.115.5
867,142.93.115.5,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,142.93.115.5
924,146.70.112.126,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,146.70.112.126
929,146.70.112.126,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,146.70.112.126
932,146.70.112.126,2025-06-18,7-Day,Possibly Active,2025-06-25,Seen,146.70.112.126
963,146.70.45.166,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,146.70.45.166
983,148.113.152.91,2025-06-18,7-Day,Possibly Active,2025-06-25,Seen,148.113.152.91
984,148.113.206.49,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,148.113.206.49
986,148.113.206.49,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,148.113.206.49
987,148.113.206.49,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,148.113.206.49
989,148.113.206.49,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,148.113.206.49

C:\Users\jaskew\AppData\Local\Temp\ipykernel_26812\1209747276.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

✅ Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\OS\forecast_log.xlsx

 VA – Outcome counts:
Outcome
Pending     19438
Not Seen     3377
Seen         1065

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
69,103.149.86.208,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.149.86.208
72,103.149.86.208,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.149.86.208
122,103.191.76.181,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,103.191.76.181
125,103.191.76.181,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,103.191.76.181
174,103.61.44.100,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.61.44.100
177,103.61.44.100,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.61.44.100
210,104.128.161.233,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.128.161.233
215,104.128.161.233,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.128.161.233
225,104.152.52.105,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.152.52.105
227,104.152.52.105,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.105
228,104.152.52.105,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.105
230,104.152.52.105,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.152.52.105
233,104.152.52.105,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.105
234,104.152.52.110,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.152.52.110
236,104.152.52.110,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.110
237,104.152.52.110,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.110
239,104.152.52.110,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.152.52.110
242,104.152.52.110,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.110
245,104.152.52.139,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.139
246,104.152.52.139,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.139
248,104.152.52.139,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.152.52.139
251,104.152.52.139,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.139
252,104.152.52.148,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.152.52.148
254,104.152.52.148,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.148
255,104.152.52.148,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.148
257,104.152.52.148,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.152.52.148
260,104.152.52.148,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.148
261,104.152.52.155,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.152.52.155
263,104.152.52.155,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.155
264,104.152.52.155,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.155
269,104.152.52.155,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.155
273,104.152.52.212,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.212
278,104.152.52.212,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.212
282,104.152.52.216,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.216
287,104.152.52.216,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.216
291,104.152.52.225,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.225
293,104.152.52.225,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.152.52.225
299,104.152.52.237,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.237
300,104.152.52.237,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.237
302,104.152.52.237,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.152.52.237
305,104.152.52.237,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.237
308,104.152.52.238,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.238
309,104.152.52.238,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.238
314,104.152.52.238,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.238
317,104.152.52.239,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.239
318,104.152.52.239,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.239
320,104.152.52.239,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.152.52.239
323,104.152.52.239,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.239
324,104.152.52.242,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.152.52.242
326,104.152.52.242,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.242

C:\Users\jaskew\AppData\Local\Temp\ipykernel_26812\1209747276.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

✅ Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\VA\forecast_log.xlsx