In [119]:
import os
import pandas as pd

folder_path = r"Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Full Daily Reports"
files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]
files

['full_daily_report_20250616.csv',
 'full_daily_report_20250617.csv',
 'full_daily_report_20250618.csv',
 'full_daily_report_20250623.csv',
 'full_daily_report_20250624.csv',
 'full_daily_report_20250625.csv',
 'full_daily_report_20250626.csv',
 'full_daily_report_20250627.csv',
 'full_daily_report_20250630.csv']

In [120]:
dfs = {}
for file_name in files:
    file_path = os.path.join(folder_path, file_name)
    var_name = os.path.splitext(file_name)[0]  # Remove .csv extension
    dfs[var_name] = pd.read_csv(file_path)
    print(f"Loaded {file_name} into dfs['{var_name}'], shape: {dfs[var_name].shape}")

# Example of accessing a specific DataFrame
df_example = dfs['full_daily_report_20250616']

Loaded full_daily_report_20250616.csv into dfs['full_daily_report_20250616'], shape: (6395, 12)
Loaded full_daily_report_20250617.csv into dfs['full_daily_report_20250617'], shape: (6751, 12)
Loaded full_daily_report_20250618.csv into dfs['full_daily_report_20250618'], shape: (7082, 12)
Loaded full_daily_report_20250623.csv into dfs['full_daily_report_20250623'], shape: (7408, 12)
Loaded full_daily_report_20250624.csv into dfs['full_daily_report_20250624'], shape: (7509, 12)
Loaded full_daily_report_20250625.csv into dfs['full_daily_report_20250625'], shape: (7533, 12)
Loaded full_daily_report_20250626.csv into dfs['full_daily_report_20250626'], shape: (8007, 12)
Loaded full_daily_report_20250627.csv into dfs['full_daily_report_20250627'], shape: (8433, 12)
Loaded full_daily_report_20250630.csv into dfs['full_daily_report_20250630'], shape: (8514, 12)

In [121]:
display(df_example.head())

,Indicator,Observed Today,Frequency (7d),Frequency (30d),Probability: 7-Day,Confidence: 7-Day,Probability: 14-Day,Confidence: 14-Day,Probability: 30-Day,Confidence: 30-Day,Partner,FileDate
0,102.129.153.158,0,0.0,1.0,6.88%,7-Day: Low confidence,13.68%,14-Day: Low confidence,68.66%,30-Day: Possibly active,CDC,20250616
1,102.129.153.43,0,0.0,0.0,0.38%,7-Day: Low confidence,0.93%,14-Day: Low confidence,18.11%,30-Day: Low confidence,CDC,20250616
2,102.129.153.71,0,0.0,2.0,12.39%,7-Day: Low confidence,24.8%,14-Day: Low confidence,86.71%,30-Day: Highly likely,CDC,20250616
3,102.165.16.161,0,0.0,0.0,0.01%,7-Day: Low confidence,0.01%,14-Day: Low confidence,0.17%,30-Day: Low confidence,CDC,20250616
4,103.133.107.28,0,0.0,1.0,9.14%,7-Day: Low confidence,59.14%,14-Day: Possibly active,73.35%,30-Day: Possibly active,CDC,20250616

In [122]:
# List all subfolders in folder_path
logs_folder = r'Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs'

subfolders = [f.path for f in os.scandir(logs_folder) if f.is_dir()]
for subfolder in subfolders:
    print(f"Folder: {os.path.basename(subfolder)}")
    subfolder_files = [f for f in os.listdir(subfolder) if os.path.isfile(os.path.join(subfolder, f))]
    print(f"  Files: {subfolder_files}")

Folder: CDC
  Files: ['CDC_forecast_log.xlsx', 'forecast_log.xlsx', '~$forecast_log_2025-06-23.xlsx']
Folder: CMS
  Files: ['CMS_forecast_log.xlsx', 'forecast_log.xlsx']
Folder: DHA
  Files: ['DHA_forecast_log.xlsx', 'forecast_log.xlsx']
Folder: FDA
  Files: ['FDA_forecast_log.xlsx', 'forecast_log.xlsx']
Folder: HHS
  Files: ['forecast_log.xlsx', 'HHS_forecast_log.xlsx']
Folder: HRSA
  Files: ['forecast_log.xlsx', 'HRSA_forecast_log.xlsx']
Folder: IHS
  Files: ['forecast_log.xlsx', 'IHS_forecast_log.xlsx']
Folder: NIH
  Files: ['forecast_log.xlsx', 'NIH_forecast_log.xlsx']
Folder: OS
  Files: ['forecast_log.xlsx', 'OS_forecast_log.xlsx']
Folder: VA
  Files: ['forecast_log.xlsx', 'VA_forecast_log.xlsx', '~$forecast_log.xlsx']

In [123]:
excel_dfs = {}
for subfolder in subfolders:
    subfolder_files = [f for f in os.listdir(subfolder) if os.path.isfile(os.path.join(subfolder, f))]
    for file in subfolder_files:
        # Skip temporary Excel files (usually start with '~$')
        if file.endswith('.xlsx') and not file.startswith('~$'):
            file_full_path = os.path.join(subfolder, file)
            var_base = os.path.splitext(file)[0]
            excel_dfs[var_base] = pd.read_excel(file_full_path, engine='openpyxl')
            print(f"Loaded {file} from {os.path.basename(subfolder)} into excel_dfs['{var_base}'], shape: {excel_dfs[var_base].shape}")

Loaded CDC_forecast_log.xlsx from CDC into excel_dfs['CDC_forecast_log'], shape: (8361, 6)
Loaded forecast_log.xlsx from CDC into excel_dfs['forecast_log'], shape: (8361, 6)
Loaded CMS_forecast_log.xlsx from CMS into excel_dfs['CMS_forecast_log'], shape: (29319, 6)
Loaded forecast_log.xlsx from CMS into excel_dfs['forecast_log'], shape: (29319, 6)
Loaded DHA_forecast_log.xlsx from DHA into excel_dfs['DHA_forecast_log'], shape: (22518, 6)
Loaded forecast_log.xlsx from DHA into excel_dfs['forecast_log'], shape: (22518, 6)
Loaded FDA_forecast_log.xlsx from FDA into excel_dfs['FDA_forecast_log'], shape: (20034, 6)
Loaded forecast_log.xlsx from FDA into excel_dfs['forecast_log'], shape: (20034, 6)
Loaded forecast_log.xlsx from HHS into excel_dfs['forecast_log'], shape: (11286, 6)
Loaded HHS_forecast_log.xlsx from HHS into excel_dfs['HHS_forecast_log'], shape: (11286, 6)
Loaded forecast_log.xlsx from HRSA into excel_dfs['forecast_log'], shape: (18786, 6)
Loaded HRSA_forecast_log.xlsx from HRSA into excel_dfs['HRSA_forecast_log'], shape: (18786, 6)
Loaded forecast_log.xlsx from IHS into excel_dfs['forecast_log'], shape: (17502, 6)
Loaded IHS_forecast_log.xlsx from IHS into excel_dfs['IHS_forecast_log'], shape: (17502, 6)
Loaded forecast_log.xlsx from NIH into excel_dfs['forecast_log'], shape: (31875, 6)
Loaded NIH_forecast_log.xlsx from NIH into excel_dfs['NIH_forecast_log'], shape: (31875, 6)
Loaded forecast_log.xlsx from OS into excel_dfs['forecast_log'], shape: (17679, 6)
Loaded OS_forecast_log.xlsx from OS into excel_dfs['OS_forecast_log'], shape: (17679, 6)
Loaded forecast_log.xlsx from VA into excel_dfs['forecast_log'], shape: (20772, 6)
Loaded VA_forecast_log.xlsx from VA into excel_dfs['VA_forecast_log'], shape: (20772, 6)

In [124]:
display(excel_dfs['VA_forecast_log'].head())

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome
0,1-you.njalla.no,2025-06-16,14-Day,Possibly active,2025-06-30,Not Seen
1,1-you.njalla.no,2025-06-16,30-Day,Possibly active,2025-07-16,Pending
2,1-you.njalla.no,2025-06-16,7-Day,Low confidence,2025-06-23,Not Seen
3,1-you.njalla.no,2025-06-17,14-Day,Possibly active,2025-07-01,Pending
4,1-you.njalla.no,2025-06-17,30-Day,Possibly active,2025-07-17,Pending

In [125]:
import os
from datetime import datetime
from typing import Dict

import pandas as pd
from IPython.display import display

# ---------------------------------------------------------------------
# Assumed provided elsewhere in notebook/script:
#   dfs        – dict[str, pd.DataFrame] of loaded daily reports
#   subfolders – iterable of partner subfolder paths
#   excel_dfs  – dict[str, pd.DataFrame] of loaded forecast logs
# ---------------------------------------------------------------------

# Build a lookup: FileDate → daily DataFrame (normalized to datetime only)
dfs_by_date: Dict[pd.Timestamp, pd.DataFrame] = {}

print("\n✅ Daily files successfully parsed by FileDate:")
for key, df in dfs.items():
    if 'FileDate' not in df.columns:
        continue

    df = df.copy()
    df['FileDate'] = pd.to_datetime(
        df['FileDate'].astype(str).str.zfill(8),
        format='%Y%m%d',
        errors='coerce'
    ).dt.normalize()

    valid_dates = df['FileDate'].dropna().unique()
    if len(valid_dates) > 0:
        dfs[key] = df  # Save normalized DataFrame
        for dt in valid_dates:
            dfs_by_date[dt] = df  # Last one wins if duplicated
        print(f"- {key} → {[d.strftime('%Y-%m-%d') for d in valid_dates]}")

# ---------------------------------------------------------------------
# Process and update each partner forecast log
for subfolder in subfolders:
    partner_name = os.path.basename(subfolder).strip()
    partner_clean = partner_name.lower()
    log_key = f"{partner_name}_forecast_log"
    log_path = os.path.join(subfolder, "forecast_log.xlsx")  # path to save

    if log_key not in excel_dfs:
        print(f"⚠️ Skipping {partner_name}: No forecast log found.")
        continue

    log_df = excel_dfs[log_key].copy()

    log_df['Forecasted Check Date'] = pd.to_datetime(
        log_df['Forecasted Check Date'],
        errors='coerce'
    ).dt.normalize()

    if 'Outcome' not in log_df.columns:
        log_df['Outcome'] = ''

    for idx, row in log_df.iterrows():
        check_date = row['Forecasted Check Date']
        indicator_norm = str(row['Indicator']).strip().lower()

        daily_df = dfs_by_date.get(check_date)
        if daily_df is None:
            continue  # no report for that date

        # Normalize once per DataFrame
        if 'Indicator_norm' not in daily_df.columns:
            daily_df['Indicator_norm'] = daily_df['Indicator'].astype(str).str.strip().str.lower()
        if 'Partner_norm' not in daily_df.columns:
            daily_df['Partner_norm'] = daily_df['Partner'].astype(str).str.strip().str.lower()

        subset = daily_df[
            (daily_df['Partner_norm'] == partner_clean) &
            (daily_df['Indicator_norm'] == indicator_norm)
        ]

        seen = subset['Observed Today'].eq(1).any()
        log_df.at[idx, 'Outcome'] = 'Seen' if seen else 'Not Seen'

    # Print outcome summary for partner
    print(f"\n📊 {partner_name} – Outcome counts:")
    print(log_df['Outcome'].value_counts(dropna=False).to_string())

    # Preview top 50 'Seen' outcomes
    display(log_df[log_df['Outcome'] == 'Seen'].head(50))

    # -----------------------------------------------------------------
        # Merge with existing saved file (if it exists), and keep only new
    if os.path.exists(log_path):
        try:
            existing_df = pd.read_excel(log_path)
        except Exception as e:
            print(f"⚠️ Could not read existing file for {partner_name}: {e}")
            existing_df = pd.DataFrame(columns=log_df.columns)
    else:
        existing_df = pd.DataFrame(columns=log_df.columns)

    combined_df = pd.concat([existing_df, log_df], ignore_index=True)
    combined_df.drop_duplicates(inplace=True)

    # ✅ Sort/group by Indicator for better readability
    combined_df.sort_values(by=['Indicator', 'Forecasted Check Date'], inplace=True)

    # Save merged file
    try:
        combined_df.to_excel(log_path, index=False)
        print(f"Updated and grouped log written to: {log_path}")
    except Exception as e:
        print(f"Failed to save log for {partner_name}: {e}")

✅ Daily files successfully parsed by FileDate:
- full_daily_report_20250616 → ['2025-06-16']
- full_daily_report_20250617 → ['2025-06-17']
- full_daily_report_20250618 → ['2025-06-18']
- full_daily_report_20250623 → ['2025-06-23']
- full_daily_report_20250624 → ['2025-06-24']
- full_daily_report_20250625 → ['2025-06-25']
- full_daily_report_20250626 → ['2025-06-26']
- full_daily_report_20250627 → ['2025-06-27']
- full_daily_report_20250630 → ['2025-06-30']

📊 CDC – Outcome counts:
Outcome
Pending     6942
Not Seen    1378
Seen          41

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome
210,104.21.48.1,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
212,104.21.48.1,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
215,104.21.48.1,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
218,104.21.48.1,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
221,104.21.48.1,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
222,104.21.54.132,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
230,104.21.54.132,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
233,104.21.54.132,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
411,148.153.189.62,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
422,148.153.189.62,2025-06-23,7-Day,Possibly active,2025-06-30,Seen
557,156.146.63.133,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
782,156.146.63.180,2025-06-16,7-Day,Low confidence,2025-06-23,Seen
848,162.142.125.242,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
851,162.142.125.242,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
854,162.142.125.242,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
858,162.142.125.247,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
863,162.142.125.247,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
866,162.142.125.247,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
869,162.142.125.247,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
870,162.142.125.255,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
872,162.142.125.255,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
878,162.142.125.255,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
881,162.142.125.255,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
996,172.240.108.68,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
1001,172.240.108.68,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
1007,172.240.108.68,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
1094,176.65.148.250,2025-06-16,7-Day,Possibly active,2025-06-23,Seen
1097,176.65.148.250,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
1109,176.65.149.182,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
1136,178.175.129.37,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
1253,190.92.174.36,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
1379,193.163.125.108,2025-06-17,7-Day,Low confidence,2025-06-24,Seen
1571,196.251.70.216,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
1691,196.251.84.199,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
2000,23.205.105.180,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
2070,34.160.111.145,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
2081,34.160.111.145,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
2723,51.158.205.47,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
2744,61.95.255.74,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
3005,68.69.186.86,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
3314,91.90.122.24,2025-06-17,7-Day,Highly likely,2025-06-24,Seen

Updated and grouped log written to: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\CDC\forecast_log.xlsx

📊 CMS – Outcome counts:
Outcome
Pending     24454
Not Seen     3944
Seen          921

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome
24,101.89.174.236,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
26,101.89.174.236,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
29,101.89.174.236,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
32,101.89.174.236,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
35,101.89.174.236,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
108,103.149.86.208,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
119,103.149.86.208,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
177,103.203.59.0,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
179,103.203.59.0,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
182,103.203.59.0,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
185,103.203.59.0,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
188,103.203.59.0,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
213,103.61.44.100,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
224,103.61.44.100,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
383,104.152.52.238,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
467,104.18.32.191,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
477,104.18.68.40,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
479,104.18.68.40,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
482,104.18.68.40,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
488,104.18.68.40,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
494,104.18.69.40,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
497,104.18.69.40,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
506,104.192.3.74,2025-06-17,7-Day,Low confidence,2025-06-24,Seen
549,104.21.48.1,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
551,104.21.48.1,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
554,104.21.48.1,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
557,104.21.48.1,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
560,104.21.48.1,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
605,104.234.115.162,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
623,104.234.115.77,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
626,104.234.115.77,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
635,104.237.131.164,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
638,104.237.131.164,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
645,104.237.151.205,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
647,104.237.151.205,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
650,104.237.151.205,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
656,104.237.151.205,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
681,106.54.32.10,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
683,106.54.32.10,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
686,106.54.32.10,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
689,106.54.32.10,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
692,106.54.32.10,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
705,107.174.224.18,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
707,107.174.224.18,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
710,107.174.224.18,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
713,107.174.224.18,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
716,107.174.224.18,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
753,107.189.13.254,2025-06-16,14-Day,Possibly active,2025-06-30,Seen
764,107.189.13.254,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
785,107.189.3.94,2025-06-18,7-Day,Highly likely,2025-06-25,Seen

Updated and grouped log written to: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\CMS\forecast_log.xlsx

📊 DHA – Outcome counts:
Outcome
Pending     18742
Not Seen     2987
Seen          789

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome
29,103.108.229.67,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
41,103.108.231.51,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
53,103.108.231.67,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
77,103.136.147.130,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
89,103.136.147.4,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
159,103.203.59.0,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
164,103.203.59.0,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
170,103.203.59.0,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
188,103.214.20.131,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
212,103.216.220.19,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
224,103.216.220.35,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
231,103.61.44.100,2025-06-16,14-Day,Possibly active,2025-06-30,Seen
242,103.61.44.100,2025-06-23,7-Day,Low confidence,2025-06-30,Seen
260,103.75.11.51,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
272,103.75.11.67,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
305,104.131.6.219,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
315,104.160.6.2,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
317,104.160.6.2,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
320,104.160.6.2,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
323,104.160.6.2,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
326,104.160.6.2,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
375,104.234.115.77,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
383,104.234.115.77,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
386,104.234.115.77,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
387,104.237.131.164,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
392,104.237.131.164,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
398,104.237.131.164,2025-06-23,7-Day,Possibly active,2025-06-30,Seen
399,104.237.151.205,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
404,104.237.151.205,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
410,104.237.151.205,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
423,107.174.224.18,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
425,107.174.224.18,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
428,107.174.224.18,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
431,107.174.224.18,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
434,107.174.224.18,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
459,111.67.197.113,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
461,111.67.197.113,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
470,111.67.197.113,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
522,118.193.59.10,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
530,118.193.59.10,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
533,118.193.59.10,2025-06-23,7-Day,Low confidence,2025-06-30,Seen
548,118.26.111.94,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
551,118.26.111.94,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
584,120.48.45.123,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
639,123.58.209.112,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
650,123.58.209.112,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
677,129.227.46.131,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
689,129.227.46.163,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
692,129.227.46.163,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
797,136.144.43.81,2025-06-17,7-Day,Highly likely,2025-06-24,Seen

Updated and grouped log written to: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\DHA\forecast_log.xlsx

📊 FDA – Outcome counts:
Outcome
Pending     16820
Not Seen     2527
Seen          687

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome
24,101.89.174.236,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
26,101.89.174.236,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
29,101.89.174.236,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
32,101.89.174.236,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
35,101.89.174.236,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
132,103.203.59.0,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
134,103.203.59.0,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
137,103.203.59.0,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
140,103.203.59.0,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
143,103.203.59.0,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
341,104.156.155.31,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
344,104.156.155.31,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
401,104.234.115.77,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
413,104.237.131.164,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
422,104.237.151.205,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
444,106.54.32.10,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
446,106.54.32.10,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
449,106.54.32.10,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
452,106.54.32.10,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
455,106.54.32.10,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
480,107.174.224.18,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
482,107.174.224.18,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
485,107.174.224.18,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
488,107.174.224.18,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
491,107.174.224.18,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
563,112.102.196.2,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
606,115.190.15.27,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
608,115.190.15.27,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
611,115.190.15.27,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
614,115.190.15.27,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
617,115.190.15.27,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
660,118.193.59.10,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
668,118.193.59.10,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
671,118.193.59.10,2025-06-23,7-Day,Low confidence,2025-06-30,Seen
684,118.26.111.94,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
686,118.26.111.94,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
692,118.26.111.94,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
695,118.26.111.94,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
705,119.96.59.16,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
707,119.96.59.16,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
710,119.96.59.16,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
713,119.96.59.16,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
716,119.96.59.16,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
731,120.48.45.123,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
734,120.48.45.123,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
759,121.196.237.27,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
761,121.196.237.27,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
764,121.196.237.27,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
767,121.196.237.27,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
770,121.196.237.27,2025-06-23,7-Day,Highly likely,2025-06-30,Seen

Updated and grouped log written to: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\FDA\forecast_log.xlsx

📊 HHS – Outcome counts:
Outcome
Pending     9179
Not Seen    1940
Seen         167

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome
26,103.125.146.77,2025-06-16,7-Day,Possibly active,2025-06-23,Seen
32,103.125.146.77,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
116,104.21.54.132,2025-06-18,7-Day,Low confidence,2025-06-25,Seen
194,107.189.3.94,2025-06-16,7-Day,Low confidence,2025-06-23,Seen
224,107.189.8.16,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
257,118.193.72.187,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
260,118.193.72.187,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
276,119.200.13.201,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
278,119.200.13.201,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
281,119.200.13.201,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
284,119.200.13.201,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
287,119.200.13.201,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
326,136.144.43.81,2025-06-16,7-Day,Possibly active,2025-06-23,Seen
332,136.144.43.81,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
353,138.199.21.209,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
356,138.199.21.209,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
408,141.98.11.57,2025-06-16,14-Day,Low confidence,2025-06-30,Seen
410,141.98.11.57,2025-06-16,7-Day,Low confidence,2025-06-23,Seen
413,141.98.11.57,2025-06-17,7-Day,Low confidence,2025-06-24,Seen
416,141.98.11.57,2025-06-18,7-Day,Low confidence,2025-06-25,Seen
419,141.98.11.57,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
488,146.70.112.126,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
515,146.70.165.227,2025-06-18,7-Day,Low confidence,2025-06-25,Seen
560,146.70.192.174,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
575,146.70.204.164,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
578,146.70.204.164,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
602,146.70.204.166,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
671,146.70.204.172,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
686,146.70.204.173,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
848,146.70.45.166,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
851,146.70.45.166,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
854,146.70.45.166,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
932,149.102.224.187,2025-06-16,7-Day,Low confidence,2025-06-23,Seen
1163,149.88.27.197,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
1199,149.88.27.200,2025-06-17,7-Day,Low confidence,2025-06-24,Seen
1235,149.88.27.205,2025-06-17,7-Day,Low confidence,2025-06-24,Seen
1280,149.88.27.211,2025-06-16,7-Day,Possibly active,2025-06-23,Seen
1482,152.32.128.214,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
1484,152.32.128.214,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1487,152.32.128.214,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
1490,152.32.128.214,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
1493,152.32.128.214,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
1562,156.146.63.133,2025-06-17,7-Day,Low confidence,2025-06-24,Seen
1697,156.146.63.174,2025-06-18,7-Day,Low confidence,2025-06-25,Seen
1845,162.142.125.242,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
1847,162.142.125.242,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1850,162.142.125.242,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
1853,162.142.125.242,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
1856,162.142.125.242,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
1857,162.142.125.247,2025-06-16,14-Day,Highly likely,2025-06-30,Seen

Updated and grouped log written to: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\HHS\forecast_log.xlsx

📊 HRSA – Outcome counts:
Outcome
Pending     15586
Not Seen     3061
Seen          139

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome
14,101.89.174.236,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
119,103.203.59.0,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
215,104.152.52.139,2025-06-16,7-Day,Low confidence,2025-06-23,Seen
227,104.152.52.148,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
287,104.152.52.237,2025-06-16,7-Day,Possibly active,2025-06-23,Seen
446,104.237.131.164,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
458,104.237.151.205,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
500,106.54.32.10,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
521,107.174.224.18,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
674,115.190.15.27,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
791,119.96.59.16,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
836,121.196.237.27,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
893,124.156.231.182,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
908,124.205.213.108,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
920,124.239.153.90,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1121,14.103.172.199,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1217,142.93.115.5,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1367,148.113.206.49,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1391,148.153.189.62,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1403,149.102.229.181,2025-06-16,7-Day,Low confidence,2025-06-23,Seen
1463,152.32.128.214,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1550,157.245.227.101,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1721,165.154.135.215,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1838,167.99.13.19,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1898,169.150.223.208,2025-06-16,7-Day,Low confidence,2025-06-23,Seen
2171,176.65.148.234,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2183,176.65.148.236,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2195,176.65.148.250,2025-06-16,7-Day,Possibly active,2025-06-23,Seen
2252,178.128.84.112,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2324,18.117.57.162,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2348,18.221.137.47,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2360,18.223.104.85,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2420,183.224.237.233,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2450,185.12.59.118,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2504,185.129.62.63,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2540,185.169.4.150,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2741,185.241.208.204,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2825,188.166.106.38,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2909,192.155.84.28,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3152,193.163.125.103,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3164,193.163.125.107,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3176,193.163.125.108,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3188,193.163.125.109,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3200,193.163.125.115,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3212,193.163.125.117,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3224,193.163.125.121,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3236,193.163.125.127,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3248,193.163.125.132,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3260,193.163.125.143,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3272,193.163.125.149,2025-06-16,7-Day,Highly likely,2025-06-23,Seen

Updated and grouped log written to: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\HRSA\forecast_log.xlsx

📊 IHS – Outcome counts:
Outcome
Pending     14630
Not Seen     2289
Seen          583

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome
36,103.203.59.0,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
38,103.203.59.0,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
41,103.203.59.0,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
44,103.203.59.0,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
47,103.203.59.0,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
192,104.192.3.74,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
200,104.192.3.74,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
203,104.192.3.74,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
228,104.234.115.162,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
233,104.234.115.162,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
239,104.234.115.162,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
245,104.234.115.167,2025-06-17,7-Day,Low confidence,2025-06-24,Seen
248,104.234.115.167,2025-06-18,7-Day,Low confidence,2025-06-25,Seen
266,104.237.131.164,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
269,104.237.131.164,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
272,104.237.131.164,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
276,104.237.151.205,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
278,104.237.151.205,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
281,104.237.151.205,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
287,104.237.151.205,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
290,104.244.73.193,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
291,104.244.79.50,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
299,104.244.79.50,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
302,104.244.79.50,2025-06-23,7-Day,Possibly active,2025-06-30,Seen
327,107.174.224.18,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
329,107.174.224.18,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
332,107.174.224.18,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
335,107.174.224.18,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
338,107.174.224.18,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
353,107.189.3.148,2025-06-18,7-Day,Possibly active,2025-06-25,Seen
359,107.189.3.94,2025-06-18,7-Day,Possibly active,2025-06-25,Seen
362,107.189.3.94,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
365,107.189.31.187,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
368,107.189.31.187,2025-06-18,7-Day,Possibly active,2025-06-25,Seen
371,107.189.31.187,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
377,107.189.6.124,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
383,107.189.8.16,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
434,118.193.59.10,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
437,118.193.59.10,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
440,118.193.59.10,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
461,118.26.111.94,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
464,118.26.111.94,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
489,119.96.59.16,2025-06-16,14-Day,Low confidence,2025-06-30,Seen
500,119.96.59.16,2025-06-23,7-Day,Possibly active,2025-06-30,Seen
578,123.58.209.112,2025-06-18,7-Day,Possibly active,2025-06-25,Seen
584,124.198.131.108,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
608,128.14.236.99,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
906,142.93.115.5,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
908,142.93.115.5,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
911,142.93.115.5,2025-06-17,7-Day,Highly likely,2025-06-24,Seen

Updated and grouped log written to: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\IHS\forecast_log.xlsx

📊 NIH – Outcome counts:
Outcome
Pending     26280
Not Seen     5358
Seen          237

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome
192,103.203.59.0,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
194,103.203.59.0,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
200,103.203.59.0,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
203,103.203.59.0,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
426,104.18.32.191,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
431,104.18.32.191,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
437,104.18.32.191,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
536,104.21.3.76,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
539,104.21.3.76,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
542,104.21.3.76,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
917,107.174.224.18,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
1671,148.113.206.49,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
1673,148.113.206.49,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1676,148.113.206.49,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
1679,148.113.206.49,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
1682,148.113.206.49,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
1799,15.156.234.60,2025-06-18,7-Day,Low confidence,2025-06-25,Seen
2321,159.203.98.153,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
2471,161.35.53.231,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
2474,161.35.53.231,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
2477,161.35.53.231,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
2490,162.142.125.242,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
2492,162.142.125.242,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2495,162.142.125.242,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
2498,162.142.125.242,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
2501,162.142.125.242,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
2684,165.154.217.112,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
2747,165.232.138.158,2025-06-16,7-Day,Low confidence,2025-06-23,Seen
2852,170.64.166.144,2025-06-23,7-Day,Possibly active,2025-06-30,Seen
2879,172.203.234.251,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
2882,172.203.234.251,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
2913,172.240.108.68,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
2915,172.240.108.68,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
2918,172.240.108.68,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
2921,172.240.108.68,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
2924,172.240.108.68,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
3170,176.65.148.234,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
3191,176.65.148.250,2025-06-16,7-Day,Low confidence,2025-06-23,Seen
3194,176.65.148.250,2025-06-17,7-Day,Low confidence,2025-06-24,Seen
3197,176.65.148.250,2025-06-18,7-Day,Low confidence,2025-06-25,Seen
3218,176.65.149.182,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
3230,178.128.84.112,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3336,18.117.57.162,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
3344,18.117.57.162,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
3347,18.117.57.162,2025-06-23,7-Day,Highly likely,2025-06-30,Seen
3374,18.221.137.47,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3389,18.223.104.85,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
3528,185.12.59.118,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
3530,185.12.59.118,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
3533,185.12.59.118,2025-06-17,7-Day,Highly likely,2025-06-24,Seen

Updated and grouped log written to: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\NIH\forecast_log.xlsx

📊 OS – Outcome counts:
Outcome
Pending     15150
Not Seen     1994
Seen          535

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome
117,103.203.59.0,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
119,103.203.59.0,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
122,103.203.59.0,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
125,103.203.59.0,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
203,104.152.52.139,2025-06-18,7-Day,Possibly active,2025-06-25,Seen
242,104.152.52.225,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
305,104.156.155.35,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
341,104.237.131.164,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
350,104.237.151.205,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
353,104.237.151.205,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
366,106.54.32.10,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
374,106.54.32.10,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
384,107.174.224.18,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
389,107.174.224.18,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
392,107.174.224.18,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
405,107.189.30.69,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
416,109.70.100.5,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
422,109.70.100.6,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
491,118.193.59.10,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
494,118.193.59.10,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
500,118.193.72.187,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
512,118.26.111.94,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
545,120.48.45.123,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
548,120.48.45.123,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
558,121.196.237.27,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
560,121.196.237.27,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
635,124.156.231.182,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
662,124.239.153.90,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
734,136.144.43.81,2025-06-18,7-Day,Possibly active,2025-06-25,Seen
864,142.93.115.5,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
866,142.93.115.5,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
924,146.70.112.126,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
929,146.70.112.126,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
932,146.70.112.126,2025-06-18,7-Day,Possibly active,2025-06-25,Seen
983,148.113.152.91,2025-06-18,7-Day,Possibly active,2025-06-25,Seen
984,148.113.206.49,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
986,148.113.206.49,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
989,148.113.206.49,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
1079,152.32.128.214,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
1091,155.94.155.19,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
1094,155.94.155.19,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
1142,159.203.44.105,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
1211,164.92.191.35,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
1212,165.154.135.215,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
1214,165.154.135.215,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1217,165.154.135.215,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
1220,165.154.135.215,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
1235,165.154.54.189,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
1305,167.99.13.19,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
1307,167.99.13.19,2025-06-16,7-Day,Highly likely,2025-06-23,Seen

Updated and grouped log written to: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\OS\forecast_log.xlsx

📊 VA – Outcome counts:
Outcome
Pending     17906
Not Seen     2179
Seen          687

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome
69,103.149.86.208,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
122,103.191.76.181,2025-06-17,7-Day,Possibly active,2025-06-24,Seen
125,103.191.76.181,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
174,103.61.44.100,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
215,104.128.161.233,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
225,104.152.52.105,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
227,104.152.52.105,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
230,104.152.52.105,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
233,104.152.52.105,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
234,104.152.52.110,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
236,104.152.52.110,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
239,104.152.52.110,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
242,104.152.52.110,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
245,104.152.52.139,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
248,104.152.52.139,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
251,104.152.52.139,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
252,104.152.52.148,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
254,104.152.52.148,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
257,104.152.52.148,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
260,104.152.52.148,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
261,104.152.52.155,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
263,104.152.52.155,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
269,104.152.52.155,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
278,104.152.52.212,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
287,104.152.52.216,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
293,104.152.52.225,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
299,104.152.52.237,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
302,104.152.52.237,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
305,104.152.52.237,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
308,104.152.52.238,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
314,104.152.52.238,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
317,104.152.52.239,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
320,104.152.52.239,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
323,104.152.52.239,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
324,104.152.52.242,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
326,104.152.52.242,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
332,104.152.52.242,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
347,104.156.155.31,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
350,104.156.155.31,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
440,104.234.115.162,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
449,104.234.115.167,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
452,104.234.115.167,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
456,104.234.115.77,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
461,104.234.115.77,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
467,104.237.131.164,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
470,104.237.131.164,2025-06-17,7-Day,Highly likely,2025-06-24,Seen
473,104.237.131.164,2025-06-18,7-Day,Highly likely,2025-06-25,Seen
474,104.237.151.205,2025-06-16,14-Day,Highly likely,2025-06-30,Seen
476,104.237.151.205,2025-06-16,7-Day,Highly likely,2025-06-23,Seen
479,104.237.151.205,2025-06-17,7-Day,Highly likely,2025-06-24,Seen

Updated and grouped log written to: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\VA\forecast_log.xlsx