In [1]:
import os
import pandas as pd

folder_path = r"Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Full Daily Reports"
files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]
files

['full_daily_report_20250616.csv',
 'full_daily_report_20250617.csv',
 'full_daily_report_20250618.csv',
 'full_daily_report_20250623.csv',
 'full_daily_report_20250624.csv',
 'full_daily_report_20250625.csv',
 'full_daily_report_20250626.csv',
 'full_daily_report_20250627.csv',
 'full_daily_report_20250630.csv',
 'full_daily_report_20250701.csv',
 'full_daily_report_20250702.csv',
 'full_daily_report_20250703.csv',
 'full_daily_report_20250707.csv',
 'full_daily_report_20250708.csv',
 'full_daily_report_20250709.csv',
 'full_daily_report_20250710.csv',
 'full_daily_report_20250711.csv',
 'full_daily_report_20250714.csv',
 'full_daily_report_20250715.csv',
 'full_daily_report_20250716.csv',
 'full_daily_report_20250717.csv',
 'full_daily_report_20250718.csv',
 'full_daily_report_20250721.csv',
 'full_daily_report_20250722.csv',
 'full_daily_report_20250723.csv',
 'full_daily_report_20250724.csv',
 'full_daily_report_20250725.csv',
 'full_daily_report_20250728.csv']

In [2]:
from datetime import datetime

# Get today's date in the same format as the file names (YYYYMMDD)
today_str = datetime.now().strftime('%Y%m%d')

# Filter files that contain today's date
current_date_files = [f for f in files if today_str in f]
current_date_files

['full_daily_report_20250728.csv']

In [3]:
dfs = {}
for file_name in files:
    file_path = os.path.join(folder_path, file_name)
    var_name = os.path.splitext(file_name)[0]  # Remove .csv extension
    dfs[var_name] = pd.read_csv(file_path)
    print(f"Loaded {file_name} into dfs['{var_name}'], shape: {dfs[var_name].shape}")

# Example of accessing a specific DataFrame
df_example = dfs['full_daily_report_20250616']

Loaded full_daily_report_20250616.csv into dfs['full_daily_report_20250616'], shape: (6395, 12)
Loaded full_daily_report_20250617.csv into dfs['full_daily_report_20250617'], shape: (6751, 12)
Loaded full_daily_report_20250618.csv into dfs['full_daily_report_20250618'], shape: (7082, 12)
Loaded full_daily_report_20250623.csv into dfs['full_daily_report_20250623'], shape: (7408, 12)
Loaded full_daily_report_20250624.csv into dfs['full_daily_report_20250624'], shape: (7509, 12)
Loaded full_daily_report_20250625.csv into dfs['full_daily_report_20250625'], shape: (7533, 12)
Loaded full_daily_report_20250626.csv into dfs['full_daily_report_20250626'], shape: (8007, 12)
Loaded full_daily_report_20250627.csv into dfs['full_daily_report_20250627'], shape: (8433, 12)
Loaded full_daily_report_20250630.csv into dfs['full_daily_report_20250630'], shape: (8514, 12)
Loaded full_daily_report_20250701.csv into dfs['full_daily_report_20250701'], shape: (9050, 12)
Loaded full_daily_report_20250702.csv into dfs['full_daily_report_20250702'], shape: (9243, 12)
Loaded full_daily_report_20250703.csv into dfs['full_daily_report_20250703'], shape: (9450, 12)
Loaded full_daily_report_20250707.csv into dfs['full_daily_report_20250707'], shape: (9810, 12)
Loaded full_daily_report_20250708.csv into dfs['full_daily_report_20250708'], shape: (9861, 12)
Loaded full_daily_report_20250709.csv into dfs['full_daily_report_20250709'], shape: (9901, 12)
Loaded full_daily_report_20250710.csv into dfs['full_daily_report_20250710'], shape: (9969, 12)
Loaded full_daily_report_20250711.csv into dfs['full_daily_report_20250711'], shape: (10020, 12)
Loaded full_daily_report_20250714.csv into dfs['full_daily_report_20250714'], shape: (10252, 12)
Loaded full_daily_report_20250715.csv into dfs['full_daily_report_20250715'], shape: (10284, 12)
Loaded full_daily_report_20250716.csv into dfs['full_daily_report_20250716'], shape: (10340, 12)
Loaded full_daily_report_20250717.csv into dfs['full_daily_report_20250717'], shape: (10370, 12)
Loaded full_daily_report_20250718.csv into dfs['full_daily_report_20250718'], shape: (2591, 12)
Loaded full_daily_report_20250721.csv into dfs['full_daily_report_20250721'], shape: (10468, 12)
Loaded full_daily_report_20250722.csv into dfs['full_daily_report_20250722'], shape: (10546, 12)
Loaded full_daily_report_20250723.csv into dfs['full_daily_report_20250723'], shape: (8595, 12)
Loaded full_daily_report_20250724.csv into dfs['full_daily_report_20250724'], shape: (5251, 12)
Loaded full_daily_report_20250725.csv into dfs['full_daily_report_20250725'], shape: (8621, 12)
Loaded full_daily_report_20250728.csv into dfs['full_daily_report_20250728'], shape: (8980, 12)

In [4]:
display(df_example.head())

,Indicator,Observed Today,Frequency (7d),Frequency (30d),Probability: 7-Day,Confidence: 7-Day,Probability: 14-Day,Confidence: 14-Day,Probability: 30-Day,Confidence: 30-Day,Partner,FileDate
0,102.129.153.158,0,0.0,1.0,6.88%,7-Day: Low confidence,13.68%,14-Day: Low confidence,68.66%,30-Day: Possibly active,CDC,20250616
1,102.129.153.43,0,0.0,0.0,0.38%,7-Day: Low confidence,0.93%,14-Day: Low confidence,18.11%,30-Day: Low confidence,CDC,20250616
2,102.129.153.71,0,0.0,2.0,12.39%,7-Day: Low confidence,24.8%,14-Day: Low confidence,86.71%,30-Day: Highly likely,CDC,20250616
3,102.165.16.161,0,0.0,0.0,0.01%,7-Day: Low confidence,0.01%,14-Day: Low confidence,0.17%,30-Day: Low confidence,CDC,20250616
4,103.133.107.28,0,0.0,1.0,9.14%,7-Day: Low confidence,59.14%,14-Day: Possibly active,73.35%,30-Day: Possibly active,CDC,20250616

In [5]:
# List all subfolders in folder_path
logs_folder = r'Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs'

subfolders = [f.path for f in os.scandir(logs_folder) if f.is_dir()]
for subfolder in subfolders:
    print(f"Folder: {os.path.basename(subfolder)}")
    subfolder_files = [f for f in os.listdir(subfolder) if os.path.isfile(os.path.join(subfolder, f))]
    print(f"  Files: {subfolder_files}")

Folder: CDC
  Files: ['CDC_forecast_log.xlsx', 'forecast_log.xlsx', '~$forecast_log_2025-06-23.xlsx']
Folder: CMS
  Files: ['CMS_forecast_log.xlsx', 'forecast_log.xlsx']
Folder: DHA
  Files: ['DHA_forecast_log.xlsx', 'forecast_log.xlsx']
Folder: FDA
  Files: ['FDA_forecast_log.xlsx', 'forecast_log.xlsx']
Folder: HHS
  Files: ['forecast_log.xlsx', 'HHS_forecast_log.xlsx']
Folder: HRSA
  Files: ['forecast_log.xlsx', 'HRSA_forecast_log.xlsx']
Folder: IHS
  Files: ['forecast_log.xlsx', 'IHS_forecast_log.xlsx']
Folder: NIH
  Files: ['forecast_log.xlsx', 'NIH_forecast_log.xlsx']
Folder: OS
  Files: ['forecast_log.xlsx', 'OS_forecast_log.xlsx']
Folder: VA
  Files: ['forecast_log.xlsx', 'VA_forecast_log.xlsx']

In [6]:
excel_dfs = {}
for subfolder in subfolders:
    subfolder_files = [f for f in os.listdir(subfolder) if os.path.isfile(os.path.join(subfolder, f))]
    for file in subfolder_files:
        # Skip temporary Excel files (usually start with '~$')
        if file.endswith('.xlsx') and not file.startswith('~$'):
            file_full_path = os.path.join(subfolder, file)
            var_base = os.path.splitext(file)[0]
            excel_dfs[var_base] = pd.read_excel(file_full_path, engine='openpyxl')
            print(f"Loaded {file} from {os.path.basename(subfolder)} into excel_dfs['{var_base}'], shape: {excel_dfs[var_base].shape}")

Loaded CDC_forecast_log.xlsx from CDC into excel_dfs['CDC_forecast_log'], shape: (37659, 6)
Loaded forecast_log.xlsx from CDC into excel_dfs['forecast_log'], shape: (34500, 6)
Loaded CMS_forecast_log.xlsx from CMS into excel_dfs['CMS_forecast_log'], shape: (123216, 6)
Loaded forecast_log.xlsx from CMS into excel_dfs['forecast_log'], shape: (112308, 6)
Loaded DHA_forecast_log.xlsx from DHA into excel_dfs['DHA_forecast_log'], shape: (100101, 6)
Loaded forecast_log.xlsx from DHA into excel_dfs['forecast_log'], shape: (90870, 6)
Loaded FDA_forecast_log.xlsx from FDA into excel_dfs['FDA_forecast_log'], shape: (92484, 6)
Loaded forecast_log.xlsx from FDA into excel_dfs['forecast_log'], shape: (83781, 6)
Loaded forecast_log.xlsx from HHS into excel_dfs['forecast_log'], shape: (22326, 6)
Loaded HHS_forecast_log.xlsx from HHS into excel_dfs['HHS_forecast_log'], shape: (26085, 6)
Loaded forecast_log.xlsx from HRSA into excel_dfs['forecast_log'], shape: (59601, 6)
Loaded HRSA_forecast_log.xlsx from HRSA into excel_dfs['HRSA_forecast_log'], shape: (64635, 6)
Loaded forecast_log.xlsx from IHS into excel_dfs['forecast_log'], shape: (73668, 6)
Loaded IHS_forecast_log.xlsx from IHS into excel_dfs['IHS_forecast_log'], shape: (81393, 6)
Loaded forecast_log.xlsx from NIH into excel_dfs['forecast_log'], shape: (116757, 6)
Loaded NIH_forecast_log.xlsx from NIH into excel_dfs['NIH_forecast_log'], shape: (127032, 6)
Loaded forecast_log.xlsx from OS into excel_dfs['forecast_log'], shape: (75867, 6)
Loaded OS_forecast_log.xlsx from OS into excel_dfs['OS_forecast_log'], shape: (84543, 6)
Loaded forecast_log.xlsx from VA into excel_dfs['forecast_log'], shape: (95481, 6)
Loaded VA_forecast_log.xlsx from VA into excel_dfs['VA_forecast_log'], shape: (106413, 6)

In [7]:
display(excel_dfs['VA_forecast_log'].head())

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome
0,1-you.njalla.no,2025-06-16,14-Day,Possibly active,2025-06-30,Not Seen
1,1-you.njalla.no,2025-06-16,30-Day,Possibly active,2025-07-16,Pending
2,1-you.njalla.no,2025-06-16,7-Day,Low confidence,2025-06-23,Not Seen
3,1-you.njalla.no,2025-06-17,14-Day,Possibly active,2025-07-01,Pending
4,1-you.njalla.no,2025-06-17,30-Day,Possibly active,2025-07-17,Pending

In [ ]:
import os
import shutil
from datetime import datetime
from typing import Dict
import pandas as pd
from IPython.display import display
from concurrent.futures import ThreadPoolExecutor

# ---------------------------------------------------------------------
# Normalize helper
CONFIDENCE_MAP = {
    '30-day: highly likely': 'Highly Likely',
    '30-day: possibly active': 'Possibly Active',
    '30-day: low confidence': 'Low Confidence',
    '14-day: highly likely': 'Highly Likely',
    '14-day: possibly active': 'Possibly Active',
    '14-day: low confidence': 'Low Confidence',
    '7-day: highly likely': 'Highly Likely',
    '7-day: possibly active': 'Possibly Active',
    '7-day: low confidence': 'Low Confidence',
    'highly likely': 'Highly Likely',
    'possibly active': 'Possibly Active',
    'low confidence': 'Low Confidence'
}

# ---------------------------------------------------------------------
# Normalize daily reports by FileDate
dfs_by_date: Dict[pd.Timestamp, pd.DataFrame] = {}
print("\n✅ Daily files successfully parsed by FileDate:")
for key, df in dfs.items():
    df.columns = df.columns.str.strip()
    if 'FileDate' not in df.columns:
        continue
    df = df.copy()
    df['FileDate'] = pd.to_datetime(df['FileDate'], errors='coerce').dt.normalize()
    valid_dates = df['FileDate'].dropna().unique()
    if valid_dates.size > 0:
        dfs[key] = df
        dfs_by_date.update({dt: df for dt in valid_dates})
        print(f"- {key} → {[d.strftime('%Y-%m-%d') for d in valid_dates]}")

# ---------------------------------------------------------------------
# Backup and clean forecast logs
backup_folder = r'Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup'
os.makedirs(backup_folder, exist_ok=True)
print("\n🔄 Backing up and cleaning existing forecast logs...")

def backup_and_clean_logs(subfolder):
    partner_name = os.path.basename(subfolder).strip()
    log_path = os.path.join(subfolder, "forecast_log.xlsx")
    if os.path.exists(log_path):
        backup_path = os.path.join(backup_folder, f"{partner_name}_forecast_log_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx")
        shutil.copy2(log_path, backup_path)
        print(f"  Backed up {partner_name} → {backup_path}")
        os.remove(log_path)
        print(f"   Deleted original {partner_name} log")

with ThreadPoolExecutor() as executor:
    executor.map(backup_and_clean_logs, subfolders)

print("\n" + "="*60)
print(" Starting fresh data processing with clean normalization...")
print("="*60)

# ---------------------------------------------------------------------
# Process forecast logs per partner
def process_partner_logs(subfolder):
    partner_name = os.path.basename(subfolder).strip()
    partner_clean = partner_name.lower()
    log_key = f"{partner_name}_forecast_log"
    log_path = os.path.join(subfolder, "forecast_log.xlsx")
    if log_key not in excel_dfs:
        print(f" Skipping {partner_name}: No forecast log found.")
        return
    log_df = excel_dfs[log_key].copy()
    log_df.columns = log_df.columns.str.strip()
    log_df['Forecasted Check Date'] = pd.to_datetime(log_df['Forecasted Check Date'], errors='coerce').dt.normalize()
    log_df['Outcome'] = log_df.get('Outcome', '')
    log_df['Indicator_norm'] = log_df['Indicator'].astype(str).str.strip().str.lower()
    log_df['Confidence'] = log_df['Confidence'].astype(str).str.strip().str.lower().map(CONFIDENCE_MAP).fillna(log_df['Confidence'])
    log_df['Forecast Type'] = log_df['Forecast Type'].astype(str).str.split(':').str[-1].str.strip().str.title()
    if 'Indicator_norm' not in dfs_by_date:
        dfs_by_date['Indicator_norm'] = dfs_by_date['Indicator'].astype(str).str.strip().str.lower()
    if 'Partner_norm' not in dfs_by_date:
        dfs_by_date['Partner_norm'] = dfs_by_date['Partner'].astype(str).str.strip().str.lower()
    log_df['Outcome'] = log_df.apply(lambda row: 'Seen' if dfs_by_date.get(row['Forecasted Check Date'], pd.DataFrame()).query("Partner_norm == @partner_clean and Indicator_norm == @row['Indicator_norm']").get('Observed Today', pd.Series()).eq(1).any() else 'Not Seen', axis=1)
    print(f"\n {partner_name} – Outcome counts:")
    print(log_df['Outcome'].value_counts(dropna=False).to_string())
    display(log_df[log_df['Outcome'] == 'Seen'].head(50))
    if os.path.exists(log_path):
        try:
            existing_df = pd.read_excel(log_path)
            existing_df.columns = existing_df.columns.str.strip()
            existing_df['Confidence'] = existing_df['Confidence'].astype(str).str.strip().str.lower().map(CONFIDENCE_MAP).fillna(existing_df['Confidence'])
            existing_df['Forecast Type'] = existing_df['Forecast Type'].astype(str).str.split(':').str[-1].str.strip().str.title()
        except Exception as e:
            print(f" Could not read existing file for {partner_name}: {e}")
            existing_df = pd.DataFrame(columns=log_df.columns)
    else:
        existing_df = pd.DataFrame(columns=log_df.columns)
    combined_df = pd.concat([existing_df, log_df], ignore_index=True)
    combined_df['Forecast Date'] = pd.to_datetime(combined_df['Forecast Date'], errors='coerce')
    combined_df['Confidence'] = combined_df['Confidence'].astype(str).str.strip().str.lower().map(CONFIDENCE_MAP).fillna(combined_df['Confidence'])
    combined_df['Forecast Type'] = combined_df['Forecast Type'].astype(str).str.split(':').str[-1].str.strip().str.title()
    combined_df.drop_duplicates(subset=['Indicator', 'Forecast Date', 'Forecast Type', 'Confidence'], keep='last', inplace=True)
    combined_df.sort_values(by=['Indicator', 'Forecasted Check Date'], inplace=True)
    combined_df.drop(columns='Indicator_norm', inplace=True, errors='ignore')
    try:
        combined_df.to_excel(log_path, index=False)
        print(f" Updated and saved: {log_path}")
    except Exception as e:
        print(f" Failed to save log for {partner_name}: {e}")

with ThreadPoolExecutor() as executor:
    executor.map(process_partner_logs, subfolders)

✅ Daily files successfully parsed by FileDate:
- full_daily_report_20250616 → ['2025-06-16']
- full_daily_report_20250617 → ['2025-06-17']
- full_daily_report_20250618 → ['2025-06-18']
- full_daily_report_20250623 → ['2025-06-23']
- full_daily_report_20250624 → ['2025-06-24']
- full_daily_report_20250625 → ['2025-06-25']
- full_daily_report_20250626 → ['2025-06-26']
- full_daily_report_20250627 → ['2025-06-27']
- full_daily_report_20250630 → ['2025-06-30']
- full_daily_report_20250701 → ['2025-07-01']
- full_daily_report_20250702 → ['2025-07-02']
- full_daily_report_20250703 → ['2025-07-03']
- full_daily_report_20250707 → ['2025-07-07']
- full_daily_report_20250708 → ['2025-07-08']
- full_daily_report_20250709 → ['2025-07-09']
- full_daily_report_20250710 → ['2025-07-10']
- full_daily_report_20250711 → ['2025-07-11']
- full_daily_report_20250714 → ['2025-07-14']
- full_daily_report_20250715 → ['2025-07-15']
- full_daily_report_20250716 → ['2025-07-16']
- full_daily_report_20250717 → ['2025-07-17']
- full_daily_report_20250718 → ['2025-07-18']
- full_daily_report_20250721 → ['2025-07-21']
- full_daily_report_20250722 → ['2025-07-22']
- full_daily_report_20250723 → ['2025-07-23']
- full_daily_report_20250724 → ['2025-07-24']
- full_daily_report_20250725 → ['2025-07-25']
- full_daily_report_20250728 → ['2025-07-28']

🔄 Backing up and cleaning existing forecast logs...
  Backed up CDC → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\CDC_forecast_log_backup_20250728_090652.xlsx
   Deleted original CDC log
  Backed up CMS → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\CMS_forecast_log_backup_20250728_090653.xlsx
   Deleted original CMS log
  Backed up DHA → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\DHA_forecast_log_backup_20250728_090653.xlsx
   Deleted original DHA log
  Backed up FDA → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\FDA_forecast_log_backup_20250728_090653.xlsx
   Deleted original FDA log
  Backed up HHS → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\HHS_forecast_log_backup_20250728_090653.xlsx
   Deleted original HHS log
  Backed up HRSA → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\HRSA_forecast_log_backup_20250728_090653.xlsx
   Deleted original HRSA log
  Backed up IHS → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\IHS_forecast_log_backup_20250728_090653.xlsx
   Deleted original IHS log
  Backed up NIH → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\NIH_forecast_log_backup_20250728_090653.xlsx
   Deleted original NIH log
  Backed up OS → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\OS_forecast_log_backup_20250728_090653.xlsx
   Deleted original OS log
  Backed up VA → Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs_Backup\VA_forecast_log_backup_20250728_090653.xlsx
   Deleted original VA log

============================================================
 Starting fresh data processing with clean normalization...
============================================================

 CDC – Outcome counts:
Outcome
Pending     20864
Not Seen    16297
Seen          498

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
210,104.21.48.1,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.21.48.1
211,104.21.48.1,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.21.48.1
212,104.21.48.1,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.21.48.1
213,104.21.48.1,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.21.48.1
214,104.21.48.1,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.21.48.1
215,104.21.48.1,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.21.48.1
216,104.21.48.1,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.21.48.1
217,104.21.48.1,2025-06-18,30-Day,Highly Likely,2025-07-18,Seen,104.21.48.1
218,104.21.48.1,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.21.48.1
219,104.21.48.1,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,104.21.48.1
220,104.21.48.1,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,104.21.48.1
221,104.21.48.1,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.21.48.1
222,104.21.54.132,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.21.54.132
230,104.21.54.132,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.21.54.132
233,104.21.54.132,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.21.54.132
411,148.153.189.62,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,148.153.189.62
422,148.153.189.62,2025-06-23,7-Day,Possibly Active,2025-06-30,Seen,148.153.189.62
557,156.146.63.133,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,156.146.63.133
583,156.146.63.163,2025-06-18,30-Day,Highly Likely,2025-07-18,Seen,156.146.63.163
782,156.146.63.180,2025-06-16,7-Day,Low Confidence,2025-06-23,Seen,156.146.63.180
831,161.35.53.231,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,161.35.53.231
848,162.142.125.242,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,162.142.125.242
850,162.142.125.242,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,162.142.125.242
851,162.142.125.242,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,162.142.125.242
852,162.142.125.242,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,162.142.125.242
853,162.142.125.242,2025-06-18,30-Day,Highly Likely,2025-07-18,Seen,162.142.125.242
854,162.142.125.242,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,162.142.125.242
855,162.142.125.242,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,162.142.125.242
856,162.142.125.242,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,162.142.125.242
858,162.142.125.247,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,162.142.125.247
863,162.142.125.247,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,162.142.125.247
864,162.142.125.247,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,162.142.125.247
866,162.142.125.247,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,162.142.125.247
867,162.142.125.247,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,162.142.125.247
869,162.142.125.247,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,162.142.125.247
870,162.142.125.255,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,162.142.125.255
871,162.142.125.255,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,162.142.125.255
872,162.142.125.255,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,162.142.125.255
873,162.142.125.255,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,162.142.125.255
876,162.142.125.255,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,162.142.125.255
877,162.142.125.255,2025-06-18,30-Day,Highly Likely,2025-07-18,Seen,162.142.125.255
878,162.142.125.255,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,162.142.125.255
879,162.142.125.255,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,162.142.125.255
880,162.142.125.255,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,162.142.125.255
881,162.142.125.255,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,162.142.125.255
996,172.240.108.68,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,172.240.108.68
997,172.240.108.68,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,172.240.108.68
999,172.240.108.68,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,172.240.108.68
1000,172.240.108.68,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,172.240.108.68
1001,172.240.108.68,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,172.240.108.68

C:\Users\jaskew\AppData\Local\Temp\ipykernel_24668\2759477649.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

 Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\CDC\forecast_log.xlsx

 CMS – Outcome counts:
Outcome
Pending     66563
Not Seen    41588
Seen        15065

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
24,101.89.174.236,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,101.89.174.236
25,101.89.174.236,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,101.89.174.236
26,101.89.174.236,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,101.89.174.236
27,101.89.174.236,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,101.89.174.236
28,101.89.174.236,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,101.89.174.236
29,101.89.174.236,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,101.89.174.236
30,101.89.174.236,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,101.89.174.236
31,101.89.174.236,2025-06-18,30-Day,Highly Likely,2025-07-18,Seen,101.89.174.236
32,101.89.174.236,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,101.89.174.236
33,101.89.174.236,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,101.89.174.236
34,101.89.174.236,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,101.89.174.236
35,101.89.174.236,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,101.89.174.236
108,103.149.86.208,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.149.86.208
109,103.149.86.208,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,103.149.86.208
111,103.149.86.208,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.149.86.208
112,103.149.86.208,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,103.149.86.208
114,103.149.86.208,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.149.86.208
115,103.149.86.208,2025-06-18,30-Day,Highly Likely,2025-07-18,Seen,103.149.86.208
117,103.149.86.208,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,103.149.86.208
118,103.149.86.208,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,103.149.86.208
119,103.149.86.208,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.149.86.208
177,103.203.59.0,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
178,103.203.59.0,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,103.203.59.0
179,103.203.59.0,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,103.203.59.0
180,103.203.59.0,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.203.59.0
181,103.203.59.0,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,103.203.59.0
182,103.203.59.0,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.203.59.0
183,103.203.59.0,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.203.59.0
184,103.203.59.0,2025-06-18,30-Day,Highly Likely,2025-07-18,Seen,103.203.59.0
185,103.203.59.0,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,103.203.59.0
186,103.203.59.0,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,103.203.59.0
187,103.203.59.0,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,103.203.59.0
188,103.203.59.0,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
213,103.61.44.100,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.61.44.100
214,103.61.44.100,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,103.61.44.100
217,103.61.44.100,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,103.61.44.100
219,103.61.44.100,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.61.44.100
220,103.61.44.100,2025-06-18,30-Day,Highly Likely,2025-07-18,Seen,103.61.44.100
222,103.61.44.100,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,103.61.44.100
224,103.61.44.100,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.61.44.100
262,104.152.52.105,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.152.52.105
274,104.152.52.110,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.152.52.110
286,104.152.52.139,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.152.52.139
298,104.152.52.148,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.152.52.148
301,104.152.52.148,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.152.52.148
310,104.152.52.155,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.152.52.155
313,104.152.52.155,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.152.52.155
322,104.152.52.200,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.152.52.200
334,104.152.52.212,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.152.52.212
337,104.152.52.212,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.152.52.212

C:\Users\jaskew\AppData\Local\Temp\ipykernel_24668\2759477649.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

 Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\CMS\forecast_log.xlsx

 DHA – Outcome counts:
Outcome
Pending     55050
Not Seen    35299
Seen         9752

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
29,103.108.229.67,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.108.229.67
30,103.108.229.67,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.108.229.67
41,103.108.231.51,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.108.231.51
42,103.108.231.51,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.108.231.51
53,103.108.231.67,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.108.231.67
54,103.108.231.67,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.108.231.67
77,103.136.147.130,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.136.147.130
78,103.136.147.130,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.136.147.130
89,103.136.147.4,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.136.147.4
90,103.136.147.4,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.136.147.4
108,103.149.86.208,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,103.149.86.208
159,103.203.59.0,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
162,103.203.59.0,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.203.59.0
164,103.203.59.0,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.203.59.0
166,103.203.59.0,2025-06-18,30-Day,Highly Likely,2025-07-18,Seen,103.203.59.0
168,103.203.59.0,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,103.203.59.0
170,103.203.59.0,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
188,103.214.20.131,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.214.20.131
189,103.214.20.131,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.214.20.131
212,103.216.220.19,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,103.216.220.19
213,103.216.220.19,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.216.220.19
224,103.216.220.35,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,103.216.220.35
225,103.216.220.35,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.216.220.35
231,103.61.44.100,2025-06-16,14-Day,Possibly Active,2025-06-30,Seen,103.61.44.100
237,103.61.44.100,2025-06-18,14-Day,Possibly Active,2025-07-02,Seen,103.61.44.100
242,103.61.44.100,2025-06-23,7-Day,Low Confidence,2025-06-30,Seen,103.61.44.100
260,103.75.11.51,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.75.11.51
261,103.75.11.51,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.75.11.51
271,103.75.11.67,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,103.75.11.67
272,103.75.11.67,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.75.11.67
273,103.75.11.67,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.75.11.67
274,103.75.11.67,2025-06-18,30-Day,Highly Likely,2025-07-18,Seen,103.75.11.67
277,103.75.11.67,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,103.75.11.67
305,104.131.6.219,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.131.6.219
315,104.160.6.2,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.160.6.2
317,104.160.6.2,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.160.6.2
318,104.160.6.2,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.160.6.2
319,104.160.6.2,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.160.6.2
320,104.160.6.2,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.160.6.2
321,104.160.6.2,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.160.6.2
323,104.160.6.2,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.160.6.2
324,104.160.6.2,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,104.160.6.2
326,104.160.6.2,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.160.6.2
355,104.234.115.162,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.234.115.162
357,104.234.115.162,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.234.115.162
364,104.234.115.167,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.234.115.167
369,104.234.115.167,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.234.115.167
375,104.234.115.77,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.234.115.77
383,104.234.115.77,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.234.115.77
386,104.234.115.77,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.234.115.77

C:\Users\jaskew\AppData\Local\Temp\ipykernel_24668\2759477649.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

 Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\DHA\forecast_log.xlsx

 FDA – Outcome counts:
Outcome
Pending     51407
Not Seen    29786
Seen        11291

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
24,101.89.174.236,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,101.89.174.236
25,101.89.174.236,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,101.89.174.236
26,101.89.174.236,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,101.89.174.236
27,101.89.174.236,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,101.89.174.236
28,101.89.174.236,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,101.89.174.236
29,101.89.174.236,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,101.89.174.236
30,101.89.174.236,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,101.89.174.236
32,101.89.174.236,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,101.89.174.236
33,101.89.174.236,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,101.89.174.236
34,101.89.174.236,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,101.89.174.236
35,101.89.174.236,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,101.89.174.236
73,103.149.86.208,2025-06-16,30-Day,Possibly Active,2025-07-16,Seen,103.149.86.208
75,103.149.86.208,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,103.149.86.208
78,103.149.86.208,2025-06-18,14-Day,Possibly Active,2025-07-02,Seen,103.149.86.208
81,103.149.86.208,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,103.149.86.208
82,103.149.86.208,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,103.149.86.208
132,103.203.59.0,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
133,103.203.59.0,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,103.203.59.0
134,103.203.59.0,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,103.203.59.0
135,103.203.59.0,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.203.59.0
136,103.203.59.0,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,103.203.59.0
137,103.203.59.0,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.203.59.0
138,103.203.59.0,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.203.59.0
140,103.203.59.0,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,103.203.59.0
141,103.203.59.0,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,103.203.59.0
142,103.203.59.0,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,103.203.59.0
143,103.203.59.0,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
160,103.61.44.100,2025-06-17,30-Day,Possibly Active,2025-07-17,Seen,103.61.44.100
162,103.61.44.100,2025-06-18,14-Day,Possibly Active,2025-07-02,Seen,103.61.44.100
165,103.61.44.100,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,103.61.44.100
341,104.156.155.31,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.156.155.31
344,104.156.155.31,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.156.155.31
376,104.234.115.162,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.234.115.162
385,104.234.115.167,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.234.115.167
401,104.234.115.77,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.234.115.77
409,104.237.131.164,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.237.131.164
411,104.237.131.164,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.237.131.164
412,104.237.131.164,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.237.131.164
413,104.237.131.164,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.237.131.164
414,104.237.131.164,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.237.131.164
421,104.237.151.205,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.237.151.205
422,104.237.151.205,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.151.205
423,104.237.151.205,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.237.151.205
424,104.237.151.205,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.237.151.205
426,104.237.151.205,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.237.151.205
429,104.237.151.205,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,104.237.151.205
430,104.237.151.205,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,104.237.151.205
444,106.54.32.10,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,106.54.32.10
445,106.54.32.10,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,106.54.32.10
446,106.54.32.10,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,106.54.32.10

C:\Users\jaskew\AppData\Local\Temp\ipykernel_24668\2759477649.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

 Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\FDA\forecast_log.xlsx

 HHS – Outcome counts:
Outcome
Pending     17517
Not Seen     8387
Seen          181

 HHS – Outcome counts:
Outcome
Pending     17517
Not Seen     8387
Seen          181

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
24,119.200.13.201,2025-07-02,7-Day,Highly Likely,2025-07-09,Seen,119.200.13.201
34,141.98.11.57,2025-07-02,7-Day,Highly Likely,2025-07-09,Seen,141.98.11.57
124,152.32.128.214,2025-07-02,7-Day,Highly Likely,2025-07-09,Seen,152.32.128.214
152,162.142.125.242,2025-07-02,7-Day,Highly Likely,2025-07-09,Seen,162.142.125.242
153,162.142.125.247,2025-07-02,7-Day,Highly Likely,2025-07-09,Seen,162.142.125.247
154,162.142.125.255,2025-07-02,7-Day,Highly Likely,2025-07-09,Seen,162.142.125.255
157,165.22.54.16,2025-07-02,7-Day,Highly Likely,2025-07-09,Seen,165.22.54.16
208,185.170.144.3,2025-07-02,7-Day,Possibly Active,2025-07-09,Seen,185.170.144.3
354,64.227.146.243,2025-07-02,7-Day,Highly Likely,2025-07-09,Seen,64.227.146.243
387,87.236.176.51,2025-07-02,7-Day,Highly Likely,2025-07-09,Seen,87.236.176.51
395,92.118.39.84,2025-07-02,7-Day,Highly Likely,2025-07-09,Seen,92.118.39.84
435,119.200.13.201,2025-07-02,14-Day,Highly Likely,2025-07-16,Seen,119.200.13.201
445,141.98.11.57,2025-07-02,14-Day,Highly Likely,2025-07-16,Seen,141.98.11.57
535,152.32.128.214,2025-07-02,14-Day,Highly Likely,2025-07-16,Seen,152.32.128.214
563,162.142.125.242,2025-07-02,14-Day,Highly Likely,2025-07-16,Seen,162.142.125.242
564,162.142.125.247,2025-07-02,14-Day,Highly Likely,2025-07-16,Seen,162.142.125.247
565,162.142.125.255,2025-07-02,14-Day,Highly Likely,2025-07-16,Seen,162.142.125.255
568,165.22.54.16,2025-07-02,14-Day,Highly Likely,2025-07-16,Seen,165.22.54.16
765,64.227.146.243,2025-07-02,14-Day,Highly Likely,2025-07-16,Seen,64.227.146.243
1255,118.193.72.187,2025-07-03,7-Day,Highly Likely,2025-07-10,Seen,118.193.72.187
1257,119.200.13.201,2025-07-03,7-Day,Highly Likely,2025-07-10,Seen,119.200.13.201
1267,141.98.11.57,2025-07-03,7-Day,Highly Likely,2025-07-10,Seen,141.98.11.57
1357,152.32.128.214,2025-07-03,7-Day,Highly Likely,2025-07-10,Seen,152.32.128.214
1385,162.142.125.242,2025-07-03,7-Day,Highly Likely,2025-07-10,Seen,162.142.125.242
1386,162.142.125.247,2025-07-03,7-Day,Highly Likely,2025-07-10,Seen,162.142.125.247
1387,162.142.125.255,2025-07-03,7-Day,Highly Likely,2025-07-10,Seen,162.142.125.255
1390,165.22.54.16,2025-07-03,7-Day,Highly Likely,2025-07-10,Seen,165.22.54.16
1578,47.250.57.32,2025-07-03,7-Day,Highly Likely,2025-07-10,Seen,47.250.57.32
1586,64.227.146.243,2025-07-03,7-Day,Highly Likely,2025-07-10,Seen,64.227.146.243
1619,87.236.176.51,2025-07-03,7-Day,Highly Likely,2025-07-10,Seen,87.236.176.51
1667,119.200.13.201,2025-07-03,14-Day,Highly Likely,2025-07-17,Seen,119.200.13.201
1677,141.98.11.57,2025-07-03,14-Day,Highly Likely,2025-07-17,Seen,141.98.11.57
1767,152.32.128.214,2025-07-03,14-Day,Highly Likely,2025-07-17,Seen,152.32.128.214
1795,162.142.125.242,2025-07-03,14-Day,Highly Likely,2025-07-17,Seen,162.142.125.242
1796,162.142.125.247,2025-07-03,14-Day,Highly Likely,2025-07-17,Seen,162.142.125.247
1797,162.142.125.255,2025-07-03,14-Day,Highly Likely,2025-07-17,Seen,162.142.125.255
1800,165.22.54.16,2025-07-03,14-Day,Highly Likely,2025-07-17,Seen,165.22.54.16
1988,47.250.57.32,2025-07-03,14-Day,Highly Likely,2025-07-17,Seen,47.250.57.32
1996,64.227.146.243,2025-07-03,14-Day,Highly Likely,2025-07-17,Seen,64.227.146.243
2029,87.236.176.51,2025-07-03,14-Day,Highly Likely,2025-07-17,Seen,87.236.176.51
2488,119.200.13.201,2025-07-07,7-Day,Highly Likely,2025-07-14,Seen,119.200.13.201
2498,141.98.11.57,2025-07-07,7-Day,Highly Likely,2025-07-14,Seen,141.98.11.57
2588,152.32.128.214,2025-07-07,7-Day,Highly Likely,2025-07-14,Seen,152.32.128.214
2617,162.142.125.242,2025-07-07,7-Day,Highly Likely,2025-07-14,Seen,162.142.125.242
2618,162.142.125.247,2025-07-07,7-Day,Highly Likely,2025-07-14,Seen,162.142.125.247
2619,162.142.125.255,2025-07-07,7-Day,Highly Likely,2025-07-14,Seen,162.142.125.255
2622,165.22.54.16,2025-07-07,7-Day,Highly Likely,2025-07-14,Seen,165.22.54.16
2806,47.250.57.32,2025-07-07,7-Day,Highly Likely,2025-07-14,Seen,47.250.57.32
2810,61.153.184.151,2025-07-07,7-Day,Highly Likely,2025-07-14,Seen,61.153.184.151
2814,64.227.146.243,2025-07-07,7-Day,Highly Likely,2025-07-14,Seen,64.227.146.243

C:\Users\jaskew\AppData\Local\Temp\ipykernel_24668\2759477649.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

 Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\HHS\forecast_log.xlsx

 HRSA – Outcome counts:
Outcome
Pending     32562
Not Seen    31934
Seen          139

 HRSA – Outcome counts:
Outcome
Pending     32562
Not Seen    31934
Seen          139

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
14,101.89.174.236,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,101.89.174.236
119,103.203.59.0,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,103.203.59.0
215,104.152.52.139,2025-06-16,7-Day,Low Confidence,2025-06-23,Seen,104.152.52.139
227,104.152.52.148,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.148
287,104.152.52.237,2025-06-16,7-Day,Possibly Active,2025-06-23,Seen,104.152.52.237
446,104.237.131.164,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.131.164
458,104.237.151.205,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.151.205
500,106.54.32.10,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,106.54.32.10
521,107.174.224.18,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,107.174.224.18
674,115.190.15.27,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,115.190.15.27
791,119.96.59.16,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,119.96.59.16
836,121.196.237.27,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,121.196.237.27
893,124.156.231.182,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,124.156.231.182
908,124.205.213.108,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,124.205.213.108
920,124.239.153.90,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,124.239.153.90
1121,14.103.172.199,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,14.103.172.199
1217,142.93.115.5,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,142.93.115.5
1367,148.113.206.49,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,148.113.206.49
1391,148.153.189.62,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,148.153.189.62
1403,149.102.229.181,2025-06-16,7-Day,Low Confidence,2025-06-23,Seen,149.102.229.181
1463,152.32.128.214,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,152.32.128.214
1550,157.245.227.101,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,157.245.227.101
1721,165.154.135.215,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,165.154.135.215
1838,167.99.13.19,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,167.99.13.19
1898,169.150.223.208,2025-06-16,7-Day,Low Confidence,2025-06-23,Seen,169.150.223.208
2171,176.65.148.234,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,176.65.148.234
2183,176.65.148.236,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,176.65.148.236
2195,176.65.148.250,2025-06-16,7-Day,Possibly Active,2025-06-23,Seen,176.65.148.250
2252,178.128.84.112,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,178.128.84.112
2324,18.117.57.162,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,18.117.57.162
2348,18.221.137.47,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,18.221.137.47
2360,18.223.104.85,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,18.223.104.85
2420,183.224.237.233,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,183.224.237.233
2450,185.12.59.118,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,185.12.59.118
2504,185.129.62.63,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,185.129.62.63
2540,185.169.4.150,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,185.169.4.150
2741,185.241.208.204,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,185.241.208.204
2825,188.166.106.38,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,188.166.106.38
2909,192.155.84.28,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,192.155.84.28
3152,193.163.125.103,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.103
3164,193.163.125.107,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.107
3176,193.163.125.108,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.108
3188,193.163.125.109,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.109
3200,193.163.125.115,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.115
3212,193.163.125.117,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.117
3224,193.163.125.121,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.121
3236,193.163.125.127,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.127
3248,193.163.125.132,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.132
3260,193.163.125.143,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.143
3272,193.163.125.149,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,193.163.125.149

C:\Users\jaskew\AppData\Local\Temp\ipykernel_24668\2759477649.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

 Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\HRSA\forecast_log.xlsx

 IHS – Outcome counts:
Outcome
Pending     45393
Not Seen    27192
Seen         8808

 IHS – Outcome counts:
Outcome
Pending     45393
Not Seen    27192
Seen         8808

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
36,103.203.59.0,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
37,103.203.59.0,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,103.203.59.0
38,103.203.59.0,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,103.203.59.0
39,103.203.59.0,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.203.59.0
40,103.203.59.0,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,103.203.59.0
41,103.203.59.0,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.203.59.0
44,103.203.59.0,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,103.203.59.0
46,103.203.59.0,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,103.203.59.0
47,103.203.59.0,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
192,104.192.3.74,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.192.3.74
195,104.192.3.74,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.192.3.74
196,104.192.3.74,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.192.3.74
200,104.192.3.74,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.192.3.74
201,104.192.3.74,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,104.192.3.74
203,104.192.3.74,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.192.3.74
207,104.21.20.66,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,104.21.20.66
228,104.234.115.162,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.234.115.162
233,104.234.115.162,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.234.115.162
234,104.234.115.162,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.234.115.162
239,104.234.115.162,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.234.115.162
245,104.234.115.167,2025-06-17,7-Day,Low Confidence,2025-06-24,Seen,104.234.115.167
248,104.234.115.167,2025-06-18,7-Day,Low Confidence,2025-06-25,Seen,104.234.115.167
249,104.234.115.167,2025-06-23,14-Day,Possibly Active,2025-07-07,Seen,104.234.115.167
250,104.234.115.167,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,104.234.115.167
255,104.234.115.77,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.234.115.77
265,104.237.131.164,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.237.131.164
266,104.237.131.164,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.131.164
267,104.237.131.164,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.237.131.164
268,104.237.131.164,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.237.131.164
269,104.237.131.164,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.237.131.164
270,104.237.131.164,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.237.131.164
272,104.237.131.164,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.237.131.164
274,104.237.131.164,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,104.237.131.164
276,104.237.151.205,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.237.151.205
277,104.237.151.205,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.237.151.205
278,104.237.151.205,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.151.205
279,104.237.151.205,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.237.151.205
280,104.237.151.205,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.237.151.205
281,104.237.151.205,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.237.151.205
282,104.237.151.205,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.237.151.205
285,104.237.151.205,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,104.237.151.205
286,104.237.151.205,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,104.237.151.205
287,104.237.151.205,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.237.151.205
288,104.244.73.193,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,104.244.73.193
290,104.244.73.193,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.244.73.193
291,104.244.79.50,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.244.79.50
294,104.244.79.50,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.244.79.50
299,104.244.79.50,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.244.79.50
300,104.244.79.50,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,104.244.79.50
302,104.244.79.50,2025-06-23,7-Day,Possibly Active,2025-06-30,Seen,104.244.79.50

C:\Users\jaskew\AppData\Local\Temp\ipykernel_24668\2759477649.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

 Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\IHS\forecast_log.xlsx

 NIH – Outcome counts:
Outcome
Pending     65729
Not Seen    58485
Seen         2818

 NIH – Outcome counts:
Outcome
Pending     65729
Not Seen    58485
Seen         2818

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
192,103.203.59.0,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
193,103.203.59.0,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,103.203.59.0
194,103.203.59.0,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,103.203.59.0
200,103.203.59.0,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,103.203.59.0
201,103.203.59.0,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,103.203.59.0
202,103.203.59.0,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,103.203.59.0
203,103.203.59.0,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
285,103.53.40.64,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,103.53.40.64
426,104.18.32.191,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.18.32.191
427,104.18.32.191,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.18.32.191
429,104.18.32.191,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.18.32.191
431,104.18.32.191,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.18.32.191
436,104.18.32.191,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,104.18.32.191
437,104.18.32.191,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,104.18.32.191
536,104.21.3.76,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.21.3.76
538,104.21.3.76,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.21.3.76
539,104.21.3.76,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.21.3.76
542,104.21.3.76,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.21.3.76
543,104.21.3.76,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,104.21.3.76
756,104.234.115.162,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.234.115.162
765,104.234.115.167,2025-06-17,14-Day,Low Confidence,2025-07-01,Seen,104.234.115.167
772,104.234.115.167,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,104.234.115.167
783,104.234.115.77,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,104.234.115.77
917,107.174.224.18,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,107.174.224.18
1671,148.113.206.49,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,148.113.206.49
1672,148.113.206.49,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,148.113.206.49
1673,148.113.206.49,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,148.113.206.49
1674,148.113.206.49,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,148.113.206.49
1675,148.113.206.49,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,148.113.206.49
1676,148.113.206.49,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,148.113.206.49
1677,148.113.206.49,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,148.113.206.49
1679,148.113.206.49,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,148.113.206.49
1680,148.113.206.49,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,148.113.206.49
1681,148.113.206.49,2025-06-23,30-Day,Highly Likely,2025-07-23,Seen,148.113.206.49
1682,148.113.206.49,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,148.113.206.49
1794,15.156.234.60,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,15.156.234.60
1797,15.156.234.60,2025-06-18,14-Day,Possibly Active,2025-07-02,Seen,15.156.234.60
1799,15.156.234.60,2025-06-18,7-Day,Low Confidence,2025-06-25,Seen,15.156.234.60
1800,15.156.234.60,2025-06-23,14-Day,Possibly Active,2025-07-07,Seen,15.156.234.60
2313,159.203.44.105,2025-06-23,14-Day,Possibly Active,2025-07-07,Seen,159.203.44.105
2321,159.203.98.153,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,159.203.98.153
2469,161.35.53.231,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,161.35.53.231
2471,161.35.53.231,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,161.35.53.231
2472,161.35.53.231,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,161.35.53.231
2474,161.35.53.231,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,161.35.53.231
2475,161.35.53.231,2025-06-23,14-Day,Highly Likely,2025-07-07,Seen,161.35.53.231
2477,161.35.53.231,2025-06-23,7-Day,Highly Likely,2025-06-30,Seen,161.35.53.231
2490,162.142.125.242,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,162.142.125.242
2491,162.142.125.242,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,162.142.125.242
2492,162.142.125.242,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,162.142.125.242

C:\Users\jaskew\AppData\Local\Temp\ipykernel_24668\2759477649.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

 Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\NIH\forecast_log.xlsx

 OS – Outcome counts:
Outcome
Pending     47068
Not Seen    30415
Seen         7060

 OS – Outcome counts:
Outcome
Pending     47068
Not Seen    30415
Seen         7060

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
12,101.89.174.236,2025-06-17,14-Day,Possibly Active,2025-07-01,Seen,101.89.174.236
117,103.203.59.0,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.203.59.0
118,103.203.59.0,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,103.203.59.0
119,103.203.59.0,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,103.203.59.0
120,103.203.59.0,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.203.59.0
121,103.203.59.0,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,103.203.59.0
122,103.203.59.0,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,103.203.59.0
123,103.203.59.0,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,103.203.59.0
125,103.203.59.0,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,103.203.59.0
189,104.152.52.110,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.110
198,104.152.52.139,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.139
203,104.152.52.139,2025-06-18,7-Day,Possibly Active,2025-06-25,Seen,104.152.52.139
235,104.152.52.216,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.152.52.216
242,104.152.52.225,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.225
279,104.152.52.242,2025-06-17,14-Day,Low Confidence,2025-07-01,Seen,104.152.52.242
295,104.156.155.31,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.156.155.31
298,104.156.155.31,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.156.155.31
305,104.156.155.35,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.156.155.35
306,104.156.155.35,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.156.155.35
331,104.234.115.162,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.234.115.162
340,104.237.131.164,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.237.131.164
341,104.237.131.164,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.131.164
343,104.237.131.164,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.237.131.164
349,104.237.151.205,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.237.151.205
350,104.237.151.205,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.237.151.205
351,104.237.151.205,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.237.151.205
352,104.237.151.205,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.237.151.205
353,104.237.151.205,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.237.151.205
354,104.237.151.205,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.237.151.205
366,106.54.32.10,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,106.54.32.10
372,106.54.32.10,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,106.54.32.10
374,106.54.32.10,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,106.54.32.10
384,107.174.224.18,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,107.174.224.18
385,107.174.224.18,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,107.174.224.18
387,107.174.224.18,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,107.174.224.18
389,107.174.224.18,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,107.174.224.18
390,107.174.224.18,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,107.174.224.18
392,107.174.224.18,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,107.174.224.18
405,107.189.30.69,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,107.189.30.69
416,109.70.100.5,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,109.70.100.5
417,109.70.100.5,2025-06-18,14-Day,Possibly Active,2025-07-02,Seen,109.70.100.5
422,109.70.100.6,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,109.70.100.6
423,109.70.100.6,2025-06-18,14-Day,Possibly Active,2025-07-02,Seen,109.70.100.6
491,118.193.59.10,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,118.193.59.10
494,118.193.59.10,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,118.193.59.10
495,118.193.59.10,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,118.193.59.10
500,118.193.72.187,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,118.193.72.187
511,118.26.111.94,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,118.26.111.94
512,118.26.111.94,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,118.26.111.94
544,120.48.45.123,2025-06-17,30-Day,Possibly Active,2025-07-17,Seen,120.48.45.123

C:\Users\jaskew\AppData\Local\Temp\ipykernel_24668\2759477649.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

 Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\OS\forecast_log.xlsx

 VA – Outcome counts:
Outcome
Pending     60145
Not Seen    34180
Seen        12088

 VA – Outcome counts:
Outcome
Pending     60145
Not Seen    34180
Seen        12088

,Indicator,Forecast Date,Forecast Type,Confidence,Forecasted Check Date,Outcome,Indicator_norm
69,103.149.86.208,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.149.86.208
70,103.149.86.208,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,103.149.86.208
72,103.149.86.208,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.149.86.208
73,103.149.86.208,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,103.149.86.208
122,103.191.76.181,2025-06-17,7-Day,Possibly Active,2025-06-24,Seen,103.191.76.181
125,103.191.76.181,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,103.191.76.181
174,103.61.44.100,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,103.61.44.100
175,103.61.44.100,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,103.61.44.100
177,103.61.44.100,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,103.61.44.100
178,103.61.44.100,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,103.61.44.100
208,104.128.161.233,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.128.161.233
210,104.128.161.233,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.128.161.233
215,104.128.161.233,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.128.161.233
225,104.152.52.105,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.152.52.105
226,104.152.52.105,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.152.52.105
227,104.152.52.105,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.105
228,104.152.52.105,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.105
229,104.152.52.105,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.152.52.105
230,104.152.52.105,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.152.52.105
233,104.152.52.105,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.105
234,104.152.52.110,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.152.52.110
235,104.152.52.110,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.152.52.110
236,104.152.52.110,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.110
237,104.152.52.110,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.110
238,104.152.52.110,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.152.52.110
239,104.152.52.110,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.152.52.110
240,104.152.52.110,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.152.52.110
242,104.152.52.110,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.110
244,104.152.52.139,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.152.52.139
245,104.152.52.139,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.139
246,104.152.52.139,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.139
247,104.152.52.139,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.152.52.139
248,104.152.52.139,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.152.52.139
251,104.152.52.139,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.139
252,104.152.52.148,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.152.52.148
253,104.152.52.148,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.152.52.148
254,104.152.52.148,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.148
255,104.152.52.148,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.148
256,104.152.52.148,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.152.52.148
257,104.152.52.148,2025-06-17,7-Day,Highly Likely,2025-06-24,Seen,104.152.52.148
258,104.152.52.148,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.152.52.148
260,104.152.52.148,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.148
261,104.152.52.155,2025-06-16,14-Day,Highly Likely,2025-06-30,Seen,104.152.52.155
262,104.152.52.155,2025-06-16,30-Day,Highly Likely,2025-07-16,Seen,104.152.52.155
263,104.152.52.155,2025-06-16,7-Day,Highly Likely,2025-06-23,Seen,104.152.52.155
264,104.152.52.155,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.155
265,104.152.52.155,2025-06-17,30-Day,Highly Likely,2025-07-17,Seen,104.152.52.155
267,104.152.52.155,2025-06-18,14-Day,Highly Likely,2025-07-02,Seen,104.152.52.155
269,104.152.52.155,2025-06-18,7-Day,Highly Likely,2025-06-25,Seen,104.152.52.155
273,104.152.52.212,2025-06-17,14-Day,Highly Likely,2025-07-01,Seen,104.152.52.212

C:\Users\jaskew\AppData\Local\Temp\ipykernel_24668\2759477649.py:163: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([existing_df, log_df], ignore_index=True)

 Updated and saved: Z:\HTOC\Data_Analytics\Data\OpDiv_Predictions\Logs\VA\forecast_log.xlsx