In [1]:
import pandas as pd

# Load the Excel file
file_path = r"Z:\HTOC\Data_Analytics\Data\Threat Assessment Scores\Threat_Assessment_Scores.xlsx"
df = pd.read_excel(file_path)

# Display the first few rows
df

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
0,1.234.83.26,2026-02-14,Address,43,3,0.997644,0,0,NaN,NaN,NaN,180,469,134,low,[2026-03-16] Severity: low. VT score: 3. Top d...
1,101.168.57.163,2026-02-14,Address,2,3,0.999890,0,0,NaN,Incident:INC9407577,NaN,180,590,389,medium,[2026-03-16] Severity: medium. VT score: 11. T...
2,101.71.130.99,2026-03-03,Address,139,3,0.992384,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",Incident:INC9270850,NaN,180,346,464,medium,[2026-03-16] Severity: medium. VT score: 11. T...
3,103.114.96.246,2026-02-26,Address,41,1,0.997753,1,0,"CMS, DHA, NIH, OS, VA",NaN,Mr Hamza Group,170,224,130,low,[2026-03-16] Severity: low. VT score: 1. Top d...
4,103.120.116.162,2026-03-16,Address,48,3,0.997370,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9385644,NaN,740,870,364,medium,[2026-03-16] Severity: medium. VT score: 6. To...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2291,198.199.103.243,2026-01-16,Address,1,0,0.999945,1,0,VA,Incident:6755399478001848,NaN,180,368,41,low,Severity: low. VT score: 0. Top drivers: Incid...
2292,w-2@doculivery.com,2026-03-04,EmailAddress,2,4,0.999890,1,0,HHS,Incident:547380,NaN,170,224,29,low,[2026-03-06] Severity: low. VT score not avail...
2293,link.edgepilot.com,2026-03-05,Host,74,1,0.995945,0,0,"CMS, NIH",NaN,NaN,180,229,28,low,[2026-03-06] Severity: low. VT score not avail...
2294,52.87.206.242,2026-01-08,Address,1,1,0.999945,1,0,IHS,NaN,NaN,170,224,27,low,Severity: low. VT score: 0. Top drivers: TC ra...
2295,86.38.243.1,2026-02-04,Address,8,4,0.999562,0,0,"NIH, VA",NaN,NaN,170,363,23,low,[2026-03-06] Severity: low. VT score: 0. Top d...

In [2]:
import pandas as pd

# Ensure Last Observed is datetime
df['Last Observed'] = pd.to_datetime(df['Last Observed'])

# Get last 24 hours relative to latest observation
max_obs = df['Last Observed'].max()
cutoff = max_obs - pd.Timedelta(days=1)
last_24h_from_max = df[df['Last Observed'] >= cutoff]

last_24h_from_max

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
4,103.120.116.162,2026-03-16,Address,48,3,0.997370,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9385644,NaN,740,870,364,medium,[2026-03-16] Severity: medium. VT score: 6. To...
6,103.140.62.43,2026-03-15,Address,12,5,0.999342,0,0,"DHA, VA",NaN,NaN,180,590,145,low,[2026-03-16] Severity: low. VT score: 3. Top d...
7,103.143.10.79,2026-03-16,Address,17,3,0.999068,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,770,764,673,high,[2026-03-16] Severity: high. VT score: 17. Top...
9,103.203.59.0,2026-03-16,Address,282,3,0.984548,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",NaN,NaN,180,368,90,low,[2026-03-16] Severity: low. VT score: 1. Top d...
13,103.243.26.49,2026-03-16,Address,55,3,0.996986,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9375302,NaN,180,469,351,medium,[2026-03-16] Severity: medium. VT score: 6. To...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1361,120.71.10.48,2026-03-16,Address,2,5,0.999890,1,0,IHS,NaN,NaN,180,469,35,low,[2026-03-16] Severity: low. VT score: 1. Top d...
1363,134.122.44.7,2026-03-16,Address,2,3,0.999890,0,0,"CMS, FDA, HRSA, IHS, OS, VA",Incident:INC9411178,NaN,180,590,410,medium,[2026-03-16] Severity: medium. VT score: 8. To...
1366,170.64.230.230,2026-03-16,Address,2,3,0.999890,0,0,"CMS, FDA, HRSA, OS, VA",Incident:INC9426249,NaN,180,590,199,low,[2026-03-16] Severity: low. VT score: 1. Top d...
1367,180.167.128.202,2026-03-16,Address,5,3,0.999726,0,0,"CDC, CMS, DHA, FDA, HRSA, IHS, NIH, OS",Incident:INC9444954,NaN,180,590,337,medium,[2026-03-16] Severity: medium. VT score: 5. To...
1368,link.storjshare.io,2026-03-16,Host,4,4,0.999781,0,0,"IHS, NIH",NaN,Banished Kitten,180,469,161,low,[2026-03-16] Severity: low. VT score not avail...

In [3]:
# Filter last 24h results to indicators seen at more than one partner
last_24h_multiple_partners = last_24h_from_max[last_24h_from_max['Partners'].str.contains(',', na=False)]

last_24h_multiple_partners

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
4,103.120.116.162,2026-03-16,Address,48,3,0.997370,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9385644,NaN,740,870,364,medium,[2026-03-16] Severity: medium. VT score: 6. To...
6,103.140.62.43,2026-03-15,Address,12,5,0.999342,0,0,"DHA, VA",NaN,NaN,180,590,145,low,[2026-03-16] Severity: low. VT score: 3. Top d...
7,103.143.10.79,2026-03-16,Address,17,3,0.999068,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,770,764,673,high,[2026-03-16] Severity: high. VT score: 17. Top...
9,103.203.59.0,2026-03-16,Address,282,3,0.984548,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",NaN,NaN,180,368,90,low,[2026-03-16] Severity: low. VT score: 1. Top d...
13,103.243.26.49,2026-03-16,Address,55,3,0.996986,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9375302,NaN,180,469,351,medium,[2026-03-16] Severity: medium. VT score: 6. To...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1356,www.deepseek.com,2026-03-16,Host,346,3,0.981041,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,469,50,low,[2026-03-16] Severity: low. VT score not avail...
1363,134.122.44.7,2026-03-16,Address,2,3,0.999890,0,0,"CMS, FDA, HRSA, IHS, OS, VA",Incident:INC9411178,NaN,180,590,410,medium,[2026-03-16] Severity: medium. VT score: 8. To...
1366,170.64.230.230,2026-03-16,Address,2,3,0.999890,0,0,"CMS, FDA, HRSA, OS, VA",Incident:INC9426249,NaN,180,590,199,low,[2026-03-16] Severity: low. VT score: 1. Top d...
1367,180.167.128.202,2026-03-16,Address,5,3,0.999726,0,0,"CDC, CMS, DHA, FDA, HRSA, IHS, NIH, OS",Incident:INC9444954,NaN,180,590,337,medium,[2026-03-16] Severity: medium. VT score: 5. To...
1368,link.storjshare.io,2026-03-16,Host,4,4,0.999781,0,0,"IHS, NIH",NaN,Banished Kitten,180,469,161,low,[2026-03-16] Severity: low. VT score not avail...

In [4]:
# Filter multi-partner, last-24h indicators to VT score >= 10 based on Explanation text
vt_scores = last_24h_multiple_partners['Explanation'].str.extract(r'VT score:\s*(\d+)', expand=False)
vt_scores = pd.to_numeric(vt_scores, errors='coerce')

last_24h_multi_partners_vt10 = last_24h_multiple_partners[vt_scores >= 10]

last_24h_multi_partners_vt10

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
7,103.143.10.79,2026-03-16,Address,17,3,0.999068,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,770,764,673,high,[2026-03-16] Severity: high. VT score: 17. Top...
19,104.152.52.139,2026-03-15,Address,226,3,0.987616,0,0,"CMS, FDA, HHS, HRSA, NIH, OS, VA",NaN,NaN,390,473,422,medium,[2026-03-16] Severity: medium. VT score: 11. T...
20,104.152.52.216,2026-03-15,Address,223,3,0.987781,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,368,499,medium,[2026-03-16] Severity: medium. VT score: 13. T...
22,104.152.52.237,2026-03-15,Address,222,3,0.987836,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,368,499,medium,[2026-03-16] Severity: medium. VT score: 13. T...
23,104.152.52.239,2026-03-15,Address,222,3,0.987836,0,0,"CMS, FDA, HHS, HRSA, NIH, OS, VA",NaN,NaN,320,438,499,medium,[2026-03-16] Severity: medium. VT score: 14. T...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1243,87.236.176.93,2026-03-15,Address,268,3,0.985315,0,0,"DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,410,483,499,medium,[2026-03-16] Severity: medium. VT score: 15. T...
1267,91.224.92.99,2026-03-15,Address,105,3,0.994247,0,0,"CMS, DHA, FDA, HHS, HRSA, NIH, OS, VA",NaN,NaN,710,591,499,medium,[2026-03-16] Severity: medium. VT score: 14. T...
1270,92.118.39.95,2026-03-16,Address,109,3,0.994027,0,0,"CDC, CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9310331,NaN,820,736,523,high,[2026-03-16] Severity: high. VT score: 13. Top...
1278,93.123.109.245,2026-03-15,Address,23,3,0.998740,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,469,342,medium,[2026-03-16] Severity: medium. VT score: 10. T...
1284,94.16.115.121,2026-03-15,Address,201,3,0.988986,0,0,"CMS, FDA, HHS, HRSA, IHS, OS, VA",NaN,NaN,220,517,499,medium,[2026-03-16] Severity: medium. VT score: 13. T...

In [5]:
# Keep only high or critical indicators from the VT>=10, multi-partner, last-24h set
high_critical_last_24h = last_24h_multi_partners_vt10[last_24h_multi_partners_vt10['Severity'].isin(['high', 'critical'])]

high_critical_last_24h

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
7,103.143.10.79,2026-03-16,Address,17,3,0.999068,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,770,764,673,high,[2026-03-16] Severity: high. VT score: 17. Top...
43,109.70.100.1,2026-03-15,Address,202,3,0.988932,0,0,"CMS, FDA, HHS, HRSA, IHS, OS, VA",NaN,NaN,230,393,552,high,[2026-03-16] Severity: high. VT score: 12. Top...
44,109.70.100.2,2026-03-15,Address,206,3,0.988712,0,0,"CMS, FDA, HHS, HRSA, IHS, OS, VA",NaN,NaN,200,479,572,high,[2026-03-16] Severity: high. VT score: 13. Top...
45,109.70.100.5,2026-03-15,Address,217,3,0.988110,0,0,"CMS, FDA, HHS, HRSA, IHS, OS, VA",NaN,NaN,220,388,551,high,[2026-03-16] Severity: high. VT score: 12. Top...
46,109.70.100.6,2026-03-15,Address,212,3,0.988384,0,0,"CMS, FDA, HHS, HRSA, IHS, OS, VA",NaN,NaN,220,411,572,high,[2026-03-16] Severity: high. VT score: 13. Top...
51,112.31.180.128,2026-03-16,Address,15,3,0.999178,0,0,"CMS, FDA, HRSA, NIH, OS",Incident:6755399484001244,NaN,180,399,523,high,[2026-03-16] Severity: high. VT score: 14. Top...
60,121.159.71.249,2026-03-16,Address,182,3,0.990027,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9223440,NaN,670,661,538,high,[2026-03-16] Severity: high. VT score: 14. Top...
64,123.58.196.49,2026-03-16,Address,221,3,0.987890,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9176144,NaN,390,444,531,high,[2026-03-16] Severity: high. VT score: 12. Top...
65,123.58.207.81,2026-03-16,Address,215,3,0.988219,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9185304,NaN,380,439,619,high,[2026-03-16] Severity: high. VT score: 15. Top...
66,123.58.209.112,2026-03-16,Address,270,3,0.985205,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9102471,NaN,290,367,506,high,[2026-03-16] Severity: high. VT score: 11. Top...
93,138.59.233.5,2026-03-16,Address,71,3,0.996110,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9346798,NaN,540,600,626,high,[2026-03-16] Severity: high. VT score: 15. Top...
95,139.19.117.131,2026-03-16,Address,159,3,0.991288,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9267413,NaN,790,721,650,high,[2026-03-16] Severity: high. VT score: 16. Top...
106,141.98.11.82,2026-03-15,Address,36,3,0.998027,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,720,596,501,high,[2026-03-16] Severity: high. VT score: 14. Top...
200,165.154.10.165,2026-03-16,Address,206,3,0.988712,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9203759,NaN,390,444,571,high,[2026-03-16] Severity: high. VT score: 14. Top...
201,165.154.173.226,2026-03-16,Address,180,3,0.990137,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9235915,NaN,380,439,602,high,[2026-03-16] Severity: high. VT score: 14. Top...
202,165.154.179.204,2026-03-15,Address,259,3,0.985808,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",Incident:INC9118016,NaN,620,532,582,high,[2026-03-16] Severity: high. VT score: 13. Top...
216,167.94.138.124,2026-03-16,Address,120,3,0.993425,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,700,693,536,high,[2026-03-16] Severity: high. VT score: 16. Top...
261,171.25.193.235,2026-03-15,Address,218,5,0.988055,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,"Fancy Bear, Seashell Blizzard, UNC4487",210,356,578,high,[2026-03-16] Severity: high. VT score: 16. Top...
280,176.65.134.22,2026-03-16,Address,55,3,0.996986,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9375302,NaN,730,744,727,high,[2026-03-16] Severity: high. VT score: 20. Top...
286,176.65.148.52,2026-03-15,Address,32,3,0.998247,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,387,524,high,[2026-03-16] Severity: high. VT score: 19. Top...
317,183.224.237.233,2026-03-16,Address,176,3,0.990356,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS",Incident:547382,NaN,780,699,583,high,[2026-03-16] Severity: high. VT score: 14. Top...
318,184.105.247.252,2026-03-16,Address,91,3,0.995014,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9332624,NaN,290,471,551,high,[2026-03-16] Severity: high. VT score: 15. Top...
328,185.156.73.233,2026-03-16,Address,13,3,0.999288,0,0,"NIH, OS",Incident:INC9373125;Incident:INC9373119,NaN,570,664,539,high,[2026-03-16] Severity: high. VT score: 15. Top...
344,185.220.101.184,2026-03-15,Address,35,3,0.998082,0,0,"CDC, CMS, FDA, HHS, HRSA, OS, VA",NaN,NaN,200,443,668,high,[2026-03-16] Severity: high. VT score: 14. Top...
345,185.220.101.21,2026-03-15,Address,149,2,0.991836,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:102309,NaN,370,511,711,high,[2026-03-16] Severity: high. VT score: 14. Top...
483,193.32.162.145,2026-03-16,Address,153,3,0.991616,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9263763,NaN,810,784,583,high,[2026-03-16] Severity: high. VT score: 16. Top...
532,198.235.24.186,2026-03-16,Address,88,3,0.995178,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9341092,NaN,580,616,606,high,[2026-03-16] Severity: high. VT score: 14. Top...
533,198.235.24.193,2026-03-16,Address,90,3,0.995068,0,0,"CDC, CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9337221,NaN,180,326,536,high,[2026-03-16] Severity: high. VT score: 11. Top...
534,198.235.24.194,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,288,504,high,[2026-03-16] Severity: high. VT score: 15. Top...
574,198.235.24.68,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,510,453,511,high,[2026-03-16] Severity: high. VT score: 15. Top...
610,2.57.121.112,2026-03-16,Address,96,3,0.994740,0,0,"OS, VA",Incident:INC9307742,NaN,700,693,628,high,[2026-03-16] Severity: high. VT score: 16. Top...
612,2.57.121.25,2026-03-16,Address,100,3,0.994521,0,0,"OS, VA",Incident:INC9307742,NaN,710,698,628,high,[2026-03-16] Severity: high. VT score: 16. Top...
629,205.210.31.106,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9388679,NaN,180,368,512,high,[2026-03-16] Severity: high. VT score: 10. Top...
638,205.210.31.163,2026-03-16,Address,62,3,0.996603,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9366814,NaN,240,398,599,high,[2026-03-16] Severity: high. VT score: 14. Top...
658,205.210.31.209,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,288,504,high,[2026-03-16] Severity: high. VT score: 15. Top...
666,205.210.31.230,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,368,505,high,[2026-03-16] Severity: high. VT score: 15. Top...
692,205.210.31.66,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,312,504,high,[2026-03-16] Severity: high. VT score: 15. Top...
699,205.210.31.79,2026-03-16,Address,67,3,0.996329,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,368,506,high,[2026-03-16] Severity: high. VT score: 15. Top...
749,207.90.244.13,2026-03-16,Address,90,3,0.995068,0,0,"FDA, HRSA, OS, VA",Incident:INC9337221,NaN,640,598,597,high,[2026-03-16] Severity: high. VT score: 14. Top...
750,207.90.244.3,2026-03-16,Address,62,3,0.996603,0,0,"FDA, HRSA, NIH, OS, VA",Incident:INC9366814,NaN,700,611,582,high,[2026-03-16] Severity: high. VT score: 13. Top...
762,213.209.159.158,2026-03-16,Address,24,3,0.998685,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9411178,NaN,820,789,693,high,[2026-03-16] Severity: high. VT score: 18. Top...
779,23.106.248.251,2026-03-15,Address,181,5,0.990082,0,0,"CDC, CMS, DHA, FDA, HHS, IHS, NIH, OS, VA",NaN,Scattered Spider,180,590,638,high,[2026-03-16] Severity: high. VT score: 10. Top...
810,37.221.208.71,2026-03-15,Address,130,3,0.992877,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,190,474,512,high,[2026-03-16] Severity: high. VT score: 10. Top...
828,45.132.227.213,2026-03-15,Address,115,5,0.993699,0,0,"CMS, DHA, FDA, HHS, HRSA, OS, VA",NaN,Scattered Spider,180,469,720,high,[2026-03-16] Severity: high. VT score: 10. Top...
848,45.148.10.141,2026-03-16,Address,55,4,0.996986,0,0,"HHS, OS",NaN,"Crimson Collective, Scattered Spider, UNC6395",690,671,820,critical,[2026-03-16] Severity: critical. VT score: 15....
851,45.153.34.87,2026-03-16,Address,34,3,0.998137,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9366814,NaN,180,590,571,high,[2026-03-16] Severity: high. VT score: 16. Top...
870,46.161.27.151,2026-03-15,Address,2,4,0.999890,0,0,"CMS, HHS",NaN,ShadowSyndicate,860,708,675,high,[2026-03-16] Severity: high. VT score: 17. Top...
903,64.225.74.178,2026-03-16,Address,43,3,0.997644,0,0,"FDA, HRSA, NIH, OS, VA",Incident:INC9391086,NaN,410,584,597,high,[2026-03-16] Severity: high. VT score: 14. Top...
1179,65.49.1.92,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,416,505,high,[2026-03-16] Severity: high. VT score: 15. Top...
1185,65.49.1.99,2026-03-16,Address,265,3,0.985479,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,416,504,high,[2026-03-16] Severity: high. VT score: 15. Top...
1199,71.6.232.23,2026-03-16,Address,60,3,0.996712,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9332642,NaN,230,458,537,high,[2026-03-16] Severity: high. VT score: 11. Top...
1207,78.128.114.130,2026-03-16,Address,89,3,0.995123,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9332642,NaN,490,588,520,high,[2026-03-16] Severity: high. VT score: 10. Top...
1222,80.94.92.171,2026-03-16,Address,109,3,0.994027,0,0,"CDC, CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9303503,NaN,820,789,603,high,[2026-03-16] Severity: high. VT score: 17. Top...
1229,85.93.218.204,2026-03-15,Address,38,5,0.997918,0,0,"CMS, FDA, HHS, HRSA, IHS, OS, VA",NaN,FIN4,200,600,684,high,[2026-03-16] Severity: high. VT score: 12. Top...
1270,92.118.39.95,2026-03-16,Address,109,3,0.994027,0,0,"CDC, CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9310331,NaN,820,736,523,high,[2026-03-16] Severity: high. VT score: 13. Top...

In [6]:
high_critical_last_24h[high_critical_last_24h['Indicator'] == '45.148.10.141']

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
848,45.148.10.141,2026-03-16,Address,55,4,0.996986,0,0,"HHS, OS",NaN,"Crimson Collective, Scattered Spider, UNC6395",690,671,820,critical,[2026-03-16] Severity: critical. VT score: 15....

In [7]:
# Extract VT scores for high/critical last-24h indicators
vt_scores_hc = high_critical_last_24h['Explanation'].str.extract(r'VT score:\s*(\d+)', expand=False)

# VT-based selection only: keep high/critical last-24h indicators with VT score > 15
vt = pd.to_numeric(vt_scores_hc, errors='coerce')
mask_vt = vt >= 15

final_indicators = high_critical_last_24h[mask_vt]
final_indicators

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
7,103.143.10.79,2026-03-16,Address,17,3,0.999068,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,770,764,673,high,[2026-03-16] Severity: high. VT score: 17. Top...
65,123.58.207.81,2026-03-16,Address,215,3,0.988219,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9185304,NaN,380,439,619,high,[2026-03-16] Severity: high. VT score: 15. Top...
93,138.59.233.5,2026-03-16,Address,71,3,0.996110,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9346798,NaN,540,600,626,high,[2026-03-16] Severity: high. VT score: 15. Top...
95,139.19.117.131,2026-03-16,Address,159,3,0.991288,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9267413,NaN,790,721,650,high,[2026-03-16] Severity: high. VT score: 16. Top...
216,167.94.138.124,2026-03-16,Address,120,3,0.993425,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,700,693,536,high,[2026-03-16] Severity: high. VT score: 16. Top...
261,171.25.193.235,2026-03-15,Address,218,5,0.988055,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,"Fancy Bear, Seashell Blizzard, UNC4487",210,356,578,high,[2026-03-16] Severity: high. VT score: 16. Top...
280,176.65.134.22,2026-03-16,Address,55,3,0.996986,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9375302,NaN,730,744,727,high,[2026-03-16] Severity: high. VT score: 20. Top...
286,176.65.148.52,2026-03-15,Address,32,3,0.998247,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,387,524,high,[2026-03-16] Severity: high. VT score: 19. Top...
318,184.105.247.252,2026-03-16,Address,91,3,0.995014,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9332624,NaN,290,471,551,high,[2026-03-16] Severity: high. VT score: 15. Top...
328,185.156.73.233,2026-03-16,Address,13,3,0.999288,0,0,"NIH, OS",Incident:INC9373125;Incident:INC9373119,NaN,570,664,539,high,[2026-03-16] Severity: high. VT score: 15. Top...
483,193.32.162.145,2026-03-16,Address,153,3,0.991616,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9263763,NaN,810,784,583,high,[2026-03-16] Severity: high. VT score: 16. Top...
534,198.235.24.194,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,288,504,high,[2026-03-16] Severity: high. VT score: 15. Top...
574,198.235.24.68,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,510,453,511,high,[2026-03-16] Severity: high. VT score: 15. Top...
610,2.57.121.112,2026-03-16,Address,96,3,0.994740,0,0,"OS, VA",Incident:INC9307742,NaN,700,693,628,high,[2026-03-16] Severity: high. VT score: 16. Top...
612,2.57.121.25,2026-03-16,Address,100,3,0.994521,0,0,"OS, VA",Incident:INC9307742,NaN,710,698,628,high,[2026-03-16] Severity: high. VT score: 16. Top...
658,205.210.31.209,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,288,504,high,[2026-03-16] Severity: high. VT score: 15. Top...
666,205.210.31.230,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,368,505,high,[2026-03-16] Severity: high. VT score: 15. Top...
692,205.210.31.66,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,312,504,high,[2026-03-16] Severity: high. VT score: 15. Top...
699,205.210.31.79,2026-03-16,Address,67,3,0.996329,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,368,506,high,[2026-03-16] Severity: high. VT score: 15. Top...
762,213.209.159.158,2026-03-16,Address,24,3,0.998685,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9411178,NaN,820,789,693,high,[2026-03-16] Severity: high. VT score: 18. Top...
848,45.148.10.141,2026-03-16,Address,55,4,0.996986,0,0,"HHS, OS",NaN,"Crimson Collective, Scattered Spider, UNC6395",690,671,820,critical,[2026-03-16] Severity: critical. VT score: 15....
851,45.153.34.87,2026-03-16,Address,34,3,0.998137,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9366814,NaN,180,590,571,high,[2026-03-16] Severity: high. VT score: 16. Top...
870,46.161.27.151,2026-03-15,Address,2,4,0.999890,0,0,"CMS, HHS",NaN,ShadowSyndicate,860,708,675,high,[2026-03-16] Severity: high. VT score: 17. Top...
1179,65.49.1.92,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,416,505,high,[2026-03-16] Severity: high. VT score: 15. Top...
1185,65.49.1.99,2026-03-16,Address,265,3,0.985479,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,416,504,high,[2026-03-16] Severity: high. VT score: 15. Top...
1222,80.94.92.171,2026-03-16,Address,109,3,0.994027,0,0,"CDC, CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9303503,NaN,820,789,603,high,[2026-03-16] Severity: high. VT score: 17. Top...

In [8]:
import sys
import os
import urllib3
from configparser import ConfigParser

# Add your local ThreatConnect SDK to path
sys.path.append(r"Z:\HTOC\Data_Analytics\threatconnect")
from ThreatConnect import ThreatConnect
from RequestObject import RequestObject
from Owners import Owners

# Add your project repo to path
project_root = r"C:\Users\jaskew\Documents\project_repository\scripts\Data Movement\ThrearConnect-api-pull"
if project_root not in sys.path:
    sys.path.append(project_root)

from utils.config_loader import load_config

# Load API config
config_path = os.path.join(project_root, "utils", "config.json")
try:
    api_secret_key, api_access_id, api_base_url, api_default_org = load_config(config_path)
    display(f"Loaded config from: {config_path}")
    display(f"Base URL: {api_base_url}")
    display(f"Access ID: {api_access_id}")
    display(f"Default Org: {api_default_org}")
except Exception as e:
    display(f"[ERROR] Failed to load configuration: {e}")
    sys.exit(1)

# Disable SSL verification warnings (use cautiously)
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
verify_ssl = False

# Initialize ThreatConnect session
try:
    tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)
    display("ThreatConnect initialized.")
except Exception as e:
    display(f"[ERROR] Failed to initialize ThreatConnect: {e}")
    sys.exit(1)

# Define the owner (organization scope)
owner = 'HTOC Org'

# Create a request object to fetch indicators (or other data)
try:
    ro = RequestObject()
    ro.set_http_method('GET')
    ro.set_owner(owner)
    ro.set_owner_allowed(True)
    # ro.set_resource_pagination(True)  # Uncomment if needed
    display("RequestObject successfully created.")
except Exception as e:
    display(f"[ERROR] Failed to initialize RequestObject: {e}")
    sys.exit(1)

'Loaded config from: C:\\Users\\jaskew\\Documents\\project_repository\\scripts\\Data Movement\\ThrearConnect-api-pull\\utils\\config.json'

'Base URL: https://hvs.threatconnect.com/api'

'Access ID: 09783848890162390382'

'Default Org: HTOC Org'

'ThreatConnect initialized.'

'RequestObject successfully created.'

In [10]:
import pandas as pd
from datetime import datetime, timedelta
import pytz
import urllib.parse

# Configuration for ThreatConnect indicator query
QUERY_LOOKBACK_DAYS = 30  # days of lastObserved activity to include
INDICATOR_TYPE_NAMES = [
    "Address", "EmailAddress", "File", "Host", "URL", "ASN", "CIDR",
    "Email Subject", "Hashtag", "Mutex", "Registry Key", "User Agent",
]
OWNER_NAMES = [
    'HTOC Org',
    'CISA Federal Feed',
    'CMS_CTI',
    'Crowdstrike Falcon Intelligence',
    'DHS CISCP',
    'Intel471',
    'Mandiant Advantage Threat Intelligence',
    'VA_TIP Data',
]
RESULT_PAGE_SIZE = 500  # keep this smaller; same fields, just paged
INDICATOR_CHUNK_SIZE = 100  # limit size of summary IN (...) clauses

# Setup
cutoff = pd.Timestamp.utcnow()
start_date = (datetime.now(pytz.UTC) - timedelta(days=QUERY_LOOKBACK_DAYS)).date()
start = f"{start_date}T00:00:00Z"

type_names = INDICATOR_TYPE_NAMES
type_name_condition = ", ".join([f'"{t}"' for t in type_names])

list_of_owners = OWNER_NAMES

# Build owner IN (...) clause
owner_condition = ", ".join([f'"{o}"' for o in list_of_owners])

# Build indicator list from final_indicators (must already exist)
if 'final_indicators' not in globals():
    raise RuntimeError("final_indicators is not defined. Run the scoring cell first.")

if 'Indicator' not in final_indicators.columns:
    raise RuntimeError("final_indicators must have an 'Indicator' column.")

indicator_values = (
    final_indicators['Indicator']
    .astype(str)
    .str.strip()
    .unique()
    .tolist()
)

if not indicator_values:
    raise RuntimeError("final_indicators has no Indicator values to query.")

# Chunk indicators so the TQL summary IN (...) clause and URL don't get too large
indicator_chunks = [
    indicator_values[i:i + INDICATOR_CHUNK_SIZE]
    for i in range(0, len(indicator_values), INDICATOR_CHUNK_SIZE)
]

final_results = []

# Query indicators (paginate so you don't 502 with heavy fields)
# Create a NEW RequestObject WITHOUT owner restriction to query across all owners
ro_multi = RequestObject()
ro_multi.set_http_method('GET')

for chunk in indicator_chunks:
    # Build summary IN ("x","y",...) clause for this chunk
    summary_condition = ", ".join([f'"{v}"' for v in chunk])

    tql_raw = (
        f'ownerName IN ({owner_condition}) AND '
        f'typeName IN ({type_name_condition}) AND '
        f'lastObserved >= "{start}" AND '
        f'summary IN ({summary_condition})'
    )

    tql_encoded = urllib.parse.quote(tql_raw)

    result_start = 0
    result_limit = RESULT_PAGE_SIZE

    while True:
        try:
            # NOTE: same fields list you requested (tags,observations,associatedGroups,falsePositives,threatAssess)
            ro_multi.set_request_uri(
                f'/v3/indicators?tql={tql_encoded}'
                f'&fields=tags,observations,associatedGroups,falsePositives,threatAssess'
                f'&resultStart={result_start}&resultLimit={result_limit}'
            )

            response = tc.api_request(ro_multi)

            ct = response.headers.get('content-type', '')
            if not ct.startswith('application/json'):
                raise RuntimeError(f"Non-JSON response ({ct}): {response.content[:200]}")

            results = response.json()
            data_items = results.get('data', []) or []

            # stop when no more results
            if not data_items:
                break

            final_results.append(results)
            result_start += result_limit

        except Exception as e:
            display(f"Failed to query indicators (chunk size={len(chunk)}, start={result_start}): {e}")
            break

# Normalize results
normalized_data = []
for result in final_results:
    data_items = result.get('data', [])
    if not data_items:
        display("No data returned in API response:", result)
    for item in data_items:
        if isinstance(item, dict) and 'summary' in item:
            normalized_data.append(item)

if normalized_data:
    observed_src = pd.json_normalize(normalized_data)
    observed_src['indicator'] = observed_src['summary'].astype(str).str.split().str[0].str.strip()
    observed_src['lastObserved'] = pd.to_datetime(observed_src['lastObserved'], utc=True, errors='coerce')
    observed_src = observed_src[observed_src['lastObserved'] >= pd.to_datetime(start, utc=True)]

    # Create a 'sources' column by aggregating ownerName values per indicator
    sources_per_indicator = (
        observed_src.groupby('indicator')['ownerName']
        .apply(lambda x: ', '.join(sorted(set(x))))
        .reset_index()
        .rename(columns={'ownerName': 'sources'})
    )

    # Merge sources back into observed_src
    observed_src = observed_src.merge(sources_per_indicator, on='indicator', how='left')
    # Filter to keep only records where ownerName is 'HTOC Org'
    observed_src = observed_src[observed_src['ownerName'] == 'HTOC Org'].copy()
else:
    display("No valid indicator data found.")
    observed_src = pd.DataFrame()

display(observed_src)

,id,dateAdded,ownerId,ownerName,webLink,type,lastModified,rating,confidence,threatAssessRating,...,privateFlag,active,activeLocked,ip,legacyLink,tags.data,source,associatedGroups.data,indicator,sources
0,5629499561376171,2025-07-28T17:15:37Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T13:22:31Z,3.0,48.0,1.50,...,False,True,False,198.235.24.68,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...",NaN,NaN,198.235.24.68,"DHS CISCP, HTOC Org"
1,5629499578154891,2025-11-25T18:08:21Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T13:22:28Z,3.0,66.0,2.00,...,False,True,False,2.57.121.112,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,2.57.121.112,"CISA Federal Feed, HTOC Org"
2,6755399482008641,2025-11-21T16:32:42Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T13:22:23Z,3.0,64.0,3.00,...,False,True,False,80.94.92.171,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,80.94.92.171,HTOC Org
3,6755399475098423,2025-10-09T12:44:59Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T11:22:21Z,3.0,59.0,1.50,...,False,True,False,139.19.117.131,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,139.19.117.131,"DHS CISCP, HTOC Org"
4,5629499588124309,2026-02-17T20:34:32Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T11:22:21Z,3.0,78.0,1.50,...,False,True,False,213.209.159.158,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,213.209.159.158,"CISA Federal Feed, HTOC Org"
8,5629499574100045,2025-10-22T17:52:34Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T10:06:01Z,4.0,65.0,2.00,...,False,True,False,45.148.10.141,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 1739892, 'name': 'UNC6395', 'lastUsed'...",NaN,"[{'id': 6755399479000167, 'dateAdded': '2026-0...",45.148.10.141,"CMS_CTI, HTOC Org"
11,6755399465229522,2025-07-28T17:34:08Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T09:22:16Z,3.0,71.0,1.50,...,False,True,False,205.210.31.230,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,205.210.31.230,"DHS CISCP, HTOC Org"
12,5629499584034451,2026-01-20T19:44:18Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T09:22:15Z,3.0,73.0,2.00,...,False,True,False,185.156.73.233,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 35760, 'name': 'OS Splunk API', 'descr...",NaN,NaN,185.156.73.233,HTOC Org
13,6755399481063961,2025-11-17T16:08:16Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T09:22:13Z,3.0,65.0,2.00,...,False,True,False,167.94.138.124,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,167.94.138.124,"DHS CISCP, HTOC Org"
14,5629499578154887,2025-11-25T18:08:18Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T09:22:12Z,3.0,66.0,2.00,...,False,True,False,2.57.121.25,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,2.57.121.25,"CISA Federal Feed, HTOC Org"
15,5629499570118108,2025-10-02T17:13:20Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T09:22:12Z,3.0,57.0,3.00,...,False,True,False,193.32.162.145,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,193.32.162.145,HTOC Org
17,6755399494008118,2026-02-28T17:40:37Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T09:01:01Z,3.0,80.0,1.50,...,False,True,False,103.143.10.79,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,103.143.10.79,"CISA Federal Feed, HTOC Org"
20,6755399467058891,2025-08-08T14:21:47Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T09:01:01Z,3.0,50.0,1.00,...,False,True,False,123.58.207.81,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,123.58.207.81,"DHS CISCP, HTOC Org"
21,5629499582019974,2025-12-29T14:35:07Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T09:01:01Z,3.0,71.0,2.65,...,False,True,False,138.59.233.5,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,138.59.233.5,"CISA Federal Feed, HTOC Org"
22,5629499581012209,2025-12-15T16:04:41Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T09:01:01Z,3.0,69.0,2.50,...,False,True,False,184.105.247.252,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,184.105.247.252,HTOC Org
25,5629499584035050,2026-01-21T14:28:00Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T00:24:38Z,3.0,73.0,1.50,...,False,True,False,176.65.134.22,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,176.65.134.22,"CISA Federal Feed, HTOC Org"
26,5629499547737364,2025-06-04T16:43:17Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-16T00:07:17Z,3.0,41.0,2.00,...,False,True,False,176.65.148.52,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...",NaN,NaN,176.65.148.52,HTOC Org
29,5629499536037128,2025-04-14T16:04:29Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-15T23:23:16Z,5.0,56.0,2.47,...,False,True,False,171.25.193.235,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 494361, 'name': 'UNC4487', 'lastUsed':...",NaN,"[{'id': 6755399448000753, 'dateAdded': '2025-0...",171.25.193.235,HTOC Org
30,6755399487004193,2026-01-14T14:12:02Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-15T09:22:18Z,3.0,73.0,3.00,...,False,True,False,45.153.34.87,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,45.153.34.87,HTOC Org
32,4406762,2023-09-26T18:36:47Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-15T07:06:01Z,4.0,48.0,1.60,...,False,True,False,46.161.27.151,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 258988, 'name': 'Amber Members', 'last...",NaN,"[{'id': 5629499546000858, 'dateAdded': '2025-0...",46.161.27.151,"CMS_CTI, HTOC Org"
33,6755399465229527,2025-07-28T17:34:12Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-14T00:24:26Z,3.0,50.0,1.50,...,False,True,False,65.49.1.92,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,65.49.1.92,"DHS CISCP, HTOC Org"
35,6755399459078588,2025-06-25T17:34:59Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-14T00:06:49Z,3.0,50.0,1.50,...,False,True,False,65.49.1.99,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...",NaN,NaN,65.49.1.99,"DHS CISCP, HTOC Org"
37,6755399465229332,2025-07-28T17:15:57Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-13T00:23:53Z,3.0,48.0,1.00,...,False,True,False,205.210.31.66,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...",NaN,NaN,205.210.31.66,"DHS CISCP, HTOC Org"
38,6755399465229335,2025-07-28T17:15:59Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-11T09:23:23Z,3.0,48.0,1.50,...,False,True,False,205.210.31.209,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...",NaN,NaN,205.210.31.209,"DHS CISCP, HTOC Org"
39,5629499561376901,2025-07-28T17:34:11Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-11T09:23:16Z,3.0,48.0,1.50,...,False,True,False,198.235.24.194,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...",NaN,NaN,198.235.24.194,"DHS CISCP, HTOC Org"
43,6755399487000241,2026-01-09T15:39:13Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-03-10T09:22:02Z,3.0,72.0,1.50,...,False,True,False,205.210.31.79,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 2023876, 'name': 'VA OIT CSOC CTS Splu...",NaN,NaN,205.210.31.79,"DHS CISCP, HTOC Org"

In [18]:
import pandas as pd

# Helper to see if an indicator has an I&W tag
def has_iw(tags_value):
    """
    tags_value is typically a list of dicts from ThreatConnect, e.g.:
    [{'name': 'I&W'}, {'name': 'something else'}, ...]
    """
    if tags_value is None or (isinstance(tags_value, float) and pd.isna(tags_value)):
        return False

    if not isinstance(tags_value, (list, tuple)):
        return False

    for t in tags_value:
        try:
            if isinstance(t, dict):
                name = str(t.get('name', '')).strip()
            else:
                name = str(t).strip()

            if name.lower() in {"i&w", "i & w", "iw"}:
                return True
        except Exception:
            continue
    return False

# 1) Add has_iw flag to observed_src if tags.data exists
if 'tags.data' in observed_src.columns:
    observed_src['has_iw'] = observed_src['tags.data'].apply(has_iw)
else:
    observed_src['has_iw'] = False

# 2) Collapse to one flag per indicator
iw_per_indicator = (
    observed_src.groupby('indicator', dropna=False)['has_iw']
    .max()  # any True -> True
    .reset_index()
    .rename(columns={'indicator': 'Indicator', 'has_iw': 'Reported I&W?_raw'})
)

# 3) Drop ANY existing Reported I&W? variants (_x, _y, etc.)
cols_to_drop = [c for c in final_indicators.columns if c.startswith('Reported I&W?')]
final_indicators = final_indicators.drop(columns=cols_to_drop, errors='ignore')

# 4) Merge once, with a temporary raw boolean column
final_indicators = final_indicators.merge(
    iw_per_indicator,
    on='Indicator',
    how='left'
)

# 5) Convert to Yes/No, defaulting missing to 'No'
final_indicators['Reported I&W?'] = (
    final_indicators['Reported I&W?_raw']
    .fillna(False)
    .map({True: 'Yes', False: 'No'})
)

# 6) Drop the temporary raw column
final_indicators = final_indicators.drop(columns=['Reported I&W?_raw'])

final_indicators

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation,Reported I&W?
0,103.143.10.79,2026-03-16,Address,17,3,0.999068,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,770,764,673,high,[2026-03-16] Severity: high. VT score: 17. Top...,No
1,123.58.207.81,2026-03-16,Address,215,3,0.988219,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9185304,NaN,380,439,619,high,[2026-03-16] Severity: high. VT score: 15. Top...,No
2,138.59.233.5,2026-03-16,Address,71,3,0.996110,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9346798,NaN,540,600,626,high,[2026-03-16] Severity: high. VT score: 15. Top...,No
3,139.19.117.131,2026-03-16,Address,159,3,0.991288,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9267413,NaN,790,721,650,high,[2026-03-16] Severity: high. VT score: 16. Top...,No
4,167.94.138.124,2026-03-16,Address,120,3,0.993425,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,700,693,536,high,[2026-03-16] Severity: high. VT score: 16. Top...,No
5,171.25.193.235,2026-03-15,Address,218,5,0.988055,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,"Fancy Bear, Seashell Blizzard, UNC4487",210,356,578,high,[2026-03-16] Severity: high. VT score: 16. Top...,Yes
6,176.65.134.22,2026-03-16,Address,55,3,0.996986,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9375302,NaN,730,744,727,high,[2026-03-16] Severity: high. VT score: 20. Top...,No
7,176.65.148.52,2026-03-15,Address,32,3,0.998247,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,387,524,high,[2026-03-16] Severity: high. VT score: 19. Top...,No
8,184.105.247.252,2026-03-16,Address,91,3,0.995014,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9332624,NaN,290,471,551,high,[2026-03-16] Severity: high. VT score: 15. Top...,No
9,185.156.73.233,2026-03-16,Address,13,3,0.999288,0,0,"NIH, OS",Incident:INC9373125;Incident:INC9373119,NaN,570,664,539,high,[2026-03-16] Severity: high. VT score: 15. Top...,No
10,193.32.162.145,2026-03-16,Address,153,3,0.991616,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9263763,NaN,810,784,583,high,[2026-03-16] Severity: high. VT score: 16. Top...,No
11,198.235.24.194,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,288,504,high,[2026-03-16] Severity: high. VT score: 15. Top...,No
12,198.235.24.68,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,510,453,511,high,[2026-03-16] Severity: high. VT score: 15. Top...,No
13,2.57.121.112,2026-03-16,Address,96,3,0.994740,0,0,"OS, VA",Incident:INC9307742,NaN,700,693,628,high,[2026-03-16] Severity: high. VT score: 16. Top...,No
14,2.57.121.25,2026-03-16,Address,100,3,0.994521,0,0,"OS, VA",Incident:INC9307742,NaN,710,698,628,high,[2026-03-16] Severity: high. VT score: 16. Top...,No
15,205.210.31.209,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,288,504,high,[2026-03-16] Severity: high. VT score: 15. Top...,No
16,205.210.31.230,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,368,505,high,[2026-03-16] Severity: high. VT score: 15. Top...,No
17,205.210.31.66,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,312,504,high,[2026-03-16] Severity: high. VT score: 15. Top...,No
18,205.210.31.79,2026-03-16,Address,67,3,0.996329,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,368,506,high,[2026-03-16] Severity: high. VT score: 15. Top...,No
19,213.209.159.158,2026-03-16,Address,24,3,0.998685,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9411178,NaN,820,789,693,high,[2026-03-16] Severity: high. VT score: 18. Top...,No
20,45.148.10.141,2026-03-16,Address,55,4,0.996986,0,0,"HHS, OS",NaN,"Crimson Collective, Scattered Spider, UNC6395",690,671,820,critical,[2026-03-16] Severity: critical. VT score: 15....,Yes
21,45.153.34.87,2026-03-16,Address,34,3,0.998137,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9366814,NaN,180,590,571,high,[2026-03-16] Severity: high. VT score: 16. Top...,No
22,46.161.27.151,2026-03-15,Address,2,4,0.999890,0,0,"CMS, HHS",NaN,ShadowSyndicate,860,708,675,high,[2026-03-16] Severity: high. VT score: 17. Top...,No
23,65.49.1.92,2026-03-16,Address,232,3,0.987288,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,416,505,high,[2026-03-16] Severity: high. VT score: 15. Top...,No
24,65.49.1.99,2026-03-16,Address,265,3,0.985479,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,416,504,high,[2026-03-16] Severity: high. VT score: 15. Top...,No
25,80.94.92.171,2026-03-16,Address,109,3,0.994027,0,0,"CDC, CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9303503,NaN,820,789,603,high,[2026-03-16] Severity: high. VT score: 17. Top...,No

from datetime import datetime

# Build dated output path
today_str = datetime.today().strftime('%Y%m%d')  # e.g. 20260316
output_path = rf"Z:\HTOC\Data_Analytics\Data\Threat Assessment Scores\ThreatAssessI_W\ThreatAssessI_W_{today_str}.xlsx"

# Write to Excel
final_indicators.to_excel(output_path, index=False)

output_path