In [1]:
import sys
import os
import urllib3
from configparser import ConfigParser

# Add your local ThreatConnect SDK to path
sys.path.append(r"Z:\HTOC\Data_Analytics\threatconnect")
from ThreatConnect import ThreatConnect
from RequestObject import RequestObject
from Owners import Owners

# Add your project repo to path
project_root = r"C:\Users\jaskew\Documents\project_repository\scripts\Data Movement\ThrearConnect-api-pull"
if project_root not in sys.path:
    sys.path.append(project_root)

from utils.config_loader import load_config

# Load API config
config_path = os.path.join(project_root, "utils", "config.json")
try:
    api_secret_key, api_access_id, api_base_url, api_default_org = load_config(config_path)
    display(f"Loaded config from: {config_path}")
    display(f"Base URL: {api_base_url}")
    display(f"Access ID: {api_access_id}")
    display(f"Default Org: {api_default_org}")
except Exception as e:
    display(f"[ERROR] Failed to load configuration: {e}")
    sys.exit(1)

# Disable SSL verification warnings (use cautiously)
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
verify_ssl = False

# Initialize ThreatConnect session
try:
    tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)
    display("ThreatConnect initialized.")
except Exception as e:
    display(f"[ERROR] Failed to initialize ThreatConnect: {e}")
    sys.exit(1)

# Define the owner (organization scope)
owner = 'HTOC Org'

# Create a request object to fetch indicators (or other data)
try:
    ro = RequestObject()
    ro.set_http_method('GET')
    ro.set_owner(owner)
    ro.set_owner_allowed(True)
    # ro.set_resource_pagination(True)  # Uncomment if needed
    display("RequestObject successfully created.")
except Exception as e:
    display(f"[ERROR] Failed to initialize RequestObject: {e}")
    sys.exit(1)

'Loaded config from: C:\\Users\\jaskew\\Documents\\project_repository\\scripts\\Data Movement\\ThrearConnect-api-pull\\utils\\config.json'

'Base URL: https://hvs.threatconnect.com/api'

'Access ID: 09783848890162390382'

'Default Org: HTOC Org'

'ThreatConnect initialized.'

'RequestObject successfully created.'

In [12]:
import pandas as pd
from datetime import datetime, timedelta
import pytz
import urllib.parse

# Setup
cutoff = pd.Timestamp.utcnow()
start_date = (datetime.now(pytz.UTC) - timedelta(days=3)).date()
start = f"{start_date}T00:00:00Z"
type_names = ["Address", "EmailAddress", "File", "Host", "URL", "ASN", "CIDR",
              "Email Subject", "Hashtag", "Mutex", "Registry Key", "Stripped URL", "User Agent"]
type_name_condition = ", ".join([f'"{t}"' for t in type_names])
list_of_owners = ['HTOC Org']
final_results = []

# Query indicators
for owner in list_of_owners:
    display(f"Querying owner: {owner}")
    try:
        tql_raw = (
            f'ownerName EQ "{owner}" AND '
            f'typeName IN ({type_name_condition}) AND '
            f'lastObserved >= "{start}"'
        )
        tql_encoded = urllib.parse.quote(tql_raw)
        ro.set_http_method('GET')
        ro.set_request_uri(f'/v3/indicators?tql={tql_encoded}&fields=tags,observations,associatedGroups&resultStart=0&resultLimit=10000')
        response = tc.api_request(ro)

        if response.headers.get('content-type') == 'application/json':
            results = response.json()
            final_results.append(results)
    except Exception as e:
        display(f"Failed to query indicators for {owner}: {e}")

# Normalize results
normalized_data = []
for result in final_results:
    data_items = result.get('data', [])
    if not data_items:
        display("No data returned in API response:", result)
    for item in data_items:
        if isinstance(item, dict) and 'summary' in item:
            normalized_data.append(item)

if normalized_data:
    observed_src = pd.json_normalize(normalized_data)
    observed_src['indicator'] = observed_src['summary'].str.split().str[0].str.strip()
    observed_src.drop_duplicates(subset='indicator', inplace=True)
    observed_src['lastObserved'] = pd.to_datetime(observed_src['lastObserved'], utc=True)
    observed_src = observed_src[observed_src['lastObserved'] >= pd.to_datetime(start)]
else:
    display("No valid indicator data found.")
    observed_src = pd.DataFrame()

display(observed_src)

'Querying owner: HTOC Org'

,id,dateAdded,ownerId,ownerName,webLink,type,lastModified,rating,confidence,description,...,legacyLink,tags.data,associatedGroups.data,hostName,dnsActive,whoisActive,source,address,url,indicator
0,6755399447111241,2025-05-14T17:44:47Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T12:25:16Z,1.0,4,FBI Email Alert May 14 2025,...,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.236.176.16
1,5265101,2025-01-23T19:51:13Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T12:12:28Z,1.0,6,CISA conducted a hunt on IoC's obtained from o...,...,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...","[{'id': 546888, 'dateAdded': '2025-01-23T19:51...",NaN,NaN,NaN,NaN,NaN,NaN,146.190.241.65
2,5265088,2025-01-23T19:51:13Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T12:09:04Z,3.0,57,CISA conducted a hunt on IoC's obtained from o...,...,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 471298, 'name': 'DHA Splunk API', 'las...","[{'id': 546888, 'dateAdded': '2025-01-23T19:51...",NaN,NaN,NaN,NaN,NaN,NaN,138.197.101.95
3,6755399459033722,2025-06-16T17:42:11Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T12:08:55Z,3.0,71,RITM0589984,...,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 35760, 'name': 'OS Splunk API', 'descr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,185.40.4.149
4,5629499564010904,2025-08-18T13:49:34Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T12:08:50Z,3.0,80,INC9198174,...,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 35760, 'name': 'OS Splunk API', 'descr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.86.35.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1287,4503719,2024-01-23T19:14:31Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Stripped URL,2025-01-17T23:24:43Z,3.0,80,A phishing email with a .htm file containing a...,...,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 238537, 'name': 'fake voicemail', 'las...","[{'id': 308984, 'dateAdded': '2024-01-23T19:14...",NaN,NaN,NaN,https://aka.ms/LearnAboutSenderIdentification,NaN,aka.ms/learnaboutsenderidentification,aka.ms/learnaboutsenderidentification
1288,4324196,2023-04-21T14:22:00Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Stripped URL,2025-01-16T23:23:57Z,3.0,84,NaN,...,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 34822, 'name': 'business email comprom...","[{'id': 149988, 'dateAdded': '2023-04-21T14:08...",NaN,NaN,NaN,NaN,NaN,geo.netsupportsoftware.com/location/loca.asp,geo.netsupportsoftware.com/location/loca.asp
1290,4585199,2024-04-30T15:02:57Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Stripped URL,2024-05-05T23:23:15Z,4.0,54,VA users received email messages from <Good Ch...,...,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 39680, 'name': 'Initial Access: Phishi...",NaN,NaN,NaN,NaN,NaN,NaN,track.christianityreport.net,track.christianityreport.net
1291,4585198,2024-04-30T15:02:57Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Stripped URL,2024-04-30T15:24:35Z,4.0,51,VA users received email messages from <Good Ch...,...,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 39680, 'name': 'Initial Access: Phishi...",NaN,NaN,NaN,NaN,NaN,NaN,christianityreport.net,christianityreport.net
1292,4442727,2023-10-06T23:26:48Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Stripped URL,2024-03-28T23:23:43Z,3.0,83,NaN,...,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 35760, 'name': 'OS Splunk API', 'descr...",NaN,NaN,NaN,NaN,https://google,NaN,google,google

In [3]:
import pandas as pd
from datetime import datetime, timedelta
import pytz
import urllib.parse

# Setup
cutoff = pd.Timestamp.utcnow()
start_date = (datetime.now(pytz.UTC) - timedelta(days=3)).date()
start = f"{start_date}T00:00:00Z"

# Fields to return from GET /v3/indicators/{indicatorId or indicator}
detail_fields = [
    "ownerName", "type", "summary", "dateAdded", "lastModified", "active",
    "confidence", "rating", "threatAssessScore", "observations",
    "tags", "attributes", "securityLabels", "associatedGroups"
]

list_of_indicators = ['207.167.64.24'] 

# Build the keys to fetch
if "observed_src" in globals() and isinstance(observed_src, pd.DataFrame) and not observed_src.empty:
    if "id" in observed_src.columns:
        indicator_keys = (
            observed_src["id"].dropna().astype(str).str.strip().tolist()
        )
    elif "summary" in observed_src.columns:
        indicator_keys = (
            observed_src["summary"].dropna().astype(str).str.strip().tolist()
        )
    else:
        indicator_keys = list_of_indicators
else:
    indicator_keys = list_of_indicators

# De-duplicate while preserving order
seen = set()
ordered_keys = []
for k in indicator_keys:
    if k and k not in seen:
        seen.add(k)
        ordered_keys.append(k)

final_results = []

# Query indicators (single-resource endpoint only)
for key in ordered_keys:
    display(f"Querying indicator: {key}")
    try:
        # URL-encode the path segment (works for both numeric IDs and summary strings)
        path_key = urllib.parse.quote(str(key), safe="")
        ro.set_http_method('GET')
        ro.set_request_uri(f'/v3/indicators/{path_key}?fields=tags,observations,associatedGroups&resultStart=0&resultLimit=10000')
        response = tc.api_request(ro)

        if response.headers.get('content-type') == 'application/json':
            result = response.json() or {}
            final_results.append(result)
    except Exception as e:
        pass

# Normalize results
normalized_data = []
for result in final_results:
    data_item = result.get('data', {})
    # v3 single GET usually returns a dict; occasionally data['indicator'] may hold it
    if isinstance(data_item, dict):
        record = data_item.get('indicator', data_item)
        if isinstance(record, dict) and 'summary' in record:
            normalized_data.append(record)
    elif isinstance(data_item, list):
        # Very rare shape; keep parity with earlier normalizer
        for item in data_item:
            if isinstance(item, dict) and 'summary' in item:
                normalized_data.append(item)

if normalized_data:
    observed_src = pd.json_normalize(normalized_data)
    # Derive a simple 'indicator' token from summary (e.g., first token)
    if 'summary' in observed_src.columns:
        observed_src['indicator'] = observed_src['summary'].astype(str).str.split().str[0].str.strip()

    # Drop dupes on 'indicator' if it exists
    if 'indicator' in observed_src.columns:
        observed_src.drop_duplicates(subset='indicator', inplace=True)

    # Filter to lastObserved >= start, if lastObserved exists
    if 'lastObserved' in observed_src.columns:
        observed_src['lastObserved'] = pd.to_datetime(observed_src['lastObserved'], utc=True, errors='coerce')
        #observed_src = observed_src[observed_src['lastObserved'] >= pd.to_datetime(start)]
else:
    display("No valid indicator data found.")
    observed_src = pd.DataFrame()

display(observed_src)

'Querying indicator: 207.167.64.24'

,id,dateAdded,ownerId,ownerName,webLink,type,lastModified,rating,confidence,description,summary,observations,lastObserved,privateFlag,active,activeLocked,ip,legacyLink,tags.data,indicator
0,5629499556005918,2025-06-30T17:15:16Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-18T07:46:16Z,3.0,73,RITM0594044,207.167.64.24,247054,2025-08-17 00:00:00+00:00,False,True,False,207.167.64.24,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 749, 'name': 'malicious', 'lastUsed': ...",207.167.64.24

In [4]:
# Unnest tags.data in observed_src to get a list of each tag per indicator

# Explode tags.data to one row per tag
tags_exploded = (
    observed_src[['indicator', 'tags.data']]
      .explode('tags.data')
      .dropna(subset=['tags.data'])
)

# Extract tag name from each tag object
tags_exploded['tag_name'] = tags_exploded['tags.data'].apply(lambda x: x.get('name') if isinstance(x, dict) else None)

# Aggregate all tag names into a list per indicator
tags_per_indicator = (
    tags_exploded.groupby('indicator')['tag_name']
    .apply(lambda x: [t for t in x if t])
    .reset_index()
    .rename(columns={'tag_name': 'tag_list'})
)

# Merge back to observed_src if desired
observed_src_with_tags = observed_src.merge(tags_per_indicator, on='indicator', how='left')

display(observed_src_with_tags[['indicator', 'tag_list']])

       indicator                                           tag_list
0  207.167.64.24  [malicious, CDC Splunk API, Observed, HHS Splu...

In [5]:
# List of tags to count (case-insensitive, strip whitespace)
tags_of_interest = [
    "Scanning", "DDoS", "Spam", "Phishing", "Cryptojacking",
    "Credential Stuffing", "Ransomware", "Data Theft",
    "Cross Site Scripting Attacks", "SQL Injections"
]

# Normalize tag_list to lowercase for matching
def tag_counter(tag_list, tag):
    if not isinstance(tag_list, list):
        return 0
    return sum(1 for t in tag_list if isinstance(t, str) and t.strip().lower() == tag.lower())

tag_counts = {}
for tag in tags_of_interest:
    tag_counts[tag] = observed_src_with_tags['tag_list'].apply(lambda lst: tag_counter(lst, tag)).sum()
    # Add a column to observed_src with the list of matching "Botnet" tags per indicator
    botnet_tags = set(tags_of_interest)
    def extract_botnet_tags(tag_list):
        if not isinstance(tag_list, list):
            return []
        return [t for t in tag_list if isinstance(t, str) and t.strip().lower() in {b.lower() for b in botnet_tags}]

    # Map indicator to its tag_list for efficient lookup
    indicator_to_tags = dict(zip(observed_src_with_tags['indicator'], observed_src_with_tags['tag_list']))

    observed_src['Botnet'] = observed_src['indicator'].map(lambda ind: extract_botnet_tags(indicator_to_tags.get(ind, [])))
# Display as a DataFrame for readability
pd.DataFrame(list(tag_counts.items()), columns=['Tag', 'Count'])

                            Tag  Count
0                      Scanning      0
1                          DDoS      0
2                          Spam      0
3                      Phishing      0
4                 Cryptojacking      0
5           Credential Stuffing      0
6                    Ransomware      0
7                    Data Theft      0
8  Cross Site Scripting Attacks      0
9                SQL Injections      0

In [10]:
observed_src

,id,dateAdded,ownerId,ownerName,webLink,type,lastModified,rating,confidence,description,...,observations,lastObserved,privateFlag,active,activeLocked,ip,legacyLink,tags.data,indicator,Botnet
0,5629499556005918,2025-06-30T17:15:16Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-18T07:46:16Z,3.0,73,RITM0594044,...,247054,2025-08-17 00:00:00+00:00,False,True,False,207.167.64.24,https://hvs.threatconnect.com/auth/indicators/...,"[{'id': 749, 'name': 'malicious', 'lastUsed': ...",207.167.64.24,[]

In [11]:
import os
import pandas as pd
from datetime import datetime, timedelta

# Base file path with placeholder for date
base_path = r"Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d{date}.csv"
#base_path = r"C:\Users\jaskew\Documents\project_repository\data\raw\ObservationDataFiles\htoc_opdiv_obs_d{date}.csv"
date_format = "%Y%m%d"

def get_file_paths(base_path, days=3):
    """ Generate file paths for the last `days` days using list comprehension. """
    today = datetime.utcnow()
    dates_to_pull = [(today - timedelta(days=i)).strftime(date_format) for i in range(days)]
    
    # Construct file paths
    file_paths = [base_path.format(date=dt) for dt in dates_to_pull]
    
    # Filter for existing files
    existing_files = [file_path for file_path in file_paths if os.path.exists(file_path)]
    
    if not existing_files:
        display("No files found for the specified date range.")
    else:
        display(f"Files to be loaded: {existing_files}")
    
    return existing_files

def load_observed_data(file_paths):
    """ Load and concatenate observed data from multiple files. """
    data_frames = []

    for file_path in file_paths:
        try:
            df = pd.read_csv(file_path)
            data_frames.append(df)
        except Exception as e:
            display(f"Error reading file {file_path}: {e}")
    
    # Concatenate data
    if data_frames:
        observed_data_df = pd.concat(data_frames, ignore_index=True)
        display(f"Loaded data from {len(data_frames)} files.")
    else:
        observed_data_df = pd.DataFrame()

    return observed_data_df

# Example Usage:
# Fetch file paths for the last 3 days
file_paths = get_file_paths(base_path, days=1)

# Load observed data
observed_data_df = load_observed_data(file_paths)

C:\Users\jaskew\AppData\Local\Temp\ipykernel_18948\1319479530.py:12: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  today = datetime.utcnow()

"Files to be loaded: ['Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250819.csv']"

'Loaded data from 1 files.'

In [12]:
import pandas as pd

df = observed_src.copy()

#df = df[df['indicator'].isin(observed_data_df['indicator'])]
# --- FULL TAGS UNNEST + PARTNERS ---

# explode tags.data
tags_exploded = (
    df[['indicator', 'tags.data']]
      .explode('tags.data')
      .dropna(subset=['tags.data'])
)

# normalize all fields in tags.data into flat columns
tags_norm = pd.json_normalize(tags_exploded['tags.data'])
tags_norm.columns = [f"tag_{c}" for c in tags_norm.columns]

# re‑attach indicator
tags_expanded = tags_exploded.reset_index(drop=True).join(tags_norm)

# extract partners
tags_expanded['partner'] = tags_expanded['tag_name'].map(
    lambda n: n[:-len(' Splunk API')] if isinstance(n, str) and n.endswith(' Splunk API') else None
)

# aggregate each tag_* field into a list per indicator
tag_fields = list(tags_norm.columns)
tag_agg = (
    tags_expanded
      .groupby('indicator', as_index=False)
      .agg({
          **{f: list for f in tag_fields},
          'partner': lambda x: [p for p in dict.fromkeys(x) if p]
      })
      .rename(columns={'partner':'partners'})
)

# --- GROUPS VIA EXPLODE + GROUPBY ---

#groups_exploded = (
#    df[['indicator', 'associatedGroups.data']]
#      .explode('associatedGroups.data')
#      .dropna(subset=['associatedGroups.data'])
#)

#group_norm = pd.json_normalize(
#    groups_exploded['associatedGroups.data']
#).rename(columns={'id':'group_id','name':'group_name'})

#groups_exploded = groups_exploded.reset_index(drop=True).join(group_norm)

#group_agg = (
#    groups_exploded
#      .drop_duplicates(subset=['indicator','group_id','group_name'])
#      .groupby('indicator', as_index=False)
#      .agg({
#          'group_id':   lambda ids: list(ids),
#          'group_name': lambda names: list(names)
#      })
#      .rename(columns={'group_id':'group_ids','group_name':'group_names'})
#)

# --- CORE AGGREGATION OF OTHER COLUMNS ---

first_cols = [
    'id','dateAdded','ownerId','ownerName','webLink','type','lastModified',
    'rating','confidence','description','summary','observations',
    'lastObserved','privateFlag','active','activeLocked','ip',
    'legacyLink','source','address','url'
]
# Remove 'hostName', 'dnsActive', 'whoisActive' from first_cols to avoid KeyError

# Add 'Botnet' column from observed_src if it exists
if 'Botnet' in observed_src.columns:
    df['Botnet'] = observed_src['Botnet']
    first_cols.append('Botnet')

base_agg = (
    df
      .drop(columns=[
          'createdBy.id','createdBy.userName','createdBy.firstName','createdBy.lastName',
          'createdBy.pseudonym','createdBy.owner','xid','eventType','documentDateAdded',
          'documentType','fileSize','fileName','downVoteCount','upVoteCount','type_group',
          'webLink_group','ownerName_group','ownerId_group','dateAdded_group','id_group',
          'platforms.count','tactics.count',
      ], errors='ignore')
      .groupby('indicator', as_index=False)[
          [c for c in first_cols if c in df.columns]
      ]
      .first()
)

# --- MERGE EVERYTHING BACK ---

agg_df = (
    base_agg
      .merge(tag_agg,   on='indicator', how='left')
#      .merge(group_agg, on='indicator', how='left')
)

def clean_list(lst):
    if not isinstance(lst, list):
        return []
    cleaned = []
    for v in lst:
        # drop any null‑like values
        try:
            if pd.isna(v):
                continue
        except Exception:
            pass
        # drop empty strings
        if isinstance(v, str) and v == "":
            continue
        cleaned.append(v)
    return cleaned

def list_to_csv(lst):
    """
    Takes a cleaned list and returns:
      - a comma-separated string of its items, OR
      - an empty string if there are none.
    """
    if not lst:
        return ""
    return ", ".join(str(v) for v in lst)

# apply to all your formerly‑list columns
#for col in ['partners','group_ids','group_names'] + tag_fields:
#    agg_df[col] = agg_df[col].apply(clean_list).apply(list_to_csv)

# Only apply to columns that exist in agg_df to avoid KeyError
for col in ['partners', 'group_ids', 'group_names'] + tag_fields:
    if col in agg_df.columns:
        agg_df[col] = agg_df[col].apply(clean_list).apply(list_to_csv)
    
display(agg_df)

,indicator,id,dateAdded,ownerId,ownerName,webLink,type,lastModified,rating,confidence,...,active,activeLocked,ip,legacyLink,Botnet,tag_id,tag_name,tag_lastUsed,tag_description,partners
0,207.167.64.24,5629499556005918,2025-06-30T17:15:16Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-18T07:46:16Z,3.0,73,...,True,False,207.167.64.24,https://hvs.threatconnect.com/auth/indicators/...,[],"749, 23575, 23576, 23577, 23586, 23630, 23769,...","malicious, CDC Splunk API, Observed, HHS Splun...","2025-08-18T14:50:29Z, 2025-08-19T10:13:24Z, 20...",Observations reported by the HHS Ofice of the ...,"CDC, HHS, IHS, NIH, CMS, FDA, OS, DHA"

In [13]:
# ──────────────────────────────────────────────────────────────────────────────
# Enrich only final filtered indicators (Shodan & VirusTotalV3) and flatten
# ──────────────────────────────────────────────────────────────────────────────
import urllib.parse
import pandas as pd

COL_PATH = "data.enrichment.data"   # adjust if API changes

indicator_values = (
    agg_df["summary"]
    .dropna()
    .astype(str)
    .unique()
    .tolist()
)

display(f"Enriching {len(indicator_values)} indicators with Shodan & VirusTotalV3...")

enriched_results = []
failed = []

for value in indicator_values:
    try:
        encoded_value = urllib.parse.quote(value, safe="")
        q = urllib.parse.urlencode({"type": ["Shodan", "VirusTotalV3"]}, doseq=True)
        enrich_url = f"/v3/indicators/{encoded_value}/enrich?{q}"

        # Build a fresh RequestObject each loop (adjust to your SDK)
        ro = RequestObject()
        ro.set_http_method("POST")
        ro.set_request_uri(enrich_url)
        ro.set_body({})

        resp = tc.api_request(ro)
        resp.raise_for_status()

        data = resp.json()
        data["summary"] = value
        enriched_results.append(data)

    except Exception as e:
        failed.append({"summary": value, "error": str(e)})

# If nothing enriched, just carry on
if not enriched_results:
    display("No enrichment data retrieved.")
    recent_tags = agg_df.copy()

else:
    # One row per summary from enrichment payload
    df_enriched = (
        pd.json_normalize(enriched_results)
          .drop_duplicates(subset="summary", keep="last")
    )

    # Merge enrichment block into base
    recent_tags = agg_df.merge(df_enriched, on="summary", how="left")

    # ── Flatten enrichment payload without creating duplicate base rows ───────
    if COL_PATH in recent_tags.columns:
        exploded = (
            recent_tags[["summary", COL_PATH]]
            .explode(COL_PATH)
            .dropna(subset=[COL_PATH])
        )

        enrich_flat = pd.json_normalize(exploded[COL_PATH]).add_prefix("enrich_")
        enrich_flat["summary"] = exploded["summary"].values

        # ---- Aggregation helpers ---------------------------------------------
        def _flatten_lists(values):
            """Flatten one level of lists in a sequence, keep dicts intact."""
            out = []
            for v in values:
                if isinstance(v, list):
                    out.extend(v)
                else:
                    out.append(v)
            return out

        def _agg_obj(series: pd.Series):
            vals = [v for v in series.dropna()]
            if not vals:
                return None
            flat = _flatten_lists(vals)
            # if everything is hashable & not dict/list, dedupe
            if all(not isinstance(v, (list, dict)) for v in flat):
                return list(pd.unique(flat))
            return flat  # keep as-is when dicts/lists present

        obj_cols = enrich_flat.select_dtypes("object").columns.difference(["summary"])
        num_cols = enrich_flat.columns.difference(obj_cols.union({"summary"}))

        agg_dict = {c: _agg_obj for c in obj_cols}
        # choose your numeric aggregation; 'max' or 'first'
        agg_dict.update({c: "max" for c in num_cols})

        enrich_wide = (
            enrich_flat
              .groupby("summary", as_index=False)
              .agg(agg_dict)
        )

        # Remove raw list col and merge flattened cols back
        recent_tags = (
            recent_tags.drop(columns=[COL_PATH], errors="ignore")
                       .drop_duplicates(subset="summary")
                       .merge(enrich_wide, on="summary", how="left")
        )

        display(f"Successfully enriched and merged {len(df_enriched)} indicators.")
    else:
        display("Enrichment column not found; nothing to flatten.")

# Optional: report/log failures
if failed:
    display(f"{len(failed)} indicators failed to enrich.")
    # Example: pd.DataFrame(failed).to_json("enrich_failures.json", orient="records")

'Enriching 1 indicators with Shodan & VirusTotalV3...'

C:\Users\jaskew\AppData\Local\Temp\ipykernel_23376\2721959216.py:88: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  return list(pd.unique(flat))

'Successfully enriched and merged 1 indicators.'

In [14]:
recent_tags.drop(columns=['tag_id', 'tag_lastUsed', 'tag_lastModified', 'tag_ownerId', 
                          'tag_ownerName', 'tag_dateAdded', 'tag_description','tag_tactics.count', 
                          'tag_platform.data', 'tag_platform.count', 'data.id', 'data.dateAdded', 'data.ownerId',
                          'data.webLink', 'data.ownerName', 'data.lastModified', 'data.summary', 'data.ip',
                          'data.legacyLink','data.source', 'enrich_cloudProvider', 'enrich_cloudRegion', 'enrich_type',
                          'id'], inplace=True, errors='ignore')

recent_tags

,indicator,dateAdded,ownerId,ownerName,webLink,type,lastModified,rating,confidence,description,...,data.activeLocked,enrich_asn,enrich_city,enrich_country,enrich_isp,enrich_openPorts,enrich_org,enrich_tags,enrich_vulnerabilities,enrich_vtMaliciousCount
0,207.167.64.24,2025-06-30T17:15:16Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-18T07:46:16Z,3.0,73,RITM0594044,...,False,[AS399045],[Kansas City],[United States],"[DediOutlet, LLC]","[{'transport': 'tcp', 'port': 21, 'data': '220...",[Sullivan's Hosting LLC],[scanner],"[{'name': 'CVE-2024-38475', 'port': 80, 'descr...",21.0

In [ ]:
from pymongo import MongoClient

# Connect to MongoDB
client = MongoClient("mongodb://localhost:27017/")
db = client["Threat_Assess_Controlled_Scoring_Data"]
collection = db["controlled_enriched_observation_Data"]

# Convert DataFrame to dictionary records
records = recent_tags.to_dict(orient="records")

# Insert records into MongoDB
result = collection.insert_many(records)
print(f"Inserted {len(result.inserted_ids)} documents into enriched_observation_Data.")

client.close()

In [97]:
from pymongo import MongoClient
import pandas as pd

# Connect to MongoDB
client = MongoClient("mongodb://localhost:27017/")
db = client["Threat_Assess_Larger_Scoring_Data"]
collection = db["larger_enriched_observation_Data"]

# Pull data back from MongoDB
docs = list(collection.find())
recent_tags = pd.DataFrame(docs)
print(f"Pulled {len(recent_tags)} documents from enriched_observation_Data.")

Pulled 10000 documents from enriched_observation_Data.

In [99]:
recent_tags = recent_tags.head(50)
recent_tags.loc[recent_tags['enrich_vtMaliciousCount'].isnull(), 'enrich_vtMaliciousCount'] = 0
display(recent_tags)

,_id,indicator,dateAdded,ownerId,ownerName,webLink,type,lastModified,rating,confidence,...,enrich_city,enrich_country,enrich_domains,enrich_hostNames,enrich_isp,enrich_openPorts,enrich_org,enrich_tags,enrich_vulnerabilities,enrich_vtMaliciousCount
0,68a60b186a95e5f0822c49b8,0-------zpital-of-philadelphia-crowdstrike.gw....,2024-07-29T16:43:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:41Z,3.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,68a60b186a95e5f0822c49b9,00512-okta-0cd1fe6e4d31c9b-12-okta.core.gw-ste...,2024-07-29T16:43:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:50Z,3.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,68a60b186a95e5f0822c49ba,00512-okta-0cd1fe6e4d31c9b-12-okta.core.gw.cro...,2024-07-29T16:43:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:42Z,3.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,68a60b186a95e5f0822c49bb,00518-okta-0cd1fe6e4d61c9b-18-okta-stepwell-cr...,2024-07-29T16:43:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:37Z,3.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,68a60b186a95e5f0822c49bc,00d7ks32.life,2024-05-07T15:02:23Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-20T07:59:56Z,3.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
5,68a60b186a95e5f0822c49bd,0212top.online,2024-07-08T20:55:55Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:49Z,4.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
6,68a60b186a95e5f0822c49be,0212top.site,2024-07-08T20:55:55Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:39Z,4.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
7,68a60b186a95e5f0822c49bf,0212top.top,2024-07-08T20:55:55Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:54Z,4.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
8,68a60b186a95e5f0822c49c0,0212top.xyz,2024-07-08T20:55:55Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:36Z,4.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
9,68a60b186a95e5f0822c49c1,02B4571470D83163D103112F07F1C434,2025-07-23T16:41:24Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,File,2025-08-19T18:04:32Z,5.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
10,68a60b186a95e5f0822c49c2,0370.ru,2024-04-22T17:20:07Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:52Z,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11,68a60b186a95e5f0822c49c3,03bna10rk88tp9lq.gw-stepwell-crowdstrike-nifi-...,2024-08-01T13:47:54Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-16T08:03:39Z,3.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
12,68a60b186a95e5f0822c49c4,0539.crowdstrike.denarii.cash,2024-07-29T16:43:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:49Z,3.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
13,68a60b186a95e5f0822c49c5,05CED941CFD74C8E631BB087B18358B9,2025-08-18T15:00:52Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,File,2025-08-18T15:00:54Z,3.0,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
14,68a60b186a95e5f0822c49c6,0824.cronos.com.ar,2024-02-29T16:54:09Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-16T08:03:40Z,5.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
15,68a60b186a95e5f0822c49c7,0909kses.top,2024-07-08T20:55:55Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:55Z,4.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
16,68a60b186a95e5f0822c49c8,0BA36C80167919A98CFFC002CF6819D3F5E117207E901A...,2025-08-19T12:24:10Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,File,2025-08-19T12:24:13Z,4.0,70.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
17,68a60b186a95e5f0822c49c9,0EC721718294F18D7173D777C8FE7CB4,2025-08-07T14:32:35Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,File,2025-08-16T08:04:35Z,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
18,68a60b186a95e5f0822c49ca,0a3myb17.life,2024-05-07T15:02:23Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-20T07:59:46Z,3.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
19,68a60b186a95e5f0822c49cb,0flzv18rk2obqbzl.crowdstrike.prod.careem-pay.com,2024-08-01T13:47:54Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-16T08:03:20Z,3.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
20,68a60b186a95e5f0822c49cc,1-careem-stepwell-crowdstrike-nifi-np.careem.ae,2024-07-29T16:43:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:37Z,3.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
21,68a60b186a95e5f0822c49cd,1-you.njalla.no,2025-02-11T16:19:08Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-16T08:03:37Z,5.0,74.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
22,68a60b186a95e5f0822c49ce,1.112.1.1,2017-01-03T15:27:15Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:26Z,5.0,82.0,...,None,None,None,None,None,None,None,None,None,3.0
23,68a60b186a95e5f0822c49cf,1.116.139.11,2025-07-14T18:49:57Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:25Z,3.0,64.0,...,None,None,None,None,None,None,None,None,None,0.0
24,68a60b186a95e5f0822c49d0,1.119.3.28,2024-07-01T16:24:37Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:08Z,4.0,12.0,...,[Beijing],[China],None,None,[Priority of Fashion(Beijing)Information Techn...,"[{'transport': 'tcp', 'port': 80, 'product': '...",[Priority of Fashion(Beijing)Information Techn...,"[eol-os, self-signed, database]","[{'name': 'CVE-2014-4078', 'port': 81, 'descri...",0.0
25,68a60b186a95e5f0822c49d1,1.163.226.38,2025-05-06T16:54:45Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:03:14Z,3.0,46.0,...,None,None,None,None,None,None,None,None,None,0.0
26,68a60b186a95e5f0822c49d2,1.170.115.172,2025-05-06T16:54:45Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:02:58Z,3.0,46.0,...,[Taichung],[Taiwan],[hinet.net],[1-170-115-172.dynamic-ip.hinet.net],[Data Communication Business Group],"[{'transport': 'udp', 'port': 1900, 'data': 'H...","[Chunghwa Telecom Co.,Ltd.]",None,None,0.0
27,68a60b186a95e5f0822c49d3,1.192.18.4,2025-05-14T17:47:35Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-18T07:46:22Z,3.0,67.0,...,None,None,None,None,None,None,None,None,None,4.0
28,68a60b186a95e5f0822c49d4,1.204.166.3,2025-05-14T17:47:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-20T07:59:27Z,3.0,66.0,...,None,None,None,None,None,None,None,None,None,3.0
29,68a60b186a95e5f0822c49d5,1.212.1.1,2017-01-03T15:27:15Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:24Z,5.0,82.0,...,None,None,None,None,None,None,None,None,None,0.0
30,68a60b186a95e5f0822c49d6,1.54.101.176,2025-07-02T12:05:31Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:03:05Z,4.0,67.0,...,None,None,None,None,None,None,None,None,None,0.0
31,68a60b186a95e5f0822c49d7,1.94.136.42,2025-04-07T11:23:00Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:32Z,4.0,50.0,...,[Shanghai],[China],[hwclouds-dns.com],[ecs-1-94-136-42.compute.hwclouds-dns.com],[Huawei Cloud Service data center],"[{'transport': 'tcp', 'port': 22, 'product': '...","[Beijing Teletron Telecom Engineering Co., Ltd.]",None,None,1.0
32,68a60b186a95e5f0822c49d8,1.zip,2024-05-10T12:40:11Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:37Z,5.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
33,68a60b186a95e5f0822c49d9,100.27.42.247,2025-08-11T15:16:09Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-18T07:46:17Z,3.0,79.0,...,None,None,None,None,None,None,None,None,None,0.0
34,68a60b186a95e5f0822c49da,1005.filemail.com,2025-01-21T14:28:16Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-20T07:59:57Z,3.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
35,68a60b186a95e5f0822c49db,101.206.168.19,2025-01-21T12:37:22Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:09Z,5.0,71.0,...,None,None,None,None,None,None,None,None,None,0.0
36,68a60b186a95e5f0822c49dc,101.206.169.129,2025-01-21T12:37:22Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:08Z,5.0,71.0,...,None,None,None,None,None,None,None,None,None,0.0
37,68a60b186a95e5f0822c49dd,101.36.106.114,2025-04-07T11:23:00Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:23Z,4.0,50.0,...,[Hong Kong],[Hong Kong],None,None,[UCLOUD INFORMATION TECHNOLOGY (HK) LIMITED],"[{'transport': 'tcp', 'port': 25, 'data': '220...",[UCLOUD INFORMATION TECHNOLOGY (HK) LIMITED],[self-signed],None,11.0
38,68a60b186a95e5f0822c49de,101.36.108.94,2025-04-07T11:23:00Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:12Z,4.0,50.0,...,[Hong Kong],[Hong Kong],[gost.run],[gost.run],[UCLOUD INFORMATION TECHNOLOGY (HK) LIMITED],"[{'transport': 'tcp', 'port': 8081, 'data': 'H...",[UCLOUD INFORMATION TECHNOLOGY (HK) LIMITED],[proxy],None,0.0
39,68a60b186a95e5f0822c49df,101.64.234.86,2017-01-03T15:27:15Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:28Z,5.0,82.0,...,[Shanghai],[China],None,None,[CHINA UNICOM China169 Backbone],"[{'transport': 'tcp', 'port': 21, 'product': '...",[UNICOM ZheJiang Province Network],"[eol-product, database]",None,3.0
40,68a60b186a95e5f0822c49e0,101.79.10.222,2025-07-02T12:05:29Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:03:09Z,4.0,67.0,...,None,None,None,None,None,None,None,None,None,1.0
41,68a60b186a95e5f0822c49e1,101.79.5.222,2024-05-13T14:23:27Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-20T07:59:26Z,3.0,3.0,...,None,None,None,None,None,None,None,None,None,0.0
42,68a60b186a95e5f0822c49e2,101.89.148.7,2025-08-09T18:13:37Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:03:14Z,3.0,79.0,...,[Shanghai],[China],None,None,[China Telecom (Group)],"[{'transport': 'tcp', 'port': 22, 'product': '...",[CHINANET SHANGHAI PROVINCE NETWORK],None,"[{'name': 'CVE-2008-3844', 'port': 22, 'descri...",10.0
43,68a60b186a95e5f0822c49e3,101.89.174.236,2025-05-21T18:39:43Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:34Z,3.0,68.0,...,[Shanghai],[China],None,None,[China Telecom (Group)],"[{'transport': 'tcp', 'port': 22, 'data': 'SSH...",[CHINANET SHANGHAI PROVINCE NETWORK],None,None,10.0
44,68a60b186a95e5f0822c49e4,101.98.11.146,2017-01-03T15:27:15Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:04Z,5.0,82.0,...,None,None,None,None,None,None,None,None,None,2.0
45,68a60b186a95e5f0822c49e5,101.99.75.178,2024-05-31T14:00:37Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:03:07Z,4.0,19.0,...,[Lelystad],[Netherlands],"[kamon.la, ritalinkopen.online]","[www.ritalinkopen.online, mail.ritalinkopen.on...",[Shinjiru Technology Sdn Bhd],"[{'transport': 'tcp', 'port': 21, 'data': '220...",[Shinjiru Technology Sdn Bhd],"[self-signed, starttls]",None,5.0
46,68a60b186a95e5f0822c49e6,101.99.75.232,2024-04-22T17:16:35Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:29Z,3.0,1.0,...,None,None,None,None,None,None,None,None,None,3.0
47,68a60b186a95e5f0822c49e7,101.99.75.251,2024-04-22T17:16:35Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:20Z,3.0,1.0,...,None,None,None,None,None,None,None,None,None,0.0
48,68a60b186a95e5f0822c49e8,1019.billybobandirect.org,2025-05-23T18:26:59Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-16T08:03:28Z,3.0,63.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
49,68a60b186a95e5f0822c49e9,102.0.5.152,2025-07-02T12:05:36Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:03:03Z,4.0,67.0,...,[Nairobi],[Kenya],[airtelkenya.com],[152-5-0-102.r.airtelkenya.com],[Airtel Networks Kenya Limited],"[{'transport': 'udp', 'port': 161, 'product': ...",[Allocated to Airtel Kenya Mobile Broadband an...,[vpn],None,1.0

In [105]:
import os
import pandas as pd
from datetime import datetime, timedelta

# Base file path with placeholder for date
base_path = r"Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d{date}.csv"
#base_path = r"C:\Users\jaskew\Documents\project_repository\data\raw\ObservationDataFiles\htoc_opdiv_obs_d{date}.csv"
date_format = "%Y%m%d"

def get_file_paths(base_path, days):
    """ Generate file paths for the last `days` days using list comprehension. """
    today = datetime.utcnow()
    dates_to_pull = [(today - timedelta(days=i)).strftime(date_format) for i in range(days)]
    
    # Construct file paths
    file_paths = [base_path.format(date=dt) for dt in dates_to_pull]
    
    # Filter for existing files
    existing_files = [file_path for file_path in file_paths if os.path.exists(file_path)]
    
    if not existing_files:
        print("No files found for the specified date range.")
    else:
        print(f"Files to be loaded: {existing_files}")
    
    return existing_files

def load_observed_data(file_paths):
    """ Load and concatenate observed data from multiple files. """
    data_frames = []

    for file_path in file_paths:
        try:
            df = pd.read_csv(file_path)
            data_frames.append(df)
        except Exception as e:
            print(f"Error reading file {file_path}: {e}")
    
    # Concatenate data
    if data_frames:
        observed_data_df = pd.concat(data_frames, ignore_index=True)
        print(f"Loaded data from {len(data_frames)} files.")
    else:
        observed_data_df = pd.DataFrame()

    return observed_data_df

# Example Usage:
# Fetch file paths for the last 3 days
file_paths = get_file_paths(base_path, days=365)

# Load observed data
observed_data_df = load_observed_data(file_paths)

Files to be loaded: ['Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250825.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250824.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250823.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250822.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250821.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250820.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250819.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250818.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250817.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250816.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250815.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250814.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250813.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250812.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250811.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250810.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250809.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250808.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250807.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250806.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250805.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250804.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250803.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250802.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250801.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250731.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250730.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250729.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250728.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250727.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250726.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250725.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250724.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250723.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250722.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250721.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250720.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250719.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250718.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250717.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250716.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250715.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250714.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250713.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250712.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250711.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250710.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250709.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250708.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250707.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250706.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250705.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250704.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250703.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250702.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250701.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250630.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250629.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250628.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250627.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250626.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250625.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250624.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250623.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250622.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250621.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250620.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250619.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250618.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250617.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250616.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250615.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250614.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250613.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250612.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250611.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250610.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250609.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250608.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250607.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250606.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250605.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250604.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250603.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250602.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250601.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250531.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250530.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250529.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250528.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250527.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250526.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250525.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250524.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250523.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250522.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250521.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250520.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250519.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250518.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250517.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250516.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250515.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250514.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250513.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250512.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250511.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250510.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250509.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250508.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250507.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250506.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250505.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250504.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250503.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250502.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250501.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250430.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250429.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250428.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250427.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250426.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250425.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250424.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250423.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250422.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250421.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250420.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250419.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250418.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250417.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250416.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250415.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250414.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250413.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250412.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250411.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250410.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250409.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250408.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250407.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250406.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250405.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250404.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250403.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250402.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250401.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250331.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250330.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250329.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250328.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250327.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250326.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250325.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250324.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250323.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250322.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250321.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250320.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250319.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250318.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250317.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250316.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250315.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250314.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250313.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250312.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250311.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250310.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250309.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250308.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250307.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250306.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250305.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250304.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250303.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250302.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250301.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250228.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250227.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250226.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250225.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250224.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250223.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250222.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250221.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250220.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250219.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250218.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250217.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250216.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250215.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250214.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250213.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250212.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250211.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250210.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250209.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250208.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250207.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250206.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250205.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250204.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250203.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250202.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250201.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250131.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250130.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250129.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250128.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250127.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250126.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250125.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250124.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250123.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250122.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250121.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250120.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250119.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250118.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250117.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250116.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250115.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250114.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250113.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250112.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250111.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250110.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250109.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250108.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250107.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250106.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250105.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250104.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250103.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250102.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20250101.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241231.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241230.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241229.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241228.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241227.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241226.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241225.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241224.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241223.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241222.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241221.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241220.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241219.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241218.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20241217.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d2024121

In [106]:
# Count how many times each indicator in recent_tags was seen in observed_data_df
indicator_counts = (
    observed_data_df['indicator']
    .value_counts()
    .rename('obs_count')
    .reset_index()
    .rename(columns={'index': 'indicator'})
)

# Merge the counts into recent_tags
recent_tags = recent_tags.merge(indicator_counts, on='indicator', how='left')
recent_tags['obs_count'] = recent_tags['obs_count'].fillna(0).astype(int)

display(recent_tags[['indicator', 'obs_count']])

                                            indicator  obs_count
0   0-------zpital-of-philadelphia-crowdstrike.gw....          0
1   00512-okta-0cd1fe6e4d31c9b-12-okta.core.gw-ste...          0
2   00512-okta-0cd1fe6e4d31c9b-12-okta.core.gw.cro...          0
3   00518-okta-0cd1fe6e4d61c9b-18-okta-stepwell-cr...          0
4                                       00d7ks32.life          0
5                                      0212top.online          0
6                                        0212top.site          0
7                                         0212top.top          0
8                                         0212top.xyz          0
9                    02B4571470D83163D103112F07F1C434          0
10                                            0370.ru          0
11  03bna10rk88tp9lq.gw-stepwell-crowdstrike-nifi-...          0
12                      0539.crowdstrike.denarii.cash          0
13                   05CED941CFD74C8E631BB087B18358B9          0
14                                 0824.cronos.com.ar          0
15                                       0909kses.top          0
16  0BA36C80167919A98CFFC002CF6819D3F5E117207E901A...          0
17                   0EC721718294F18D7173D777C8FE7CB4          0
18                                      0a3myb17.life          0
19   0flzv18rk2obqbzl.crowdstrike.prod.careem-pay.com          0
20    1-careem-stepwell-crowdstrike-nifi-np.careem.ae          0
21                                    1-you.njalla.no         12
22                                          1.112.1.1          0
23                                       1.116.139.11          0
24                                         1.119.3.28          0
25                                       1.163.226.38          0
26                                      1.170.115.172          0
27                                         1.192.18.4         11
28                                        1.204.166.3         17
29                                          1.212.1.1          0
30                                       1.54.101.176          0
31                                        1.94.136.42          0
32                                              1.zip          0
33                                      100.27.42.247         58
34                                  1005.filemail.com          2
35                                     101.206.168.19          0
36                                    101.206.169.129          0
37                                     101.36.106.114          0
38                                      101.36.108.94          0
39                                      101.64.234.86          0
40                                      101.79.10.222          0
41                                       101.79.5.222          0
42                                       101.89.148.7         55
43                                     101.89.174.236        310
44                                      101.98.11.146          0
45                                      101.99.75.178          0
46                                      101.99.75.232          0
47                                      101.99.75.251          0
48                          1019.billybobandirect.org          0
49                                        102.0.5.152          4

In [ ]:
import re

# helper to flatten list-or-str into a list of strings
def flatten_hosts(hosts):
    if isinstance(hosts, list):
        return [h for h in hosts if isinstance(h, str)]
    elif isinstance(hosts, str):
        return [hosts]
    return []

# regex: 
# ^[A-Za-z]+       → first label is one “word” (letters only)
# (?:\.[^.]+){3}$  → exactly three more “.” followed by non-dot characters
four_label_word_prefix = re.compile(r'^[A-Za-z]+(?:\.[^.]+){3}$')

# Try to match on 'enrich_org' instead of 'enrich_hostNames'
if 'enrich_org' in recent_tags.columns:
    global matched_results
    exploded = recent_tags.explode('enrich_org')

    mask = exploded['enrich_org'].astype(str).str.match(four_label_word_prefix, na=False)

    matched = recent_tags.loc[exploded[mask].index.unique()]
    matched_results = matched[['indicator','enrich_org']]
else:
    matched = pd.DataFrame(columns=recent_tags.columns)
    matched_results = None


display(matched_results)

In [109]:
recent_tags

,_id,indicator,dateAdded,ownerId,ownerName,webLink,type,lastModified,rating,confidence,...,enrich_country,enrich_domains,enrich_hostNames,enrich_isp,enrich_openPorts,enrich_org,enrich_tags,enrich_vulnerabilities,enrich_vtMaliciousCount,obs_count
0,68a60b186a95e5f0822c49b8,0-------zpital-of-philadelphia-crowdstrike.gw....,2024-07-29T16:43:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:41Z,3.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
1,68a60b186a95e5f0822c49b9,00512-okta-0cd1fe6e4d31c9b-12-okta.core.gw-ste...,2024-07-29T16:43:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:50Z,3.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
2,68a60b186a95e5f0822c49ba,00512-okta-0cd1fe6e4d31c9b-12-okta.core.gw.cro...,2024-07-29T16:43:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:42Z,3.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
3,68a60b186a95e5f0822c49bb,00518-okta-0cd1fe6e4d61c9b-18-okta-stepwell-cr...,2024-07-29T16:43:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:37Z,3.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
4,68a60b186a95e5f0822c49bc,00d7ks32.life,2024-05-07T15:02:23Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-20T07:59:56Z,3.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
5,68a60b186a95e5f0822c49bd,0212top.online,2024-07-08T20:55:55Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:49Z,4.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
6,68a60b186a95e5f0822c49be,0212top.site,2024-07-08T20:55:55Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:39Z,4.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
7,68a60b186a95e5f0822c49bf,0212top.top,2024-07-08T20:55:55Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:54Z,4.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
8,68a60b186a95e5f0822c49c0,0212top.xyz,2024-07-08T20:55:55Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:36Z,4.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
9,68a60b186a95e5f0822c49c1,02B4571470D83163D103112F07F1C434,2025-07-23T16:41:24Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,File,2025-08-19T18:04:32Z,5.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
10,68a60b186a95e5f0822c49c2,0370.ru,2024-04-22T17:20:07Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:52Z,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
11,68a60b186a95e5f0822c49c3,03bna10rk88tp9lq.gw-stepwell-crowdstrike-nifi-...,2024-08-01T13:47:54Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-16T08:03:39Z,3.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
12,68a60b186a95e5f0822c49c4,0539.crowdstrike.denarii.cash,2024-07-29T16:43:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:49Z,3.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
13,68a60b186a95e5f0822c49c5,05CED941CFD74C8E631BB087B18358B9,2025-08-18T15:00:52Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,File,2025-08-18T15:00:54Z,3.0,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
14,68a60b186a95e5f0822c49c6,0824.cronos.com.ar,2024-02-29T16:54:09Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-16T08:03:40Z,5.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
15,68a60b186a95e5f0822c49c7,0909kses.top,2024-07-08T20:55:55Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:55Z,4.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
16,68a60b186a95e5f0822c49c8,0BA36C80167919A98CFFC002CF6819D3F5E117207E901A...,2025-08-19T12:24:10Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,File,2025-08-19T12:24:13Z,4.0,70.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
17,68a60b186a95e5f0822c49c9,0EC721718294F18D7173D777C8FE7CB4,2025-08-07T14:32:35Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,File,2025-08-16T08:04:35Z,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
18,68a60b186a95e5f0822c49ca,0a3myb17.life,2024-05-07T15:02:23Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-20T07:59:46Z,3.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
19,68a60b186a95e5f0822c49cb,0flzv18rk2obqbzl.crowdstrike.prod.careem-pay.com,2024-08-01T13:47:54Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-16T08:03:20Z,3.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
20,68a60b186a95e5f0822c49cc,1-careem-stepwell-crowdstrike-nifi-np.careem.ae,2024-07-29T16:43:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:37Z,3.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
21,68a60b186a95e5f0822c49cd,1-you.njalla.no,2025-02-11T16:19:08Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-16T08:03:37Z,5.0,74.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12
22,68a60b186a95e5f0822c49ce,1.112.1.1,2017-01-03T15:27:15Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:26Z,5.0,82.0,...,None,None,None,None,None,None,None,None,3.0,0
23,68a60b186a95e5f0822c49cf,1.116.139.11,2025-07-14T18:49:57Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:25Z,3.0,64.0,...,None,None,None,None,None,None,None,None,0.0,0
24,68a60b186a95e5f0822c49d0,1.119.3.28,2024-07-01T16:24:37Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:08Z,4.0,12.0,...,[China],None,None,[Priority of Fashion(Beijing)Information Techn...,"[{'transport': 'tcp', 'port': 80, 'product': '...",[Priority of Fashion(Beijing)Information Techn...,"[eol-os, self-signed, database]","[{'name': 'CVE-2014-4078', 'port': 81, 'descri...",0.0,0
25,68a60b186a95e5f0822c49d1,1.163.226.38,2025-05-06T16:54:45Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:03:14Z,3.0,46.0,...,None,None,None,None,None,None,None,None,0.0,0
26,68a60b186a95e5f0822c49d2,1.170.115.172,2025-05-06T16:54:45Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:02:58Z,3.0,46.0,...,[Taiwan],[hinet.net],[1-170-115-172.dynamic-ip.hinet.net],[Data Communication Business Group],"[{'transport': 'udp', 'port': 1900, 'data': 'H...","[Chunghwa Telecom Co.,Ltd.]",None,None,0.0,0
27,68a60b186a95e5f0822c49d3,1.192.18.4,2025-05-14T17:47:35Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-18T07:46:22Z,3.0,67.0,...,None,None,None,None,None,None,None,None,4.0,11
28,68a60b186a95e5f0822c49d4,1.204.166.3,2025-05-14T17:47:30Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-20T07:59:27Z,3.0,66.0,...,None,None,None,None,None,None,None,None,3.0,17
29,68a60b186a95e5f0822c49d5,1.212.1.1,2017-01-03T15:27:15Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:24Z,5.0,82.0,...,None,None,None,None,None,None,None,None,0.0,0
30,68a60b186a95e5f0822c49d6,1.54.101.176,2025-07-02T12:05:31Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:03:05Z,4.0,67.0,...,None,None,None,None,None,None,None,None,0.0,0
31,68a60b186a95e5f0822c49d7,1.94.136.42,2025-04-07T11:23:00Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:32Z,4.0,50.0,...,[China],[hwclouds-dns.com],[ecs-1-94-136-42.compute.hwclouds-dns.com],[Huawei Cloud Service data center],"[{'transport': 'tcp', 'port': 22, 'product': '...","[Beijing Teletron Telecom Engineering Co., Ltd.]",None,None,1.0,0
32,68a60b186a95e5f0822c49d8,1.zip,2024-05-10T12:40:11Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-19T07:45:37Z,5.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
33,68a60b186a95e5f0822c49d9,100.27.42.247,2025-08-11T15:16:09Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-18T07:46:17Z,3.0,79.0,...,None,None,None,None,None,None,None,None,0.0,58
34,68a60b186a95e5f0822c49da,1005.filemail.com,2025-01-21T14:28:16Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-20T07:59:57Z,3.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2
35,68a60b186a95e5f0822c49db,101.206.168.19,2025-01-21T12:37:22Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:09Z,5.0,71.0,...,None,None,None,None,None,None,None,None,0.0,0
36,68a60b186a95e5f0822c49dc,101.206.169.129,2025-01-21T12:37:22Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:08Z,5.0,71.0,...,None,None,None,None,None,None,None,None,0.0,0
37,68a60b186a95e5f0822c49dd,101.36.106.114,2025-04-07T11:23:00Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:23Z,4.0,50.0,...,[Hong Kong],None,None,[UCLOUD INFORMATION TECHNOLOGY (HK) LIMITED],"[{'transport': 'tcp', 'port': 25, 'data': '220...",[UCLOUD INFORMATION TECHNOLOGY (HK) LIMITED],[self-signed],None,11.0,0
38,68a60b186a95e5f0822c49de,101.36.108.94,2025-04-07T11:23:00Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:12Z,4.0,50.0,...,[Hong Kong],[gost.run],[gost.run],[UCLOUD INFORMATION TECHNOLOGY (HK) LIMITED],"[{'transport': 'tcp', 'port': 8081, 'data': 'H...",[UCLOUD INFORMATION TECHNOLOGY (HK) LIMITED],[proxy],None,0.0,0
39,68a60b186a95e5f0822c49df,101.64.234.86,2017-01-03T15:27:15Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:28Z,5.0,82.0,...,[China],None,None,[CHINA UNICOM China169 Backbone],"[{'transport': 'tcp', 'port': 21, 'product': '...",[UNICOM ZheJiang Province Network],"[eol-product, database]",None,3.0,0
40,68a60b186a95e5f0822c49e0,101.79.10.222,2025-07-02T12:05:29Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:03:09Z,4.0,67.0,...,None,None,None,None,None,None,None,None,1.0,0
41,68a60b186a95e5f0822c49e1,101.79.5.222,2024-05-13T14:23:27Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-20T07:59:26Z,3.0,3.0,...,None,None,None,None,None,None,None,None,0.0,0
42,68a60b186a95e5f0822c49e2,101.89.148.7,2025-08-09T18:13:37Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:03:14Z,3.0,79.0,...,[China],None,None,[China Telecom (Group)],"[{'transport': 'tcp', 'port': 22, 'product': '...",[CHINANET SHANGHAI PROVINCE NETWORK],None,"[{'name': 'CVE-2008-3844', 'port': 22, 'descri...",10.0,55
43,68a60b186a95e5f0822c49e3,101.89.174.236,2025-05-21T18:39:43Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:34Z,3.0,68.0,...,[China],None,None,[China Telecom (Group)],"[{'transport': 'tcp', 'port': 22, 'data': 'SSH...",[CHINANET SHANGHAI PROVINCE NETWORK],None,None,10.0,310
44,68a60b186a95e5f0822c49e4,101.98.11.146,2017-01-03T15:27:15Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:04Z,5.0,82.0,...,None,None,None,None,None,None,None,None,2.0,0
45,68a60b186a95e5f0822c49e5,101.99.75.178,2024-05-31T14:00:37Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:03:07Z,4.0,19.0,...,[Netherlands],"[kamon.la, ritalinkopen.online]","[www.ritalinkopen.online, mail.ritalinkopen.on...",[Shinjiru Technology Sdn Bhd],"[{'transport': 'tcp', 'port': 21, 'data': '220...",[Shinjiru Technology Sdn Bhd],"[self-signed, starttls]",None,5.0,0
46,68a60b186a95e5f0822c49e6,101.99.75.232,2024-04-22T17:16:35Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:29Z,3.0,1.0,...,None,None,None,None,None,None,None,None,3.0,0
47,68a60b186a95e5f0822c49e7,101.99.75.251,2024-04-22T17:16:35Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-19T07:45:20Z,3.0,1.0,...,None,None,None,None,None,None,None,None,0.0,0
48,68a60b186a95e5f0822c49e8,1019.billybobandirect.org,2025-05-23T18:26:59Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Host,2025-08-16T08:03:28Z,3.0,63.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
49,68a60b186a95e5f0822c49e9,102.0.5.152,2025-07-02T12:05:36Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2025-08-16T08:03:03Z,4.0,67.0,...,[Kenya],[airtelkenya.com],[152-5-0-102.r.airtelkenya.com],[Airtel Networks Kenya Limited],"[{'transport': 'udp', 'port': 161, 'product': ...",[Allocated to Airtel Kenya Mobile Broadband an...,[vpn],None,1.0,4

In [140]:
import pandas as pd
import numpy as np

df = recent_tags.copy()

# ── Severity Binning ────────────────────────────
scoring_bins = [0, 200, 500, 800, 1001]
label_bins = ['low', 'medium', 'high', 'critical']

# ── Feature Weights ─────────────────────────────
Weights = {
    "MALICIOUS_WEIGHT": 0.50,
    "OBSERVATION_COUNT_WEIGHT": 0.25,
    "CONTINUITY_WEIGHT": 0.10,
    "BOTNET_FLAG_WEIGHT": -0.20, 
    "TC_RATING": 0.10,
    "TC_CONFIDENCE": 0.05
}

# ── Continuity Map ──────────────────────────────
CONTINUITY_MAP = {
    'Address': 1, 'IPv4': 1, 'IPv6': 1,
    'Domain': 2, 'Host': 2, 'URL': 2,
    'EmailAddress': 2, 'EmailSubject': 2,
    'SHA1': 3, 'SHA256': 3, 'MD5': 3
}

# Known max VT detections
VT_MAX = 94  
BOTNET_MULTIPLIER = 0.8   # penalize 20%
MAX_OBS_REALISTIC = 1000

# ── Raw weighted contributions ──────────────────
df['malicious_scaled'] = np.log1p(df['enrich_vtMaliciousCount'])
df['malicious_raw_score'] = (
    df['malicious_scaled'] * Weights['MALICIOUS_WEIGHT']
)

df['obs_count_raw_score'] = (
    df['obs_count'] * Weights['OBSERVATION_COUNT_WEIGHT']
)

# Continuity contribution
df['continuity_val'] = df['type'].map(CONTINUITY_MAP).fillna(0)
df['continuity_raw_score'] = (
    df['continuity_val'] * Weights['CONTINUITY_WEIGHT']
)

# ── Botnet ─────────────────────────────────────
botnet_actions = {'Scanning','DDoS','Spam','Phishing','Cryptojacking','Credential Stuffing'}
col = df.get('Botnet', None)

if col is None:
    df['botnet_flag'] = 0
else:
    def is_botnet(val):
        if isinstance(val, (list, set, tuple)):
            return int(bool(set(map(str, val)) & botnet_actions))
        if isinstance(val, str):
            parts = {p.strip() for p in val.replace(',', ' ').split()}
            return int(bool(parts & botnet_actions))
        return 0
    df['botnet_flag'] = col.apply(is_botnet).astype(int)

# Analyst inputs
df['tc_raw_rating'] = (
    df['rating'] * Weights['TC_RATING']
)
df['tc_raw_confidence'] = (
    df['confidence'] * Weights['TC_CONFIDENCE']
)

# ── Combine into a total raw score ──────────────
df['raw_score'] = (
    df['malicious_raw_score'] +
    df['obs_count_raw_score'] +
    df['continuity_raw_score'] +
    df['tc_raw_rating'] +
    df['tc_raw_confidence']
)

df['raw_score'] = np.where(
    df['botnet_flag'] == 1,
    df['raw_score'] * BOTNET_MULTIPLIER,
    df['raw_score']
)

# ── Define a hybrid cap (decoupled from weights) ─────────────────────────
max_malicious = np.log1p(VT_MAX)     # theoretical max VT contribution (unweighted)
obs_95th = np.percentile(df['obs_count'], 95) if not df.empty else 0
max_obs = min(obs_95th, MAX_OBS_REALISTIC)    # realistic max obs_count (unweighted)
max_continuity = max(CONTINUITY_MAP.values()) # max continuity value (unweighted)

# apply weights only in raw_score, not here
RAW_SCORE_CAP = (
    max_malicious * Weights['MALICIOUS_WEIGHT'] +
    max_obs * Weights['OBSERVATION_COUNT_WEIGHT'] +
    max_continuity * Weights['CONTINUITY_WEIGHT'] +
    (100 * Weights['TC_RATING']) +
    (100 * Weights['TC_CONFIDENCE'])
)

# ── Normalize to 0–1000 scale ───────────────────
df['Threat_Score'] = 1000 * (df['raw_score'] / RAW_SCORE_CAP).clip(0, 1)

# ── Assign Severity bin ─────────────────────────
df['Severity'] = pd.cut(
    df['Threat_Score'],
    bins=scoring_bins,
    labels=label_bins,
    right=False
)

display(df[['indicator','type','enrich_vtMaliciousCount','obs_count',
            'malicious_raw_score','obs_count_raw_score',
            'continuity_raw_score','tc_raw_rating',
            'tc_raw_confidence','botnet_flag',
            'raw_score','Threat_Score','Severity']])

,indicator,type,enrich_vtMaliciousCount,obs_count,malicious_raw_score,obs_count_raw_score,continuity_raw_score,tc_raw_rating,tc_raw_confidence,botnet_flag,raw_score,Threat_Score,Severity
0,0-------zpital-of-philadelphia-crowdstrike.gw....,Host,0.0,0,0.000000,0.00,0.2,0.3,0.75,0,1.250000,46.207410,low
1,00512-okta-0cd1fe6e4d31c9b-12-okta.core.gw-ste...,Host,0.0,0,0.000000,0.00,0.2,0.3,0.75,0,1.250000,46.207410,low
2,00512-okta-0cd1fe6e4d31c9b-12-okta.core.gw.cro...,Host,0.0,0,0.000000,0.00,0.2,0.3,0.75,0,1.250000,46.207410,low
3,00518-okta-0cd1fe6e4d61c9b-18-okta-stepwell-cr...,Host,0.0,0,0.000000,0.00,0.2,0.3,0.75,0,1.250000,46.207410,low
4,00d7ks32.life,Host,0.0,0,0.000000,0.00,0.2,0.3,0.40,0,0.900000,33.269335,low
5,0212top.online,Host,0.0,0,0.000000,0.00,0.2,0.4,1.15,0,1.750000,64.690373,low
6,0212top.site,Host,0.0,0,0.000000,0.00,0.2,0.4,1.15,0,1.750000,64.690373,low
7,0212top.top,Host,0.0,0,0.000000,0.00,0.2,0.4,1.15,0,1.750000,64.690373,low
8,0212top.xyz,Host,0.0,0,0.000000,0.00,0.2,0.4,1.15,0,1.750000,64.690373,low
9,02B4571470D83163D103112F07F1C434,File,0.0,0,0.000000,0.00,0.0,0.5,5.00,0,5.500000,203.312602,medium
10,0370.ru,Host,0.0,0,0.000000,0.00,0.2,0.3,0.05,0,0.550000,20.331260,low
11,03bna10rk88tp9lq.gw-stepwell-crowdstrike-nifi-...,Host,0.0,0,0.000000,0.00,0.2,0.3,1.25,0,1.750000,64.690373,low
12,0539.crowdstrike.denarii.cash,Host,0.0,0,0.000000,0.00,0.2,0.3,0.75,0,1.250000,46.207410,low
13,05CED941CFD74C8E631BB087B18358B9,File,0.0,0,0.000000,0.00,0.0,0.3,3.00,0,3.300000,121.987561,low
14,0824.cronos.com.ar,Host,0.0,0,0.000000,0.00,0.2,0.5,0.45,0,1.150000,42.510817,low
15,0909kses.top,Host,0.0,0,0.000000,0.00,0.2,0.4,1.15,0,1.750000,64.690373,low
16,0BA36C80167919A98CFFC002CF6819D3F5E117207E901A...,File,0.0,0,0.000000,0.00,0.0,0.4,3.50,0,3.900000,144.167118,low
17,0EC721718294F18D7173D777C8FE7CB4,File,0.0,0,0.000000,0.00,0.0,0.0,0.00,0,0.000000,0.000000,low
18,0a3myb17.life,Host,0.0,0,0.000000,0.00,0.2,0.3,0.40,0,0.900000,33.269335,low
19,0flzv18rk2obqbzl.crowdstrike.prod.careem-pay.com,Host,0.0,0,0.000000,0.00,0.2,0.3,1.25,0,1.750000,64.690373,low
20,1-careem-stepwell-crowdstrike-nifi-np.careem.ae,Host,0.0,0,0.000000,0.00,0.2,0.3,0.75,0,1.250000,46.207410,low
21,1-you.njalla.no,Host,0.0,12,0.000000,3.00,0.2,0.5,3.70,0,7.400000,273.547865,medium
22,1.112.1.1,Address,3.0,0,0.693147,0.00,0.1,0.5,4.10,0,5.393147,199.362689,low
23,1.116.139.11,Address,0.0,0,0.000000,0.00,0.1,0.3,3.20,0,3.600000,133.077340,low
24,1.119.3.28,Address,0.0,0,0.000000,0.00,0.1,0.4,0.60,0,1.100000,40.662520,low
25,1.163.226.38,Address,0.0,0,0.000000,0.00,0.1,0.3,2.30,1,2.160000,79.846404,low
26,1.170.115.172,Address,0.0,0,0.000000,0.00,0.1,0.3,2.30,1,2.160000,79.846404,low
27,1.192.18.4,Address,4.0,11,0.804719,2.75,0.1,0.3,3.35,0,7.304719,270.025713,medium
28,1.204.166.3,Address,3.0,17,0.693147,4.25,0.1,0.3,3.30,0,8.643147,319.501954,medium
29,1.212.1.1,Address,0.0,0,0.000000,0.00,0.1,0.5,4.10,0,4.700000,173.739860,low
30,1.54.101.176,Address,0.0,0,0.000000,0.00,0.1,0.4,3.35,1,3.080000,113.855057,low
31,1.94.136.42,Address,1.0,0,0.346574,0.00,0.1,0.4,2.50,0,3.346574,123.709197,low
32,1.zip,Host,0.0,0,0.000000,0.00,0.2,0.5,4.75,0,5.450000,201.464306,medium
33,100.27.42.247,Address,0.0,58,0.000000,14.50,0.1,0.3,3.95,0,18.850000,696.807737,high
34,1005.filemail.com,Host,0.0,2,0.000000,0.50,0.2,0.3,2.20,0,3.200000,118.290969,low
35,101.206.168.19,Address,0.0,0,0.000000,0.00,0.1,0.5,3.55,0,4.150000,153.408600,low
36,101.206.169.129,Address,0.0,0,0.000000,0.00,0.1,0.5,3.55,0,4.150000,153.408600,low
37,101.36.106.114,Address,11.0,0,1.242453,0.00,0.1,0.4,2.50,0,4.242453,156.826223,low
38,101.36.108.94,Address,0.0,0,0.000000,0.00,0.1,0.4,2.50,0,3.000000,110.897783,low
39,101.64.234.86,Address,3.0,0,0.693147,0.00,0.1,0.5,4.10,0,5.393147,199.362689,low
40,101.79.10.222,Address,1.0,0,0.346574,0.00,0.1,0.4,3.35,1,3.357259,124.104189,low
41,101.79.5.222,Address,0.0,0,0.000000,0.00,0.1,0.3,0.15,0,0.550000,20.331260,low
42,101.89.148.7,Address,10.0,55,1.198948,13.75,0.1,0.3,3.95,0,19.298948,713.403502,high
43,101.89.174.236,Address,10.0,310,1.198948,77.50,0.1,0.3,3.40,0,82.498948,1000.000000,critical
44,101.98.11.146,Address,2.0,0,0.549306,0.00,0.1,0.5,4.10,0,5.249306,194.045471,low
45,101.99.75.178,Address,5.0,0,0.895880,0.00,0.1,0.4,0.95,0,2.345880,86.717621,low
46,101.99.75.232,Address,3.0,0,0.693147,0.00,0.1,0.3,0.05,0,1.143147,42.257496,low
47,101.99.75.251,Address,0.0,0,0.000000,0.00,0.1,0.3,0.05,0,0.450000,16.634667,low
48,1019.billybobandirect.org,Host,0.0,0,0.000000,0.00,0.2,0.3,3.15,0,3.650000,134.925636,low
49,102.0.5.152,Address,1.0,4,0.346574,1.00,0.1,0.4,3.35,1,4.157259,153.676931,low