In [3]:
import pandas as pd

# Load the Excel file
file_path = r"Z:\HTOC\Data_Analytics\Data\Threat Assessment Scores\Threat_Assessment_Scores.xlsx"
df = pd.read_excel(file_path)

# Display the first few rows
df

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
0,1-you.njalla.no,2026-02-03,Host,34,5,0.998137,0,0,"NIH, VA",NaN,Wicked Panda,180,416,312,medium,[2026-03-05] Severity: medium. VT score not av...
1,1.234.83.26,2026-02-14,Address,43,3,0.997644,0,0,"CMS, FDA, HRSA, IHS, OS",NaN,NaN,180,469,199,low,[2026-03-05] Severity: low. VT score: 3. Top d...
2,101.168.57.163,2026-02-14,Address,2,3,0.999890,0,0,"CMS, FDA, OS, VA",NaN,NaN,180,590,555,high,[2026-03-05] Severity: high. VT score: 11. Top...
3,101.71.130.99,2026-03-03,Address,139,3,0.992384,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",NaN,NaN,540,526,467,medium,[2026-03-05] Severity: medium. VT score: 11. T...
4,103.114.96.246,2026-02-26,Address,41,1,0.997753,1,0,"CMS, DHA, NIH, OS, VA",NaN,Mr Hamza Group,180,229,142,low,[2026-03-05] Severity: low. VT score: 2. Top d...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2256,5.79.110.170,2025-12-23,Address,6,0,0.999671,1,0,"CDC, CMS, HHS",Incident:6755399448003491;Incident:529312,NaN,170,363,45,low,Severity: low. VT score: 0. Top drivers: Incid...
2257,146.70.246.116,2026-01-19,Address,3,0,0.999836,1,0,VA,Incident:6755399478001848,NaN,180,368,41,low,Severity: low. VT score: 0. Top drivers: Incid...
2258,198.199.103.243,2026-01-16,Address,1,0,0.999945,1,0,VA,Incident:6755399478001848,NaN,180,368,41,low,Severity: low. VT score: 0. Top drivers: Incid...
2259,rosesci.com,2026-01-08,Host,17,0,0.999068,0,0,NIH,NaN,NaN,170,351,30,low,Severity: low. Could not pull VT score to calc...
2260,52.87.206.242,2026-01-08,Address,1,1,0.999945,1,0,IHS,NaN,NaN,170,224,27,low,Severity: low. VT score: 0. Top drivers: TC ra...

In [4]:
import pandas as pd

# Ensure Last Observed is datetime
df['Last Observed'] = pd.to_datetime(df['Last Observed'])

# Get last 24 hours relative to latest observation
max_obs = df['Last Observed'].max()
cutoff = max_obs - pd.Timedelta(days=1)
last_24h_from_max = df[df['Last Observed'] >= cutoff]

last_24h_from_max

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
5,103.120.116.162,2026-03-05,Address,37,3,0.997973,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,640,820,539,high,[2026-03-05] Severity: high. VT score: 6. Top ...
7,103.140.62.43,2026-03-04,Address,6,5,0.999671,0,0,"DHA, VA",NaN,NaN,180,590,199,low,[2026-03-05] Severity: low. VT score: 3. Top d...
8,103.143.10.79,2026-03-05,Address,6,3,0.999671,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,470,614,633,high,[2026-03-05] Severity: high. VT score: 15. Top...
10,103.172.81.132,2026-03-05,Address,42,0,0.997699,0,0,"CMS, FDA, HHS, NIH, VA",Incident:5629499550000872;Incident:56294995470...,"Emissary Panda, Judgment Panda, UNC6337/STORM-...",180,288,180,low,[2026-03-05] Severity: low. VT score: 2. Top d...
11,103.203.59.0,2026-03-05,Address,271,3,0.985151,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",NaN,NaN,180,368,199,low,[2026-03-05] Severity: low. VT score: 1. Top d...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1401,193.142.147.111,2026-03-05,Address,1,3,0.999945,0,0,HHS,NaN,NaN,170,335,362,medium,[2026-03-05] Severity: medium. VT score: 5. To...
1402,44.206.3.7,2026-03-04,Address,1,3,0.999945,0,0,NIH,NaN,NaN,160,580,199,low,[2026-03-05] Severity: low. VT score: 0. Top d...
1403,64.225.66.97,2026-03-05,Address,2,2,0.999890,0,0,"CMS, DHA, NIH",Event:5629499536001088,NaN,180,229,199,low,[2026-03-05] Severity: low. VT score: 2. Top d...
1404,80.87.206.241,2026-03-05,Address,1,4,0.999945,0,0,"CMS, HHS",NaN,UNC5837,170,321,199,low,[2026-03-05] Severity: low. VT score: 2. Top d...
1405,grobinson@blueridgeinfosystems.com,2026-03-04,EmailAddress,3,3,0.999836,0,0,"CDC, CMS, FDA, HHS, OS, VA",NaN,NaN,170,283,60,low,[2026-03-05] Severity: low. VT score not avail...

In [5]:
# Filter last 24h results to indicators seen at more than one partner
last_24h_multiple_partners = last_24h_from_max[last_24h_from_max['Partners'].str.contains(',', na=False)]

last_24h_multiple_partners

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
5,103.120.116.162,2026-03-05,Address,37,3,0.997973,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,640,820,539,high,[2026-03-05] Severity: high. VT score: 6. Top ...
7,103.140.62.43,2026-03-04,Address,6,5,0.999671,0,0,"DHA, VA",NaN,NaN,180,590,199,low,[2026-03-05] Severity: low. VT score: 3. Top d...
8,103.143.10.79,2026-03-05,Address,6,3,0.999671,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,470,614,633,high,[2026-03-05] Severity: high. VT score: 15. Top...
10,103.172.81.132,2026-03-05,Address,42,0,0.997699,0,0,"CMS, FDA, HHS, NIH, VA",Incident:5629499550000872;Incident:56294995470...,"Emissary Panda, Judgment Panda, UNC6337/STORM-...",180,288,180,low,[2026-03-05] Severity: low. VT score: 2. Top d...
11,103.203.59.0,2026-03-05,Address,271,3,0.985151,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",NaN,NaN,180,368,199,low,[2026-03-05] Severity: low. VT score: 1. Top d...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1396,yourpensionmeeting.com,2026-03-05,Host,220,3,0.987945,0,0,"CMS, DHA, NIH, VA",Incident:6755399453001053,NaN,180,469,360,medium,[2026-03-05] Severity: medium. VT score not av...
1400,177.136.225.180,2026-03-05,Address,2,5,0.999890,0,0,"IHS, NIH, OS, VA",NaN,"Beserk Bear, Cozy Bear, Fancy Bear, Primitive ...",170,585,199,low,[2026-03-05] Severity: low. VT score: 0. Top d...
1403,64.225.66.97,2026-03-05,Address,2,2,0.999890,0,0,"CMS, DHA, NIH",Event:5629499536001088,NaN,180,229,199,low,[2026-03-05] Severity: low. VT score: 2. Top d...
1404,80.87.206.241,2026-03-05,Address,1,4,0.999945,0,0,"CMS, HHS",NaN,UNC5837,170,321,199,low,[2026-03-05] Severity: low. VT score: 2. Top d...
1405,grobinson@blueridgeinfosystems.com,2026-03-04,EmailAddress,3,3,0.999836,0,0,"CDC, CMS, FDA, HHS, OS, VA",NaN,NaN,170,283,60,low,[2026-03-05] Severity: low. VT score not avail...

In [ ]:
# Filter multi-partner, last-24h indicators to VT score >= 10 based on Explanation text
vt_scores = last_24h_multiple_partners['Explanation'].str.extract(r'VT score:\s*(\d+)', expand=False)
vt_scores = pd.to_numeric(vt_scores, errors='coerce')

last_24h_multi_partners_vt10 = last_24h_multiple_partners[vt_scores >= 10]

last_24h_multi_partners_vt10