In [2]:
import pandas as pd

# Load the Excel file
file_path = r"Z:\HTOC\Data_Analytics\Data\Threat Assessment Scores\Threat_Assessment_Scores.xlsx"
df = pd.read_excel(file_path)

# Display the first few rows
df

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
0,1.234.83.26,2026-02-14,Address,43,3,0.997644,0,0,"CMS, FDA, HRSA, OS",NaN,NaN,180,469,154,low,[2026-03-11] Severity: low. VT score: 3. Top d...
1,101.168.57.163,2026-02-14,Address,2,3,0.999890,0,0,"CMS, FDA, OS, VA",Incident:INC9407577,NaN,180,590,458,medium,[2026-03-11] Severity: medium. VT score: 11. T...
2,101.71.130.99,2026-03-03,Address,139,3,0.992384,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",Incident:INC9270850,NaN,360,436,467,medium,[2026-03-11] Severity: medium. VT score: 11. T...
3,103.114.96.246,2026-02-26,Address,41,1,0.997753,1,0,"CMS, DHA, NIH, OS, VA",NaN,Mr Hamza Group,170,224,145,low,[2026-03-11] Severity: low. VT score: 2. Top d...
4,103.120.116.162,2026-03-11,Address,43,3,0.997644,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9385644,NaN,740,870,364,medium,[2026-03-11] Severity: medium. VT score: 6. To...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2282,rosesci.com,2026-01-08,Host,17,0,0.999068,0,0,NIH,NaN,NaN,170,351,30,low,Severity: low. Could not pull VT score to calc...
2283,w-2@doculivery.com,2026-03-04,EmailAddress,2,4,0.999890,1,0,HHS,Incident:547380,NaN,170,224,29,low,[2026-03-06] Severity: low. VT score not avail...
2284,link.edgepilot.com,2026-03-05,Host,74,1,0.995945,0,0,"CMS, NIH",NaN,NaN,180,229,28,low,[2026-03-06] Severity: low. VT score not avail...
2285,52.87.206.242,2026-01-08,Address,1,1,0.999945,1,0,IHS,NaN,NaN,170,224,27,low,Severity: low. VT score: 0. Top drivers: TC ra...
2286,86.38.243.1,2026-02-04,Address,8,4,0.999562,0,0,"NIH, VA",NaN,NaN,170,363,23,low,[2026-03-06] Severity: low. VT score: 0. Top d...

In [3]:
import pandas as pd

# Ensure Last Observed is datetime
df['Last Observed'] = pd.to_datetime(df['Last Observed'])

# Get last 24 hours relative to latest observation
max_obs = df['Last Observed'].max()
cutoff = max_obs - pd.Timedelta(days=1)
last_24h_from_max = df[df['Last Observed'] >= cutoff]

last_24h_from_max

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
4,103.120.116.162,2026-03-11,Address,43,3,0.997644,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9385644,NaN,740,870,364,medium,[2026-03-11] Severity: medium. VT score: 6. To...
6,103.140.62.43,2026-03-11,Address,8,5,0.999562,0,0,"DHA, VA",NaN,NaN,180,590,145,low,[2026-03-11] Severity: low. VT score: 3. Top d...
7,103.143.10.79,2026-03-11,Address,12,3,0.999342,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,780,769,676,high,[2026-03-11] Severity: high. VT score: 17. Top...
10,103.203.59.0,2026-03-11,Address,277,3,0.984822,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",NaN,NaN,180,368,90,low,[2026-03-11] Severity: low. VT score: 1. Top d...
14,103.243.26.49,2026-03-11,Address,50,3,0.997260,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9375302,NaN,180,469,325,medium,[2026-03-11] Severity: medium. VT score: 5. To...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1378,209.38.105.30,2026-03-10,Address,1,3,0.999945,0,0,"CMS, FDA, HRSA, IHS, OS, VA",Incident:INC9328182,NaN,180,469,477,medium,[2026-03-11] Severity: medium. VT score: 11. T...
1379,223.166.97.90,2026-03-10,Address,2,3,0.999890,0,0,"HRSA, OS",NaN,NaN,180,590,37,low,[2026-03-11] Severity: low. VT score: 0. Top d...
1385,80.94.95.43,2026-03-11,Address,2,3,0.999890,0,0,"OS, VA",Incident:INC9427600,NaN,200,479,594,high,[2026-03-11] Severity: high. VT score: 14. Top...
1387,userguidecollection.com,2026-03-11,Host,4,3,0.999781,0,0,"DHA, HRSA, IHS, NIH",NaN,NaN,180,590,50,low,[2026-03-11] Severity: low. VT score not avail...
1388,wavebrowser.co,2026-03-10,Host,1,3,0.999945,0,0,DHA,Incident:5629499576000961,NaN,0,500,86,low,[2026-03-11] Severity: low. VT score not avail...

In [4]:
# Filter last 24h results to indicators seen at more than one partner
last_24h_multiple_partners = last_24h_from_max[last_24h_from_max['Partners'].str.contains(',', na=False)]

last_24h_multiple_partners

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
4,103.120.116.162,2026-03-11,Address,43,3,0.997644,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9385644,NaN,740,870,364,medium,[2026-03-11] Severity: medium. VT score: 6. To...
6,103.140.62.43,2026-03-11,Address,8,5,0.999562,0,0,"DHA, VA",NaN,NaN,180,590,145,low,[2026-03-11] Severity: low. VT score: 3. Top d...
7,103.143.10.79,2026-03-11,Address,12,3,0.999342,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,780,769,676,high,[2026-03-11] Severity: high. VT score: 17. Top...
10,103.203.59.0,2026-03-11,Address,277,3,0.984822,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",NaN,NaN,180,368,90,low,[2026-03-11] Severity: low. VT score: 1. Top d...
14,103.243.26.49,2026-03-11,Address,50,3,0.997260,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9375302,NaN,180,469,325,medium,[2026-03-11] Severity: medium. VT score: 5. To...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,195.26.241.79,2026-03-11,Address,3,3,0.999836,0,0,"CMS, DHA, HRSA, NIH",NaN,NaN,200,600,100,low,[2026-03-11] Severity: low. VT score: 1. Top d...
1378,209.38.105.30,2026-03-10,Address,1,3,0.999945,0,0,"CMS, FDA, HRSA, IHS, OS, VA",Incident:INC9328182,NaN,180,469,477,medium,[2026-03-11] Severity: medium. VT score: 11. T...
1379,223.166.97.90,2026-03-10,Address,2,3,0.999890,0,0,"HRSA, OS",NaN,NaN,180,590,37,low,[2026-03-11] Severity: low. VT score: 0. Top d...
1385,80.94.95.43,2026-03-11,Address,2,3,0.999890,0,0,"OS, VA",Incident:INC9427600,NaN,200,479,594,high,[2026-03-11] Severity: high. VT score: 14. Top...
1387,userguidecollection.com,2026-03-11,Host,4,3,0.999781,0,0,"DHA, HRSA, IHS, NIH",NaN,NaN,180,590,50,low,[2026-03-11] Severity: low. VT score not avail...

In [5]:
# Filter multi-partner, last-24h indicators to VT score >= 10 based on Explanation text
vt_scores = last_24h_multiple_partners['Explanation'].str.extract(r'VT score:\s*(\d+)', expand=False)
vt_scores = pd.to_numeric(vt_scores, errors='coerce')

last_24h_multi_partners_vt10 = last_24h_multiple_partners[vt_scores >= 10]

last_24h_multi_partners_vt10

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
7,103.143.10.79,2026-03-11,Address,12,3,0.999342,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,780,769,676,high,[2026-03-11] Severity: high. VT score: 17. Top...
43,107.9.57.100,2026-03-11,Address,123,3,0.993260,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9282086,NaN,780,769,458,medium,[2026-03-11] Severity: medium. VT score: 10. T...
53,112.31.180.128,2026-03-11,Address,10,3,0.999452,0,0,"CMS, FDA, HRSA, OS",Incident:6755399484001244,NaN,180,399,525,high,[2026-03-11] Severity: high. VT score: 14. Top...
64,121.159.71.249,2026-03-11,Address,179,3,0.990192,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9223440,NaN,640,646,517,high,[2026-03-11] Severity: high. VT score: 13. Top...
69,123.58.196.49,2026-03-11,Address,216,3,0.988164,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9176144,NaN,230,364,528,high,[2026-03-11] Severity: high. VT score: 12. Top...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1273,91.224.92.99,2026-03-11,Address,102,3,0.994411,0,0,"CMS, DHA, FDA, HHS, HRSA, NIH, OS, VA",NaN,NaN,590,531,390,medium,[2026-03-11] Severity: medium. VT score: 12. T...
1276,92.118.39.95,2026-03-11,Address,104,3,0.994301,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9310331,NaN,830,741,521,high,[2026-03-11] Severity: high. VT score: 13. Top...
1373,172.94.9.253,2026-03-11,Address,3,3,0.999836,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS",NaN,NaN,440,599,441,medium,[2026-03-11] Severity: medium. VT score: 11. T...
1378,209.38.105.30,2026-03-10,Address,1,3,0.999945,0,0,"CMS, FDA, HRSA, IHS, OS, VA",Incident:INC9328182,NaN,180,469,477,medium,[2026-03-11] Severity: medium. VT score: 11. T...
1385,80.94.95.43,2026-03-11,Address,2,3,0.999890,0,0,"OS, VA",Incident:INC9427600,NaN,200,479,594,high,[2026-03-11] Severity: high. VT score: 14. Top...

In [6]:
# Keep only high or critical indicators from the VT>=10, multi-partner, last-24h set
high_critical_last_24h = last_24h_multi_partners_vt10[last_24h_multi_partners_vt10['Severity'].isin(['high', 'critical'])]

high_critical_last_24h

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
7,103.143.10.79,2026-03-11,Address,12,3,0.999342,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,780,769,676,high,[2026-03-11] Severity: high. VT score: 17. Top...
53,112.31.180.128,2026-03-11,Address,10,3,0.999452,0,0,"CMS, FDA, HRSA, OS",Incident:6755399484001244,NaN,180,399,525,high,[2026-03-11] Severity: high. VT score: 14. Top...
64,121.159.71.249,2026-03-11,Address,179,3,0.990192,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9223440,NaN,640,646,517,high,[2026-03-11] Severity: high. VT score: 13. Top...
69,123.58.196.49,2026-03-11,Address,216,3,0.988164,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9176144,NaN,230,364,528,high,[2026-03-11] Severity: high. VT score: 12. Top...
70,123.58.207.81,2026-03-11,Address,210,3,0.988493,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9185304,NaN,240,369,596,high,[2026-03-11] Severity: high. VT score: 14. Top...
101,139.19.117.131,2026-03-11,Address,154,3,0.991562,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9267413,NaN,790,721,630,high,[2026-03-11] Severity: high. VT score: 15. Top...
156,147.185.132.58,2026-03-11,Address,73,3,0.996000,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9346798,NaN,430,594,541,high,[2026-03-11] Severity: high. VT score: 11. Top...
201,165.154.10.165,2026-03-11,Address,201,3,0.988986,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9203759,NaN,420,459,620,high,[2026-03-11] Severity: high. VT score: 15. Top...
202,165.154.173.226,2026-03-11,Address,175,3,0.990411,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9235915,NaN,180,339,577,high,[2026-03-11] Severity: high. VT score: 13. Top...
203,165.154.179.204,2026-03-11,Address,257,3,0.985918,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",Incident:INC9118016,NaN,200,322,593,high,[2026-03-11] Severity: high. VT score: 14. Top...
216,167.94.138.124,2026-03-11,Address,115,3,0.993699,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,770,728,518,high,[2026-03-11] Severity: high. VT score: 15. Top...
251,169.150.201.25,2026-03-10,Address,46,5,0.997479,0,0,"CMS, DHA, FDA, HHS, HRSA, NIH, OS",NaN,UNC5537,180,590,639,high,[2026-03-11] Severity: high. VT score: 10. Top...
261,171.25.193.235,2026-03-11,Address,213,5,0.988329,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,"Fancy Bear, Seashell Blizzard, UNC4487",200,351,558,high,[2026-03-11] Severity: high. VT score: 15. Top...
279,176.65.134.22,2026-03-11,Address,50,3,0.997260,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9375302,NaN,830,794,748,high,[2026-03-11] Severity: high. VT score: 21. Top...
288,176.65.148.52,2026-03-11,Address,29,3,0.998411,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,387,505,high,[2026-03-11] Severity: high. VT score: 18. Top...
318,183.224.237.233,2026-03-11,Address,176,3,0.990356,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS",Incident:547382,NaN,790,704,544,high,[2026-03-11] Severity: high. VT score: 12. Top...
319,184.105.247.252,2026-03-11,Address,86,3,0.995288,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9332624,NaN,380,516,572,high,[2026-03-11] Severity: high. VT score: 16. Top...
352,185.226.197.47,2026-03-11,Address,57,3,0.996877,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9366814,NaN,420,647,514,high,[2026-03-11] Severity: high. VT score: 13. Top...
353,185.226.197.49,2026-03-11,Address,57,3,0.996877,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9366814,NaN,420,647,514,high,[2026-03-11] Severity: high. VT score: 13. Top...
485,193.32.162.145,2026-03-11,Address,148,3,0.991890,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9263763,NaN,820,789,583,high,[2026-03-11] Severity: high. VT score: 16. Top...
536,198.235.24.186,2026-03-11,Address,83,3,0.995452,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9341092,NaN,180,416,577,high,[2026-03-11] Severity: high. VT score: 13. Top...
537,198.235.24.193,2026-03-11,Address,85,3,0.995342,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9337221,NaN,180,326,513,high,[2026-03-11] Severity: high. VT score: 10. Top...
538,198.235.24.194,2026-03-11,Address,227,3,0.987562,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,288,504,high,[2026-03-11] Severity: high. VT score: 15. Top...
578,198.235.24.68,2026-03-11,Address,227,3,0.987562,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,550,473,512,high,[2026-03-11] Severity: high. VT score: 15. Top...
614,2.57.121.112,2026-03-11,Address,92,3,0.994959,0,0,"OS, VA",Incident:INC9307742,NaN,720,703,629,high,[2026-03-11] Severity: high. VT score: 16. Top...
616,2.57.121.25,2026-03-11,Address,96,3,0.994740,0,0,"OS, VA",Incident:INC9307742,NaN,740,713,609,high,[2026-03-11] Severity: high. VT score: 15. Top...
634,205.210.31.106,2026-03-11,Address,227,3,0.987562,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9388679,NaN,180,368,512,high,[2026-03-11] Severity: high. VT score: 10. Top...
643,205.210.31.163,2026-03-11,Address,57,3,0.996877,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9366814,NaN,480,518,584,high,[2026-03-11] Severity: high. VT score: 13. Top...
756,207.90.244.13,2026-03-11,Address,85,3,0.995342,0,0,"FDA, HRSA, OS, VA",Incident:INC9337221,NaN,760,658,558,high,[2026-03-11] Severity: high. VT score: 12. Top...
757,207.90.244.3,2026-03-11,Address,57,3,0.996877,0,0,"FDA, HRSA, NIH, OS, VA",Incident:INC9366814,NaN,550,536,599,high,[2026-03-11] Severity: high. VT score: 14. Top...
767,213.209.159.158,2026-03-11,Address,20,3,0.998904,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9411178,NaN,790,774,692,high,[2026-03-11] Severity: high. VT score: 18. Top...
814,37.221.208.71,2026-03-11,Address,129,3,0.992932,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,320,539,515,high,[2026-03-11] Severity: high. VT score: 10. Top...
850,45.148.10.141,2026-03-11,Address,50,4,0.997260,0,0,"HHS, OS",NaN,"Crimson Collective, Scattered Spider, UNC6395",710,681,820,critical,[2026-03-11] Severity: critical. VT score: 15....
904,64.225.74.178,2026-03-11,Address,38,3,0.997918,0,0,"FDA, HRSA, NIH, OS, VA",Incident:INC9391086,NaN,490,624,579,high,[2026-03-11] Severity: high. VT score: 13. Top...
1202,71.6.232.23,2026-03-11,Address,58,3,0.996822,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9332642,NaN,430,558,541,high,[2026-03-11] Severity: high. VT score: 11. Top...
1209,77.90.185.16,2026-03-11,Address,17,3,0.999068,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9411178,NaN,660,673,598,high,[2026-03-11] Severity: high. VT score: 13. Top...
1211,78.128.114.130,2026-03-11,Address,84,3,0.995397,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9332642,NaN,500,593,520,high,[2026-03-11] Severity: high. VT score: 10. Top...
1227,80.94.92.171,2026-03-11,Address,104,3,0.994301,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9303503,NaN,820,789,601,high,[2026-03-11] Severity: high. VT score: 17. Top...
1243,87.236.176.207,2026-03-11,Address,256,3,0.985973,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,300,348,506,high,[2026-03-11] Severity: high. VT score: 15. Top...
1276,92.118.39.95,2026-03-11,Address,104,3,0.994301,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9310331,NaN,830,741,521,high,[2026-03-11] Severity: high. VT score: 13. Top...
1385,80.94.95.43,2026-03-11,Address,2,3,0.999890,0,0,"OS, VA",Incident:INC9427600,NaN,200,479,594,high,[2026-03-11] Severity: high. VT score: 14. Top...

In [15]:
high_critical_last_24h[high_critical_last_24h['Indicator'] == '45.148.10.141']

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
850,45.148.10.141,2026-03-11,Address,50,4,0.99726,0,0,"HHS, OS",NaN,"Crimson Collective, Scattered Spider, UNC6395",710,681,820,critical,[2026-03-11] Severity: critical. VT score: 15....

In [17]:
# Extract VT scores for high/critical last-24h indicators
vt_scores_hc = high_critical_last_24h['Explanation'].str.extract(r'VT score:\s*(\d+)', expand=False)

# VT-based selection only: keep high/critical last-24h indicators with VT score > 15
vt = pd.to_numeric(vt_scores_hc, errors='coerce')
mask_vt = vt >= 15

final_indicators = high_critical_last_24h[mask_vt]
final_indicators

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
7,103.143.10.79,2026-03-11,Address,12,3,0.999342,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,780,769,676,high,[2026-03-11] Severity: high. VT score: 17. Top...
101,139.19.117.131,2026-03-11,Address,154,3,0.991562,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9267413,NaN,790,721,630,high,[2026-03-11] Severity: high. VT score: 15. Top...
201,165.154.10.165,2026-03-11,Address,201,3,0.988986,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9203759,NaN,420,459,620,high,[2026-03-11] Severity: high. VT score: 15. Top...
216,167.94.138.124,2026-03-11,Address,115,3,0.993699,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,770,728,518,high,[2026-03-11] Severity: high. VT score: 15. Top...
261,171.25.193.235,2026-03-11,Address,213,5,0.988329,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,"Fancy Bear, Seashell Blizzard, UNC4487",200,351,558,high,[2026-03-11] Severity: high. VT score: 15. Top...
279,176.65.134.22,2026-03-11,Address,50,3,0.997260,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9375302,NaN,830,794,748,high,[2026-03-11] Severity: high. VT score: 21. Top...
288,176.65.148.52,2026-03-11,Address,29,3,0.998411,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,387,505,high,[2026-03-11] Severity: high. VT score: 18. Top...
319,184.105.247.252,2026-03-11,Address,86,3,0.995288,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9332624,NaN,380,516,572,high,[2026-03-11] Severity: high. VT score: 16. Top...
485,193.32.162.145,2026-03-11,Address,148,3,0.991890,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9263763,NaN,820,789,583,high,[2026-03-11] Severity: high. VT score: 16. Top...
538,198.235.24.194,2026-03-11,Address,227,3,0.987562,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,288,504,high,[2026-03-11] Severity: high. VT score: 15. Top...
578,198.235.24.68,2026-03-11,Address,227,3,0.987562,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,550,473,512,high,[2026-03-11] Severity: high. VT score: 15. Top...
614,2.57.121.112,2026-03-11,Address,92,3,0.994959,0,0,"OS, VA",Incident:INC9307742,NaN,720,703,629,high,[2026-03-11] Severity: high. VT score: 16. Top...
616,2.57.121.25,2026-03-11,Address,96,3,0.994740,0,0,"OS, VA",Incident:INC9307742,NaN,740,713,609,high,[2026-03-11] Severity: high. VT score: 15. Top...
767,213.209.159.158,2026-03-11,Address,20,3,0.998904,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9411178,NaN,790,774,692,high,[2026-03-11] Severity: high. VT score: 18. Top...
850,45.148.10.141,2026-03-11,Address,50,4,0.997260,0,0,"HHS, OS",NaN,"Crimson Collective, Scattered Spider, UNC6395",710,681,820,critical,[2026-03-11] Severity: critical. VT score: 15....
1227,80.94.92.171,2026-03-11,Address,104,3,0.994301,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9303503,NaN,820,789,601,high,[2026-03-11] Severity: high. VT score: 17. Top...
1243,87.236.176.207,2026-03-11,Address,256,3,0.985973,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,300,348,506,high,[2026-03-11] Severity: high. VT score: 15. Top...