In [7]:
import pandas as pd

# Load the Excel file
file_path = r"Z:\HTOC\Data_Analytics\Data\Threat Assessment Scores\Threat_Assessment_Scores.xlsx"
df = pd.read_excel(file_path)

# Display the first few rows
df

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
0,1.234.83.26,2026-02-14,Address,43,3,0.997644,0,0,"CMS, FDA, HRSA, OS",NaN,NaN,180,469,199,low,[2026-03-06] Severity: low. VT score: 3. Top d...
1,101.168.57.163,2026-02-14,Address,2,3,0.999890,0,0,"CMS, FDA, OS, VA",Incident:INC9407577,NaN,180,590,600,high,[2026-03-06] Severity: high. VT score: 11. Top...
2,101.71.130.99,2026-03-03,Address,139,3,0.992384,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",Incident:INC9270850,NaN,540,526,512,high,[2026-03-06] Severity: high. VT score: 11. Top...
3,103.114.96.246,2026-02-26,Address,41,1,0.997753,1,0,"CMS, DHA, NIH, OS, VA",NaN,Mr Hamza Group,180,229,142,low,[2026-03-06] Severity: low. VT score: 2. Top d...
4,103.120.116.162,2026-03-06,Address,38,3,0.997918,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9385644,NaN,720,860,581,high,[2026-03-06] Severity: high. VT score: 6. Top ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260,5.79.110.170,2025-12-23,Address,6,0,0.999671,1,0,"CDC, CMS, HHS",Incident:6755399448003491;Incident:529312,NaN,170,363,45,low,Severity: low. VT score: 0. Top drivers: Incid...
2261,146.70.246.116,2026-01-19,Address,3,0,0.999836,1,0,VA,Incident:6755399478001848,NaN,180,368,41,low,Severity: low. VT score: 0. Top drivers: Incid...
2262,198.199.103.243,2026-01-16,Address,1,0,0.999945,1,0,VA,Incident:6755399478001848,NaN,180,368,41,low,Severity: low. VT score: 0. Top drivers: Incid...
2263,rosesci.com,2026-01-08,Host,17,0,0.999068,0,0,NIH,NaN,NaN,170,351,30,low,Severity: low. Could not pull VT score to calc...
2264,52.87.206.242,2026-01-08,Address,1,1,0.999945,1,0,IHS,NaN,NaN,170,224,27,low,Severity: low. VT score: 0. Top drivers: TC ra...

In [8]:
import pandas as pd

# Ensure Last Observed is datetime
df['Last Observed'] = pd.to_datetime(df['Last Observed'])

# Get last 24 hours relative to latest observation
max_obs = df['Last Observed'].max()
cutoff = max_obs - pd.Timedelta(days=1)
last_24h_from_max = df[df['Last Observed'] >= cutoff]

last_24h_from_max

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
4,103.120.116.162,2026-03-06,Address,38,3,0.997918,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9385644,NaN,720,860,581,high,[2026-03-06] Severity: high. VT score: 6. Top ...
7,103.143.10.79,2026-03-06,Address,7,3,0.999616,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,660,709,679,high,[2026-03-06] Severity: high. VT score: 15. Top...
9,103.172.81.132,2026-03-05,Address,42,0,0.997699,0,0,"CMS, FDA, HHS, NIH, VA",Incident:5629499550000872;Incident:56294995470...,"Emissary Panda, Judgment Panda, UNC6337/STORM-...",180,288,180,low,[2026-03-06] Severity: low. VT score: 2. Top d...
10,103.203.59.0,2026-03-06,Address,272,3,0.985096,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",NaN,NaN,180,368,199,low,[2026-03-06] Severity: low. VT score: 1. Top d...
12,103.216.220.35,2026-03-06,Address,16,5,0.999123,0,0,"DHA, OS",NaN,UNC5537,170,585,199,low,[2026-03-06] Severity: low. VT score: 0. Top d...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1400,yourpensionmeeting.com,2026-03-06,Host,221,3,0.987890,0,0,"CMS, DHA, NIH, VA",Incident:6755399453001053,NaN,180,469,354,medium,[2026-03-06] Severity: medium. VT score not av...
1402,115.79.195.246,2026-03-05,Address,1,4,0.999945,1,0,NIH,Incident:102177,NaN,180,340,199,low,[2026-03-06] Severity: low. VT score: 14. Top ...
1403,141.98.10.96,2026-03-06,Address,4,3,0.999781,0,0,"CMS, DHA, HHS, IHS",NaN,NaN,180,368,377,medium,[2026-03-06] Severity: medium. VT score: 12. T...
1404,167.179.100.144,2026-03-05,Address,1,3,0.999945,1,0,CMS,NaN,Mustang Panda,170,334,89,low,[2026-03-06] Severity: low. VT score: 3. Top d...
1405,79.127.221.47,2026-03-05,Address,1,3,0.999945,0,0,NIH,Event:6755399480000573;Incident:6755399478000278,NaN,170,411,199,low,[2026-03-06] Severity: low. VT score: 2. Top d...

In [9]:
# Filter last 24h results to indicators seen at more than one partner
last_24h_multiple_partners = last_24h_from_max[last_24h_from_max['Partners'].str.contains(',', na=False)]

last_24h_multiple_partners

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
4,103.120.116.162,2026-03-06,Address,38,3,0.997918,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9385644,NaN,720,860,581,high,[2026-03-06] Severity: high. VT score: 6. Top ...
7,103.143.10.79,2026-03-06,Address,7,3,0.999616,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,660,709,679,high,[2026-03-06] Severity: high. VT score: 15. Top...
9,103.172.81.132,2026-03-05,Address,42,0,0.997699,0,0,"CMS, FDA, HHS, NIH, VA",Incident:5629499550000872;Incident:56294995470...,"Emissary Panda, Judgment Panda, UNC6337/STORM-...",180,288,180,low,[2026-03-06] Severity: low. VT score: 2. Top d...
10,103.203.59.0,2026-03-06,Address,272,3,0.985096,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS",NaN,NaN,180,368,199,low,[2026-03-06] Severity: low. VT score: 1. Top d...
12,103.216.220.35,2026-03-06,Address,16,5,0.999123,0,0,"DHA, OS",NaN,UNC5537,170,585,199,low,[2026-03-06] Severity: low. VT score: 0. Top d...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1388,telegram.me,2026-03-06,Host,82,4,0.995507,0,0,"CMS, DHA, IHS, NIH, VA",NaN,Primitive Bear,0,379,339,medium,[2026-03-06] Severity: medium. VT score not av...
1390,testing@test.com,2026-03-05,EmailAddress,11,3,0.999397,1,0,"FDA, HHS, VA",Incident:290848,NaN,180,368,131,low,[2026-03-06] Severity: low. VT score not avail...
1398,www.deepseek.com,2026-03-06,Host,343,3,0.981205,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,469,325,medium,[2026-03-06] Severity: medium. VT score not av...
1400,yourpensionmeeting.com,2026-03-06,Host,221,3,0.987890,0,0,"CMS, DHA, NIH, VA",Incident:6755399453001053,NaN,180,469,354,medium,[2026-03-06] Severity: medium. VT score not av...
1403,141.98.10.96,2026-03-06,Address,4,3,0.999781,0,0,"CMS, DHA, HHS, IHS",NaN,NaN,180,368,377,medium,[2026-03-06] Severity: medium. VT score: 12. T...

In [11]:
# Filter multi-partner, last-24h indicators to VT score >= 10 based on Explanation text
vt_scores = last_24h_multiple_partners['Explanation'].str.extract(r'VT score:\s*(\d+)', expand=False)
vt_scores = pd.to_numeric(vt_scores, errors='coerce')

last_24h_multi_partners_vt10 = last_24h_multiple_partners[vt_scores >= 10]

last_24h_multi_partners_vt10

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
7,103.143.10.79,2026-03-06,Address,7,3,0.999616,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,660,709,679,high,[2026-03-06] Severity: high. VT score: 15. Top...
20,104.152.52.110,2026-03-05,Address,221,3,0.987890,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,320,438,499,medium,[2026-03-06] Severity: medium. VT score: 15. T...
24,104.152.52.237,2026-03-05,Address,221,3,0.987890,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,210,383,499,medium,[2026-03-06] Severity: medium. VT score: 13. T...
45,107.9.57.100,2026-03-06,Address,118,3,0.993534,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, OS, VA",Incident:INC9282086,NaN,780,769,527,high,[2026-03-06] Severity: high. VT score: 10. Top...
48,109.70.100.1,2026-03-05,Address,200,3,0.989041,0,0,"CMS, FDA, HHS, HRSA, IHS, OS, VA",NaN,NaN,500,528,430,medium,[2026-03-06] Severity: medium. VT score: 11. T...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,91.224.92.182,2026-03-05,Address,24,3,0.998685,0,0,"DHA, VA",NaN,NaN,560,659,477,medium,[2026-03-06] Severity: medium. VT score: 10. T...
1306,91.224.92.99,2026-03-05,Address,98,3,0.994630,0,0,"CMS, DHA, HHS, HRSA, NIH, OS, VA",NaN,NaN,590,531,499,medium,[2026-03-06] Severity: medium. VT score: 13. T...
1309,92.118.39.95,2026-03-06,Address,99,3,0.994575,0,0,"CDC, CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9310331,NaN,810,731,560,high,[2026-03-06] Severity: high. VT score: 13. Top...
1322,94.16.115.121,2026-03-06,Address,198,3,0.989151,0,0,"CMS, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,220,517,499,medium,[2026-03-06] Severity: medium. VT score: 13. T...
1403,141.98.10.96,2026-03-06,Address,4,3,0.999781,0,0,"CMS, DHA, HHS, IHS",NaN,NaN,180,368,377,medium,[2026-03-06] Severity: medium. VT score: 12. T...

In [12]:
# Keep only high or critical indicators from the VT>=10, multi-partner, last-24h set
high_critical_last_24h = last_24h_multi_partners_vt10[last_24h_multi_partners_vt10['Severity'].isin(['high', 'critical'])]

high_critical_last_24h

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
7,103.143.10.79,2026-03-06,Address,7,3,0.999616,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,660,709,679,high,[2026-03-06] Severity: high. VT score: 15. Top...
45,107.9.57.100,2026-03-06,Address,118,3,0.993534,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, OS, VA",Incident:INC9282086,NaN,780,769,527,high,[2026-03-06] Severity: high. VT score: 10. Top...
56,112.31.180.128,2026-03-06,Address,5,3,0.999726,0,0,"CMS, FDA, HRSA, OS",Incident:6755399484001244,NaN,180,399,659,high,[2026-03-06] Severity: high. VT score: 14. Top...
105,138.59.233.5,2026-03-06,Address,63,3,0.996548,0,0,"CMS, DHA, FDA, HRSA, NIH, OS, VA",Incident:INC9346798,NaN,490,575,588,high,[2026-03-06] Severity: high. VT score: 15. Top...
106,139.19.117.131,2026-03-06,Address,149,3,0.991836,0,0,"CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",Incident:INC9267413,NaN,800,726,533,high,[2026-03-06] Severity: high. VT score: 15. Top...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1241,77.90.185.235,2026-03-06,Address,83,3,0.995452,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,180,399,502,high,[2026-03-06] Severity: high. VT score: 11. Top...
1242,78.128.114.130,2026-03-06,Address,79,3,0.995671,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9332642,NaN,350,518,563,high,[2026-03-06] Severity: high. VT score: 11. Top...
1255,80.66.83.43,2026-03-06,Address,15,3,0.999178,0,0,"OS, VA",Incident:INC9415113,NaN,350,675,599,high,[2026-03-06] Severity: high. VT score: 12. Top...
1258,80.94.92.171,2026-03-06,Address,99,3,0.994575,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9303503,NaN,820,789,565,high,[2026-03-06] Severity: high. VT score: 17. Top...
1309,92.118.39.95,2026-03-06,Address,99,3,0.994575,0,0,"CDC, CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9310331,NaN,810,731,560,high,[2026-03-06] Severity: high. VT score: 13. Top...

In [13]:
# Keep only rows where CAL Score and HTOC Threat Score differ by no more than 50 points
diff_cal_htoc = (high_critical_last_24h['CAL Score'] - high_critical_last_24h['HTOC Threat Score']).abs()

aligned_scores_last_24h = high_critical_last_24h[diff_cal_htoc <= 50]

aligned_scores_last_24h

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,CAL Score,ThreatConnect Score,HTOC Threat Score,Severity,Explanation
7,103.143.10.79,2026-03-06,Address,7,3,0.999616,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9426960,NaN,660,709,679,high,[2026-03-06] Severity: high. VT score: 15. Top...
221,167.94.138.117,2026-03-06,Address,110,3,0.993973,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,550,618,502,high,[2026-03-06] Severity: high. VT score: 12. Top...
225,167.94.138.124,2026-03-06,Address,110,3,0.993973,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,520,603,510,high,[2026-03-06] Severity: high. VT score: 15. Top...
226,167.94.138.127,2026-03-06,Address,101,3,0.994466,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,460,573,503,high,[2026-03-06] Severity: high. VT score: 11. Top...
240,167.94.138.33,2026-03-06,Address,101,3,0.994466,0,0,"CMS, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,510,634,504,high,[2026-03-06] Severity: high. VT score: 14. Top...
242,167.94.138.36,2026-03-06,Address,110,3,0.993973,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,550,654,500,high,[2026-03-06] Severity: high. VT score: 14. Top...
556,198.235.24.200,2026-03-06,Address,222,3,0.987836,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,560,558,546,high,[2026-03-06] Severity: high. VT score: 12. Top...
557,198.235.24.202,2026-03-06,Address,221,3,0.987890,0,0,"CDC, CMS, DHA, FDA, HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,550,654,543,high,[2026-03-06] Severity: high. VT score: 11. Top...
565,198.235.24.231,2026-03-06,Address,57,3,0.996877,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,570,664,546,high,[2026-03-06] Severity: high. VT score: 11. Top...
628,199.45.154.139,2026-03-06,Address,57,3,0.996877,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,590,604,544,high,[2026-03-06] Severity: high. VT score: 13. Top...
745,206.168.34.210,2026-03-06,Address,100,3,0.994521,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,520,639,503,high,[2026-03-06] Severity: high. VT score: 13. Top...
753,206.168.34.45,2026-03-06,Address,100,3,0.994521,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,480,541,515,high,[2026-03-06] Severity: high. VT score: 15. Top...
759,206.168.34.51,2026-03-06,Address,101,3,0.994466,0,0,"CDC, CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,460,531,502,high,[2026-03-06] Severity: high. VT score: 13. Top...
764,206.168.34.62,2026-03-06,Address,100,3,0.994521,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",NaN,NaN,540,519,502,high,[2026-03-06] Severity: high. VT score: 13. Top...
809,27.29.116.137,2026-03-06,Address,107,3,0.994137,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS",Incident:INC9301875,NaN,590,674,542,high,[2026-03-06] Severity: high. VT score: 11. Top...
1233,71.6.232.23,2026-03-05,Address,55,3,0.996986,0,0,"CMS, DHA, FDA, HRSA, IHS, NIH, OS, VA",Incident:INC9332642,NaN,590,638,572,high,[2026-03-06] Severity: high. VT score: 12. Top...

In [ ]:
# Apply CAL vs HTOC <= 50 rule, except allow VT score > 15
vt_scores_hc = high_critical_last_24h['Explanation'].str.extract(r'VT score:\s*(\d+)', expand=False)
vt_scores_hc = pd.to_numeric(vt_scores_hc, errors='coerce')

diff_cal_htoc_hc = (high_critical_last_24h['CAL Score'] - high_critical_last_24h['HTOC Threat Score']).abs()

final_indicators = high_critical_last_24h[(diff_cal_htoc_hc <= 50) | (vt_scores_hc > 15)]

final_indicators