In [25]:
import sys
import os
import urllib3
from configparser import ConfigParser

# Add your local ThreatConnect SDK to path
sys.path.append(r"Z:\HTOC\Data_Analytics\threatconnect")
from ThreatConnect import ThreatConnect
from RequestObject import RequestObject
from Owners import Owners

# Add your project repo to path
project_root = r"H:\HTOC\scripts\Data Movement\ThrearConnect-api-pull"
if project_root not in sys.path:
    sys.path.append(project_root)

from utils.config_loader import load_config

# Load API config
config_path = os.path.join(project_root, "utils", "config.json")
try:
    api_secret_key, api_access_id, api_base_url, api_default_org = load_config(config_path)
    display(f"Loaded config from: {config_path}")
    display(f"Base URL: {api_base_url}")
    display(f"Access ID: {api_access_id}")
    display(f"Default Org: {api_default_org}")
except Exception as e:
    display(f"[ERROR] Failed to load configuration: {e}")
    sys.exit(1)

# Disable SSL verification warnings (use cautiously)
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
verify_ssl = False

# Initialize ThreatConnect session
try:
    tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)
    display("ThreatConnect initialized.")
except Exception as e:
    display(f"[ERROR] Failed to initialize ThreatConnect: {e}")
    sys.exit(1)

# Define the owner (organization scope)
owner = 'HTOC Org'

# Create a request object to fetch indicators (or other data)
try:
    ro = RequestObject()
    ro.set_http_method('GET')
    ro.set_owner(owner)
    ro.set_owner_allowed(True)
    # ro.set_resource_pagination(True)  # Uncomment if needed
    display("RequestObject successfully created.")
except Exception as e:
    display(f"[ERROR] Failed to initialize RequestObject: {e}")
    sys.exit(1)

'Loaded config from: H:\\HTOC\\scripts\\Data Movement\\ThrearConnect-api-pull\\utils\\config.json'

'Base URL: https://hvs.threatconnect.com/api'

'Access ID: 09783848890162390382'

'Default Org: HTOC Org'

'ThreatConnect initialized.'

'RequestObject successfully created.'

In [26]:
import pandas as pd
from datetime import datetime, timedelta
import pytz
import urllib.parse

# Configuration for ThreatConnect indicator query
QUERY_LOOKBACK_HOURS = 48  # rolling wall-clock window in UTC (not calendar midnights)
INDICATOR_TYPE_NAMES = [
    "Address", "EmailAddress", "File", "Host", "URL", "ASN", "CIDR",
    "Email Subject", "Hashtag", "Mutex", "Registry Key", "User Agent",
]
OWNER_NAMES = [
    'HTOC Org',
    'CISA Federal Feed',
    'CMS_CTI',
    'Crowdstrike Falcon Intelligence',
    'DHS CISCP',
    'Intel471',
    'Mandiant Advantage Threat Intelligence',
    'VA_TIP Data',
]
RESULT_PAGE_SIZE = 500  # keep this smaller; same fields, just paged

# Single cutoff instant for TQL, observed_src filter, and workbook filter
_now_utc = datetime.now(pytz.UTC)
_last_observed_cutoff_dt = _now_utc - timedelta(hours=QUERY_LOOKBACK_HOURS)
start = _last_observed_cutoff_dt.strftime("%Y-%m-%dT%H:%M:%SZ")
LAST_OBSERVED_CUTOFF_TS = pd.Timestamp(_last_observed_cutoff_dt)

type_names = INDICATOR_TYPE_NAMES
type_name_condition = ", ".join([f'"{t}"' for t in type_names])

list_of_owners = OWNER_NAMES

# Build owner IN (...) clause
owner_condition = ", ".join([f'"{o}"' for o in list_of_owners])

tql_raw = (
    f'ownerName IN ({owner_condition}) AND '
    f'typeName IN ({type_name_condition}) AND '
    f'lastObserved >= "{start}"'
)

tql_encoded = urllib.parse.quote(tql_raw)

final_results = []

# Query indicators (paginate so you don't 502 with heavy fields)
# Create a NEW RequestObject WITHOUT owner restriction to query across all owners
ro_multi = RequestObject()
ro_multi.set_http_method('GET')

result_start = 0
result_limit = RESULT_PAGE_SIZE

while True:
    try:
        # NOTE: same fields list you requested (tags,observations,associatedGroups,falsePositives,threatAssess)
        # Only change here is removing the trailing comma after threatAssess which can break parsing.
        ro_multi.set_request_uri(
            f'/v3/indicators?tql={tql_encoded}'
            f'&fields=tags,observations,associatedGroups,falsePositives,threatAssess'
            f'&resultStart={result_start}&resultLimit={result_limit}'
        )

        response = tc.api_request(ro_multi)

        ct = response.headers.get('content-type', '')
        if not ct.startswith('application/json'):
            raise RuntimeError(f"Non-JSON response ({ct}): {response.content[:200]}")

        results = response.json()
        data_items = results.get('data', []) or []

        # stop when no more results
        if not data_items:
            break

        final_results.append(results)
        result_start += result_limit

    except Exception as e:
        display(f"Failed to query indicators (start={result_start}): {e}")
        break

# Normalize results
normalized_data = []
for result in final_results:
    data_items = result.get('data', [])
    if not data_items:
        display("No data returned in API response:", result)
    for item in data_items:
        if isinstance(item, dict) and 'summary' in item:
            normalized_data.append(item)

if normalized_data:
    observed_src = pd.json_normalize(normalized_data)
    observed_src['indicator'] = observed_src['summary'].astype(str).str.split().str[0].str.strip()
    observed_src['lastObserved'] = pd.to_datetime(observed_src['lastObserved'], utc=True, errors='coerce')
    observed_src = observed_src[observed_src["lastObserved"] >= LAST_OBSERVED_CUTOFF_TS]
    
    # Create a 'sources' column by aggregating ownerName values per indicator
    sources_per_indicator = (
        observed_src.groupby('indicator')['ownerName']
        .apply(lambda x: ', '.join(sorted(set(x))))
        .reset_index()
        .rename(columns={'ownerName': 'sources'})
    )

    # Merge sources back into observed_src
    observed_src = observed_src.merge(sources_per_indicator, on='indicator', how='left')
    # Filter to keep only records where ownerName is 'HTOC Org'
    observed_src = observed_src[observed_src['ownerName'] == 'HTOC Org'].copy()
    # Keep rows where top-level rating >= 3 OR coalesced threatAssessRating >= 3, and
    # (coalesced TA confidence >= 50 OR top-level confidence >= 50).
    # Coalesce flat vs nested threatAssess columns; keep top-level rating/confidence separate for OR.
    _rating_cols = ("threatAssessRating", "threatAssess.threatAssessRating", "rating")
    _confidence_cols = ("threatAssessConfidence", "threatAssess.threatAssessConfidence")

    def _first_non_null_numeric(df, ordered_cols):
        present = [c for c in ordered_cols if c in df.columns]
        if not present:
            return None
        out = pd.to_numeric(df[present[0]], errors="coerce")
        for c in present[1:]:
            s = pd.to_numeric(df[c], errors="coerce")
            out = out.mask(out.isna(), s)
        return out

    _tar = _first_non_null_numeric(observed_src, _rating_cols)
    _tc = _first_non_null_numeric(observed_src, _confidence_cols)
    if _tar is None or _tc is None:
        raise KeyError(
            f"Could not resolve Threat Assess columns. Tried rating={_rating_cols}, "
            f"confidence={_confidence_cols}. Columns: {list(observed_src.columns)}"
        )
    if "rating" in observed_src.columns:
        _r = pd.to_numeric(observed_src["rating"], errors="coerce")
    else:
        _r = pd.Series(float("nan"), index=observed_src.index, dtype=float)

    if "confidence" in observed_src.columns:
        _c = pd.to_numeric(observed_src["confidence"], errors="coerce")
    else:
        _c = pd.Series(float("nan"), index=observed_src.index, dtype=float)

    _pre_ta = len(observed_src)
    # Use >= 50 so a boundary value of 50.0 is included (strict > 50 dropped those rows).
    _pass_rating_band = (_tar >= 3) | (_r >= 3)
    _pass_confidence_band = (_tc >= 50) | (_c >= 50)
    observed_src = observed_src[_pass_rating_band & _pass_confidence_band].copy()
    display(
        f"Threat assess filter ((rating>=3 OR threatAssessRating>=3), confidence>=50) coalescing {_rating_cols} / {_confidence_cols}: "
        f"{_pre_ta} -> {len(observed_src)} rows."
    )
else:
    display("No valid indicator data found.")
    observed_src = pd.DataFrame()

display(observed_src)

"Threat assess filter ((rating>=3 OR threatAssessRating>=3), confidence>=50) coalescing ('threatAssessRating', 'threatAssess.threatAssessRating', 'rating') / ('threatAssessConfidence', 'threatAssess.threatAssessConfidence'): 1107 -> 927 rows."

,id,dateAdded,ownerId,ownerName,webLink,type,lastModified,confidence,threatAssessRating,threatAssessConfidence,...,rating,description,address,associatedGroups.data,hostName,dnsActive,whoisActive,text,indicator,sources
1,2695969,2020-08-17T17:15:22Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,EmailAddress,2026-07-06T11:05:14Z,50.0,4.0,50.00,...,4.0,ACD R&F processed a malspam campaign with a St...,chastity@coalcountryhealth.com,"[{'id': 128797, 'dateAdded': '2021-12-06T13:45...",NaN,NaN,NaN,NaN,chastity@coalcountryhealth.com,HTOC Org
2,14636698790074015,2026-06-02T06:43:18Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-07-06T10:55:12Z,93.0,2.5,88.25,...,3.0,NaN,NaN,"[{'id': 22517998136854987, 'dateAdded': '2026-...",NaN,NaN,NaN,NaN,185.93.89.147,"CMS_CTI, HTOC Org"
6,22517998138009930,2026-06-16T01:34:32Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-07-06T10:45:14Z,78.0,3.0,78.00,...,3.0,nih_soar - IRT-68367,NaN,NaN,NaN,NaN,NaN,NaN,31.57.184.20,HTOC Org
7,15762598695819650,2026-06-01T13:12:20Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-07-06T10:45:14Z,93.0,1.5,93.50,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.14.254.114,"CMS_CTI, HTOC Org"
8,15762598695819619,2026-06-01T13:01:47Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-07-06T10:45:14Z,90.0,1.5,92.00,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.14.254.65,"CMS_CTI, HTOC Org"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,14636698790023471,2026-05-29T03:51:50Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-06-29T07:01:49Z,92.0,1.5,93.00,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.14.254.91,"CMS_CTI, HTOC Org"
2055,21392098231023931,2026-06-11T16:45:11Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-06-29T07:01:38Z,79.0,3.0,79.00,...,3.0,nih_soar - 68237,NaN,NaN,NaN,NaN,NaN,NaN,192.42.116.63,HTOC Org
2056,15762598695819651,2026-06-01T13:12:36Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-06-29T07:00:54Z,92.0,1.5,93.00,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.14.254.115,"CMS_CTI, HTOC Org"
2057,6755399501091095,2026-03-26T11:44:40Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-06-29T07:00:43Z,74.0,1.0,69.67,...,3.0,INC9464932,NaN,NaN,NaN,NaN,NaN,NaN,87.236.176.173,HTOC Org
2058,14636698790023508,2026-05-29T04:14:50Z,9,HTOC Org,https://hvs.threatconnect.com/#/details/indica...,Address,2026-06-29T07:00:32Z,89.0,1.5,90.50,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.5.169.131,"CMS_CTI, HTOC Org"

In [27]:
observed_src[observed_src['indicator'] == '174.128.251.99']

Empty DataFrame
Columns: [id, dateAdded, ownerId, ownerName, webLink, type, lastModified, confidence, threatAssessRating, threatAssessConfidence, threatAssessScore, threatAssessScoreObserved, threatAssessScoreFalsePositive, calScore, source, summary, observations, lastObserved, falsePositives, falsePositiveReportedByUser, privateFlag, active, activeLocked, ip, legacyLink, tags.data, rating, description, address, associatedGroups.data, hostName, dnsActive, whoisActive, text, indicator, sources]
Index: []

[0 rows x 36 columns]

In [28]:
import pandas as pd
import ast
from datetime import datetime, timedelta
import pytz

# Load the Excel file
file_path = r"Z:\HTOC\Data_Analytics\Data\Threat Assessment Scores\Threat_Assessment_Scores.xlsx"
df = pd.read_excel(file_path)


# Keep only indicators that are also in observed_src
_indicator_col = next((c for c in ["indicator", "Indicator", "INDICATOR"] if c in df.columns), None)
if _indicator_col is None:
    raise KeyError(f"Could not find indicator column in df. Columns: {list(df.columns)}")

_observed_indicators = set(observed_src["indicator"].dropna().astype(str))
df = df[df[_indicator_col].astype(str).isin(_observed_indicators)].copy()

# Last Observed column: values come only from observed_src (ThreatConnect), not the workbook
_last_observed_col = next(
    (
        c
        for c in [
            "Last Observed",
            "lastObserved",
            "LastObserved",
            "last_observed",
            "LAST OBSERVED",
        ]
        if c in df.columns
    ),
    None,
)
if _last_observed_col is None:
    raise KeyError(f"Could not find 'Last Observed' column in df. Columns: {list(df.columns)}")

_assoc_groups_src_col = "associatedGroups.data"
_assoc_groups_target_col = "Associated Groups"
if _assoc_groups_src_col not in observed_src.columns:
    raise KeyError(
        f"Could not find '{_assoc_groups_src_col}' column in observed_src. Columns: {list(observed_src.columns)}"
    )


def _extract_group_ids(value):
    # Handle scalar nulls safely; avoid pd.isna on list-like values.
    if value is None:
        return pd.NA

    parsed = value
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return pd.NA
        try:
            parsed = ast.literal_eval(text)
        except (ValueError, SyntaxError):
            return text
    elif isinstance(value, float) and pd.isna(value):
        return pd.NA

    if isinstance(parsed, dict):
        gid = parsed.get("id")
        return f"Group Id: {gid}" if gid is not None else pd.NA

    if isinstance(parsed, list):
        ids = []
        for item in parsed:
            if isinstance(item, dict) and item.get("id") is not None:
                ids.append(f"Group Id: {item.get('id')}")
        return ", ".join(ids) if ids else pd.NA

    return pd.NA


_observed_latest = (
    observed_src.dropna(subset=["indicator"])
    .assign(
        indicator=lambda d: d["indicator"].astype(str),
        lastObserved=lambda d: pd.to_datetime(d["lastObserved"], utc=True, errors="coerce"),
    )
    .sort_values("lastObserved")
    .drop_duplicates(subset=["indicator"], keep="last")
)

_last_obs_by_indicator = _observed_latest.set_index("indicator")["lastObserved"]
_assoc_groups_by_indicator = _observed_latest.set_index("indicator")[_assoc_groups_src_col].map(_extract_group_ids)

# Last Observed: only from ThreatConnect (observed_src); do not fall back to Excel dates
_df_ind = df[_indicator_col].astype(str)
df[_last_observed_col] = pd.to_datetime(_df_ind.map(_last_obs_by_indicator), utc=True, errors="coerce")
_qh = QUERY_LOOKBACK_HOURS if "QUERY_LOOKBACK_HOURS" in globals() else 48
_last_obs_cutoff = (
    LAST_OBSERVED_CUTOFF_TS
    if "LAST_OBSERVED_CUTOFF_TS" in globals()
    else pd.Timestamp(datetime.now(pytz.UTC) - timedelta(hours=_qh), tz="UTC")
)
_pre_lo = len(df)
df = df[df[_last_observed_col].notna() & (df[_last_observed_col] >= _last_obs_cutoff)].copy()
display(
    f"Last Observed filter (ThreatConnect only, >= {_last_obs_cutoff}): {_pre_lo} -> {len(df)} rows."
)

_df_ind = df[_indicator_col].astype(str)

# Add associatedGroups.data ids from observed_src by indicator, stored as 'Associated Groups'
if _assoc_groups_target_col in df.columns:
    df[_assoc_groups_target_col] = _df_ind.map(_assoc_groups_by_indicator).combine_first(df[_assoc_groups_target_col])
else:
    df[_assoc_groups_target_col] = _df_ind.map(_assoc_groups_by_indicator)

df

'Last Observed filter (ThreatConnect only, >= 2026-07-04 11:14:25.935619+00:00): 927 -> 927 rows.'

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,Tagging Boost,Tagging Boost Reason,CAL Score,ThreatConnect Score,PRISM Score,Severity,Explanation,Associated Groups
1,1.192.18.4,2026-07-05 00:00:00+00:00,Address,21,3,0.998849,0,0,"CMS, FDA, HRSA, NIH, OS",NaN,NaN,0.0,NaN,190,331,228,medium,[2026-07-06] Severity: medium. VT score: 10. C...,<NA>
4,102.222.90.244,2026-07-05 00:00:00+00:00,Address,10,3,0.999452,0,0,"DHA, VA",NaN,NaN,0.0,NaN,180,469,140,low,[2026-07-06] Severity: low. VT score: 1. Conte...,<NA>
7,102.88.55.114,2026-07-05 00:00:00+00:00,Address,6,3,0.999671,0,0,"DHA, VA",NaN,NaN,0.0,NaN,180,469,140,low,[2026-07-06] Severity: low. VT score: 1. Conte...,<NA>
8,102.88.55.197,2026-07-06 00:00:00+00:00,Address,6,3,0.999671,0,0,"DHA, VA",NaN,NaN,0.0,NaN,180,469,140,low,[2026-07-06] Severity: low. VT score: 1. Conte...,<NA>
9,102.89.82.4,2026-07-05 00:00:00+00:00,Address,8,3,0.999562,0,0,"DHA, VA",NaN,NaN,0.0,NaN,180,469,87,low,[2026-07-06] Severity: low. VT score: 0. Conte...,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1851,92.118.39.71,2026-07-06 00:00:00+00:00,Address,6,3,0.999671,0,0,"CDC, HRSA, IHS, NIH, OS, VA",Incident:INC9604450;Incident:INC9604362,NaN,0.0,NaN,910,834,203,medium,[2026-07-06] Severity: medium. VT score: 9. Co...,<NA>
1853,93.88.156.34,2026-07-06 00:00:00+00:00,Address,4,3,0.999781,0,0,VA,NaN,NaN,0.0,NaN,180,469,37,low,[2026-07-06] Severity: low. VT score: 0. Conte...,<NA>
1857,mixpanel.com,2026-07-06 00:00:00+00:00,Host,8,4,0.999562,0,0,"CMS, NIH",Event:21392098237001276,NaN,0.0,NaN,0,379,139,low,[2026-07-06] Severity: low. VT score: 0. Conte...,Group Id: 21392098237001276
1858,newdaydentistry.org,2026-07-06 00:00:00+00:00,Host,5,5,0.999726,0,0,NIH,NaN,NaN,0.0,NaN,180,590,31,low,[2026-07-06] Severity: low. VT score not avail...,<NA>
1859,pacificmunicipal.com,2026-07-05 00:00:00+00:00,Host,4,5,0.999781,0,0,NIH,NaN,NaN,0.0,NaN,180,590,31,low,[2026-07-06] Severity: low. VT score not avail...,<NA>

In [29]:
import os
import pandas as pd
from datetime import datetime, timedelta

# Base file path with placeholder for date
base_path = r"Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d{date}.csv"
#base_path = r"C:\Users\jaskew\Documents\project_repository\data\raw\ObservationDataFiles\htoc_opdiv_obs_d{date}.csv"
date_format = "%Y%m%d"

def get_file_paths(base_path, days=3):
    """ Generate file paths for the last `days` days using list comprehension. """
    today = datetime.utcnow()
    dates_to_pull = [(today - timedelta(days=i)).strftime(date_format) for i in range(days)]
    
    # Construct file paths
    file_paths = [base_path.format(date=dt) for dt in dates_to_pull]
    
    # Filter for existing files
    existing_files = [file_path for file_path in file_paths if os.path.exists(file_path)]
    
    if not existing_files:
        print("No files found for the specified date range.")
    else:
        print(f"Files to be loaded: {existing_files}")
    
    return existing_files

def load_observed_data(file_paths):
    """ Load and concatenate observed data from multiple files. """
    data_frames = []

    for file_path in file_paths:
        try:
            df = pd.read_csv(file_path)
            data_frames.append(df)
        except Exception as e:
            print(f"Error reading file {file_path}: {e}")
    
    # Concatenate data
    if data_frames:
        observed_data_df = pd.concat(data_frames, ignore_index=True)
        print(f"Loaded data from {len(data_frames)} files.")
    else:
        observed_data_df = pd.DataFrame()

    return observed_data_df

# Example Usage:
# Fetch file paths for the last 3 days
file_paths = get_file_paths(base_path, days=2)

# Load observed data
observed_data_df = load_observed_data(file_paths)

Files to be loaded: ['Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20260706.csv', 'Z:/HTOC/Data_Analytics/Data/OpDiv_Observations/htoc_opdiv_obs_d20260705.csv']
Loaded data from 2 files.

C:\Users\jaskew\AppData\Local\Temp\ipykernel_23648\1484081131.py:12: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  today = datetime.utcnow()

In [30]:
observed_data_df[observed_data_df['indicator'] == '174.128.251.99']

Empty DataFrame
Columns: [indicator, API_UserName, obs_date, OpDiv, indicator_key, observations, curr_date]
Index: []

In [31]:
# Keep only indicators that are present in observed_data_df and seen by 2+ OpDiv partners
_indicator_col_df = next((c for c in ["indicator", "Indicator", "INDICATOR"] if c in df.columns), None)
_indicator_col_obs = next((c for c in ["indicator", "Indicator", "INDICATOR"] if c in observed_data_df.columns), None)
_opdiv_col = next((c for c in ["OpDiv", "opdiv", "OPDIV"] if c in observed_data_df.columns), None)

if _indicator_col_df is None:
    raise KeyError(f"Could not find indicator column in df. Columns: {list(df.columns)}")
if _indicator_col_obs is None:
    raise KeyError(f"Could not find indicator column in observed_data_df. Columns: {list(observed_data_df.columns)}")
if _opdiv_col is None:
    raise KeyError(f"Could not find OpDiv column in observed_data_df. Columns: {list(observed_data_df.columns)}")

obs = observed_data_df.dropna(subset=[_indicator_col_obs, _opdiv_col]).copy()
obs[_indicator_col_obs] = obs[_indicator_col_obs].astype(str).str.strip()
obs[_opdiv_col] = obs[_opdiv_col].astype(str).str.strip()

partners_by_indicator = (
    obs.groupby(_indicator_col_obs)[_opdiv_col]
    .apply(lambda s: sorted(set(x for x in s if x)))
)

eligible_partners = partners_by_indicator[partners_by_indicator.str.len() >= 2]
opdiv_map = eligible_partners.apply(lambda vals: ", ".join(vals))

last_24h_multiple_partners = df[
    df[_indicator_col_df].astype(str).str.strip().isin(eligible_partners.index)
].copy()
last_24h_multiple_partners["OpDiv"] = (
    last_24h_multiple_partners[_indicator_col_df].astype(str).str.strip().map(opdiv_map)
)
last_24h_multiple_partners["Partners"] = last_24h_multiple_partners["OpDiv"]

last_24h_multiple_partners

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,Tagging Boost,Tagging Boost Reason,CAL Score,ThreatConnect Score,PRISM Score,Severity,Explanation,Associated Groups,OpDiv
11,103.120.116.162,2026-07-06 00:00:00+00:00,Address,160,3,0.991233,0,0,"FDA, HRSA, OS, VA",Incident:INC9385644,NaN,0.0,NaN,900,829,235,medium,[2026-07-06] Severity: medium. VT score: 10. C...,<NA>,"FDA, HRSA, OS, VA"
112,104.234.140.162,2026-07-06 00:00:00+00:00,Address,26,3,0.998575,0,0,"DHA, VA",NaN,NaN,0.0,NaN,180,433,87,low,[2026-07-06] Severity: low. VT score: 0. Conte...,<NA>,"DHA, VA"
113,104.234.140.166,2026-07-06 00:00:00+00:00,Address,25,3,0.998630,0,0,"DHA, VA",NaN,NaN,0.0,NaN,180,469,93,low,[2026-07-06] Severity: low. VT score: 0. Conte...,<NA>,"DHA, VA"
123,104.41.137.249,2026-07-06 00:00:00+00:00,Address,88,3,0.995178,0,0,"FDA, HRSA, OS, VA",Incident:INC9486336;Incident:INC9486332,NaN,0.0,NaN,40,520,122,low,[2026-07-06] Severity: low. VT score: 3. Conte...,<NA>,"FDA, HRSA, OS, VA"
124,104.41.143.27,2026-07-06 00:00:00+00:00,Address,93,3,0.994904,0,0,"FDA, HRSA, OS, VA",Incident:INC9421495,NaN,0.0,NaN,100,550,106,low,[2026-07-06] Severity: low. VT score: 2. Conte...,<NA>,"FDA, HRSA, OS, VA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1826,43.228.157.9,2026-07-06 00:00:00+00:00,Address,6,3,0.999671,0,0,"HRSA, IHS, NIH, OS, VA",Incident:INC9604450;Incident:INC9604362,NaN,0.0,NaN,180,469,51,low,[2026-07-06] Severity: low. VT score: 3. Conte...,<NA>,"HRSA, IHS, NIH, OS, VA"
1842,62.60.130.148,2026-07-06 00:00:00+00:00,Address,7,3,0.999616,0,0,"CDC, CMS, HRSA, IHS, NIH, OS, VA",NaN,NaN,0.0,NaN,180,590,12,low,[2026-07-06] Severity: low. VT score: 10. Cont...,<NA>,"CDC, CMS, HRSA, IHS, NIH, OS, VA"
1844,80.94.92.234,2026-07-06 00:00:00+00:00,Address,6,3,0.999671,0,0,"HRSA, IHS, NIH, OS, VA",Incident:INC9604450;Incident:INC9604362,NaN,0.0,NaN,910,955,271,medium,[2026-07-06] Severity: medium. VT score: 13. C...,<NA>,"HRSA, IHS, NIH, OS, VA"
1848,91.224.92.19,2026-07-06 00:00:00+00:00,Address,7,3,0.999616,0,0,"NIH, OS, VA",NaN,NaN,0.0,NaN,180,368,201,medium,[2026-07-06] Severity: medium. VT score: 2. Co...,<NA>,"NIH, OS, VA"
1851,92.118.39.71,2026-07-06 00:00:00+00:00,Address,6,3,0.999671,0,0,"CDC, HRSA, NIH, OS, VA",Incident:INC9604450;Incident:INC9604362,NaN,0.0,NaN,910,834,203,medium,[2026-07-06] Severity: medium. VT score: 9. Co...,<NA>,"CDC, HRSA, NIH, OS, VA"

In [32]:
# Filter multi-partner, last-24h indicators to VT score >= 10 based on Explanation text
vt_scores = last_24h_multiple_partners['Explanation'].str.extract(r'VT score:\s*(\d+)', expand=False)
vt_scores = pd.to_numeric(vt_scores, errors='coerce')

last_24h_multi_partners_vt15 = last_24h_multiple_partners[vt_scores >= 2]

last_24h_multi_partners_vt15

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,Tagging Boost,Tagging Boost Reason,CAL Score,ThreatConnect Score,PRISM Score,Severity,Explanation,Associated Groups,OpDiv
11,103.120.116.162,2026-07-06 00:00:00+00:00,Address,160,3,0.991233,0,0,"FDA, HRSA, OS, VA",Incident:INC9385644,NaN,0.0,NaN,900,829,235,medium,[2026-07-06] Severity: medium. VT score: 10. C...,<NA>,"FDA, HRSA, OS, VA"
123,104.41.137.249,2026-07-06 00:00:00+00:00,Address,88,3,0.995178,0,0,"FDA, HRSA, OS, VA",Incident:INC9486336;Incident:INC9486332,NaN,0.0,NaN,40,520,122,low,[2026-07-06] Severity: low. VT score: 3. Conte...,<NA>,"FDA, HRSA, OS, VA"
124,104.41.143.27,2026-07-06 00:00:00+00:00,Address,93,3,0.994904,0,0,"FDA, HRSA, OS, VA",Incident:INC9421495,NaN,0.0,NaN,100,550,106,low,[2026-07-06] Severity: low. VT score: 2. Conte...,<NA>,"FDA, HRSA, OS, VA"
126,106.15.238.36,2026-07-06 00:00:00+00:00,Address,91,3,0.995014,0,0,"FDA, HHS, HRSA, OS",Incident:INC9480324,NaN,0.0,NaN,520,538,110,low,[2026-07-06] Severity: low. VT score: 11. Cont...,<NA>,"FDA, HHS, HRSA, OS"
133,107.189.19.172,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"HRSA, IHS, NIH, OS, VA",NaN,NaN,0.0,NaN,180,469,191,low,[2026-07-06] Severity: low. VT score: 2. Conte...,<NA>,"HRSA, IHS, NIH, OS, VA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1826,43.228.157.9,2026-07-06 00:00:00+00:00,Address,6,3,0.999671,0,0,"HRSA, IHS, NIH, OS, VA",Incident:INC9604450;Incident:INC9604362,NaN,0.0,NaN,180,469,51,low,[2026-07-06] Severity: low. VT score: 3. Conte...,<NA>,"HRSA, IHS, NIH, OS, VA"
1842,62.60.130.148,2026-07-06 00:00:00+00:00,Address,7,3,0.999616,0,0,"CDC, CMS, HRSA, IHS, NIH, OS, VA",NaN,NaN,0.0,NaN,180,590,12,low,[2026-07-06] Severity: low. VT score: 10. Cont...,<NA>,"CDC, CMS, HRSA, IHS, NIH, OS, VA"
1844,80.94.92.234,2026-07-06 00:00:00+00:00,Address,6,3,0.999671,0,0,"HRSA, IHS, NIH, OS, VA",Incident:INC9604450;Incident:INC9604362,NaN,0.0,NaN,910,955,271,medium,[2026-07-06] Severity: medium. VT score: 13. C...,<NA>,"HRSA, IHS, NIH, OS, VA"
1848,91.224.92.19,2026-07-06 00:00:00+00:00,Address,7,3,0.999616,0,0,"NIH, OS, VA",NaN,NaN,0.0,NaN,180,368,201,medium,[2026-07-06] Severity: medium. VT score: 2. Co...,<NA>,"NIH, OS, VA"
1851,92.118.39.71,2026-07-06 00:00:00+00:00,Address,6,3,0.999671,0,0,"CDC, HRSA, NIH, OS, VA",Incident:INC9604450;Incident:INC9604362,NaN,0.0,NaN,910,834,203,medium,[2026-07-06] Severity: medium. VT score: 9. Co...,<NA>,"CDC, HRSA, NIH, OS, VA"

In [33]:
# Keep only high or critical indicators from the VT>=10, multi-partner, last-24h set
final_indicators = last_24h_multi_partners_vt15[last_24h_multi_partners_vt15['Severity'].isin(['high', 'critical'])]

final_indicators

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,Threat Actor,Tagging Boost,Tagging Boost Reason,CAL Score,ThreatConnect Score,PRISM Score,Severity,Explanation,Associated Groups,OpDiv
420,179.1.195.163,2026-07-06 00:00:00+00:00,Address,24,5,0.998685,0,0,"HRSA, OS",NaN,"Diamond Sleet, Emerald Sleet, Famous Chollima,...",1.0,pair:north korea+diamond sleet,180,590,578,high,[2026-07-06] Severity: high. VT score: 2. Cont...,"Group Id: 6755399483006350, Group Id: 56294995...","HRSA, OS"
719,198.54.117.242,2026-07-06 00:00:00+00:00,Address,131,5,0.992822,1,0,"NIH, VA",NaN,"Diamond Sleet, Mustang Panda, Onyx Sleet, Rich...",1.0,pair:russia+fsb,180,343,578,high,[2026-07-06] Severity: high. VT score: 7. Cont...,"Group Id: 6755399482040879, Group Id: 67553994...","NIH, VA"
833,31.14.254.16,2026-07-06 00:00:00+00:00,Address,39,3,0.997863,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,0.0,NaN,480,619,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,"HHS, HRSA, IHS, NIH, OS, VA"
838,31.14.254.20,2026-07-06 00:00:00+00:00,Address,37,3,0.997973,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,0.0,NaN,480,619,500,high,[2026-07-06] Severity: high. VT score: 13. Con...,<NA>,"HHS, HRSA, IHS, NIH, OS, VA"
856,31.14.254.37,2026-07-06 00:00:00+00:00,Address,32,3,0.998247,0,0,"NIH, OS, VA",NaN,NaN,0.0,NaN,180,469,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,"NIH, OS, VA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,69.5.169.90,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,0.0,NaN,360,559,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,"HHS, HRSA, IHS, NIH, OS, VA"
1516,69.5.169.91,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,0.0,NaN,480,619,500,high,[2026-07-06] Severity: high. VT score: 13. Con...,<NA>,"HHS, HRSA, IHS, NIH, OS, VA"
1517,69.5.169.92,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,0.0,NaN,480,619,500,high,[2026-07-06] Severity: high. VT score: 13. Con...,<NA>,"HHS, HRSA, IHS, NIH, OS, VA"
1519,69.5.169.94,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"OS, VA",NaN,NaN,0.0,NaN,250,504,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,"OS, VA"
1521,69.5.169.96,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,NaN,0.0,NaN,640,699,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,"HHS, HRSA, IHS, NIH, OS, VA"

In [34]:
import pandas as pd

# Load external tags data
tags_path = r"Z:\HTOC\Data_Analytics\Data\Observed_Tags\htoc_observed_indicator_tags.csv"
tags_df = pd.read_csv(tags_path)

# The indicator column in the tags CSV could be e.g. 'Indicator' or 'indicator'
tags_indicator_col = None
for col in tags_df.columns:
    if str(col).lower() == 'indicator':
        tags_indicator_col = col
        break
if tags_indicator_col is None:
    raise ValueError("Could not find an 'Indicator' column in the tags CSV.")

# The tags field might be called 'Tags', 'tags', or similar
# The tags field might be called 'Tags', 'tags', 'Tag', 'tag', etc.
tags_value_col = None
for col in tags_df.columns:
    if str(col).lower() in ('tags', 'tag'):
        tags_value_col = col
        break
if tags_value_col is None:
    raise ValueError(
        f"Could not find a 'Tag' or 'Tags' column in the tags CSV. "
        f"Available columns: {list(tags_df.columns)}"
    )
# For fast lookup, set up a mapping of indicator -> tags value.
indicator_to_tags = tags_df.set_index(tags_indicator_col)[tags_value_col].to_dict()

# Prepare 'Tags' values for final_indicators
final_tags = final_indicators['Indicator'].map(indicator_to_tags)

# Insert the 'Tags' column as the second to last column
final_cols = list(final_indicators.columns)
if 'Tags' in final_cols:
    final_cols.remove('Tags')
second_to_last_idx = -1 if len(final_cols) == 0 else -1
new_cols = final_cols[:second_to_last_idx] + ['Tags'] + final_cols[second_to_last_idx:]

final_indicators['Tags'] = final_tags
final_indicators = final_indicators[new_cols]
final_indicators

C:\Users\jaskew\AppData\Local\Temp\ipykernel_23648\3834435136.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_indicators['Tags'] = final_tags

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,...,Tagging Boost,Tagging Boost Reason,CAL Score,ThreatConnect Score,PRISM Score,Severity,Explanation,Associated Groups,Tags,OpDiv
420,179.1.195.163,2026-07-06 00:00:00+00:00,Address,24,5,0.998685,0,0,"HRSA, OS",NaN,...,1.0,pair:north korea+diamond sleet,180,590,578,high,[2026-07-06] Severity: high. VT score: 2. Cont...,"Group Id: 6755399483006350, Group Id: 56294995...",North Korea,"HRSA, OS"
719,198.54.117.242,2026-07-06 00:00:00+00:00,Address,131,5,0.992822,1,0,"NIH, VA",NaN,...,1.0,pair:russia+fsb,180,343,578,high,[2026-07-06] Severity: high. VT score: 7. Cont...,"Group Id: 6755399482040879, Group Id: 67553994...",China,"NIH, VA"
833,31.14.254.16,2026-07-06 00:00:00+00:00,Address,39,3,0.997863,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,...,0.0,NaN,480,619,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,NaN,"HHS, HRSA, IHS, NIH, OS, VA"
838,31.14.254.20,2026-07-06 00:00:00+00:00,Address,37,3,0.997973,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,...,0.0,NaN,480,619,500,high,[2026-07-06] Severity: high. VT score: 13. Con...,<NA>,NaN,"HHS, HRSA, IHS, NIH, OS, VA"
856,31.14.254.37,2026-07-06 00:00:00+00:00,Address,32,3,0.998247,0,0,"NIH, OS, VA",NaN,...,0.0,NaN,180,469,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,NaN,"NIH, OS, VA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,69.5.169.90,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,...,0.0,NaN,360,559,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,NaN,"HHS, HRSA, IHS, NIH, OS, VA"
1516,69.5.169.91,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,...,0.0,NaN,480,619,500,high,[2026-07-06] Severity: high. VT score: 13. Con...,<NA>,NaN,"HHS, HRSA, IHS, NIH, OS, VA"
1517,69.5.169.92,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,...,0.0,NaN,480,619,500,high,[2026-07-06] Severity: high. VT score: 13. Con...,<NA>,NaN,"HHS, HRSA, IHS, NIH, OS, VA"
1519,69.5.169.94,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"OS, VA",NaN,...,0.0,NaN,250,504,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,NaN,"OS, VA"
1521,69.5.169.96,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,...,0.0,NaN,640,699,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,NaN,"HHS, HRSA, IHS, NIH, OS, VA"

In [35]:
import pandas as pd

# Helper to see if an indicator has an I&W tag
def has_iw(tags_value):
    """
    tags_value is typically a list of dicts from ThreatConnect, e.g.:
    [{'name': 'I&W'}, {'name': 'something else'}, ...]
    """
    if tags_value is None or (isinstance(tags_value, float) and pd.isna(tags_value)):
        return False

    if not isinstance(tags_value, (list, tuple)):
        return False

    for t in tags_value:
        try:
            if isinstance(t, dict):
                name = str(t.get('name', '')).strip()
            else:
                name = str(t).strip()

            if name.lower() in {"i&w", "i & w", "iw"}:
                return True
        except Exception:
            continue
    return False

# 1) Add has_iw flag to observed_src if tags.data exists
if 'tags.data' in observed_src.columns:
    observed_src['has_iw'] = observed_src['tags.data'].apply(has_iw)
else:
    observed_src['has_iw'] = False

# 2) Collapse to one flag per indicator
iw_per_indicator = (
    observed_src.groupby('indicator', dropna=False)['has_iw']
    .max()  # any True -> True
    .reset_index()
    .rename(columns={'indicator': 'Indicator', 'has_iw': 'Reported I&W?_raw'})
)

# 3) Drop ANY existing Reported I&W? variants (_x, _y, etc.)
cols_to_drop = [c for c in final_indicators.columns if c.startswith('Reported I&W?')]
final_indicators = final_indicators.drop(columns=cols_to_drop, errors='ignore')

# 4) Merge once, with a temporary raw boolean column
final_indicators = final_indicators.merge(
    iw_per_indicator,
    on='Indicator',
    how='left'
)

# 5) Convert to Yes/No, defaulting missing to 'No'
final_indicators['Reported I&W?'] = (
    final_indicators['Reported I&W?_raw']
    .fillna(False)
    .map({True: 'Yes', False: 'No'})
)

# 6) Drop the temporary raw column
final_indicators = final_indicators.drop(columns=['Reported I&W?_raw'])

# Rename column 'HTOC Threat Score' to 'PRISM Score' if it exists
if "HTOC Threat Score" in final_indicators.columns:
    final_indicators = final_indicators.rename(columns={"HTOC Threat Score": "PRISM Score"})


final_indicators

,Indicator,Last Observed,Indicator Type,Observation Yearly Count,ThreatConnect Rating,Observation Penalty Multiplier,Botnet Flag,False Positives,Partners,incidents/events,...,Tagging Boost Reason,CAL Score,ThreatConnect Score,PRISM Score,Severity,Explanation,Associated Groups,Tags,OpDiv,Reported I&W?
0,179.1.195.163,2026-07-06 00:00:00+00:00,Address,24,5,0.998685,0,0,"HRSA, OS",NaN,...,pair:north korea+diamond sleet,180,590,578,high,[2026-07-06] Severity: high. VT score: 2. Cont...,"Group Id: 6755399483006350, Group Id: 56294995...",North Korea,"HRSA, OS",Yes
1,198.54.117.242,2026-07-06 00:00:00+00:00,Address,131,5,0.992822,1,0,"NIH, VA",NaN,...,pair:russia+fsb,180,343,578,high,[2026-07-06] Severity: high. VT score: 7. Cont...,"Group Id: 6755399482040879, Group Id: 67553994...",China,"NIH, VA",Yes
2,31.14.254.16,2026-07-06 00:00:00+00:00,Address,39,3,0.997863,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,...,NaN,480,619,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,NaN,"HHS, HRSA, IHS, NIH, OS, VA",No
3,31.14.254.20,2026-07-06 00:00:00+00:00,Address,37,3,0.997973,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,...,NaN,480,619,500,high,[2026-07-06] Severity: high. VT score: 13. Con...,<NA>,NaN,"HHS, HRSA, IHS, NIH, OS, VA",No
4,31.14.254.37,2026-07-06 00:00:00+00:00,Address,32,3,0.998247,0,0,"NIH, OS, VA",NaN,...,NaN,180,469,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,NaN,"NIH, OS, VA",No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,69.5.169.90,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,...,NaN,360,559,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,NaN,"HHS, HRSA, IHS, NIH, OS, VA",No
74,69.5.169.91,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,...,NaN,480,619,500,high,[2026-07-06] Severity: high. VT score: 13. Con...,<NA>,NaN,"HHS, HRSA, IHS, NIH, OS, VA",No
75,69.5.169.92,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,...,NaN,480,619,500,high,[2026-07-06] Severity: high. VT score: 13. Con...,<NA>,NaN,"HHS, HRSA, IHS, NIH, OS, VA",No
76,69.5.169.94,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"OS, VA",NaN,...,NaN,250,504,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,NaN,"OS, VA",No
77,69.5.169.96,2026-07-06 00:00:00+00:00,Address,36,3,0.998027,0,0,"HHS, HRSA, IHS, NIH, OS, VA",NaN,...,NaN,640,699,500,high,[2026-07-06] Severity: high. VT score: 14. Con...,<NA>,NaN,"HHS, HRSA, IHS, NIH, OS, VA",No

In [ ]:
import ipaddress

MIN_HOSTS_PER_SUBNET = 5  # minimum hosts in a /24 before rolling up to CIDR


def _to_ip(value):
    try:
        return ipaddress.ip_address(str(value).strip())
    except ValueError:
        return None


def _subnet24(ip):
    if ip is None:
        return None
    return str(ipaddress.ip_network(f"{ip}/24", strict=False))


def _union_csv(series):
    parts = set()
    for val in series.dropna():
        for part in str(val).split(","):
            part = part.strip()
            if part:
                parts.add(part)
    return ", ".join(sorted(parts)) if parts else None


def _max_severity(series):
    order = {"critical": 2, "high": 1}
    vals = [str(v).strip().lower() for v in series.dropna()]
    if not vals:
        return None
    return max(vals, key=lambda s: order.get(s, 0))


def _has_threat_actor(value):
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return False
    return bool(str(value).strip())


def _format_host_ips(ips):
    if not isinstance(ips, list) or not ips:
        return ""

    def _sort_key(ip):
        try:
            return ipaddress.ip_address(str(ip))
        except ValueError:
            return ipaddress.ip_address("0.0.0.0")

    return "\n".join(str(ip) for ip in sorted(ips, key=_sort_key))


def condense_final_indicators(df, min_hosts=MIN_HOSTS_PER_SUBNET):
    """Roll dense /24 Address clusters into CIDR rows; keep singles and threat-actor IPs."""
    df = df.copy()
    type_col = "Indicator Type" if "Indicator Type" in df.columns else "Type"

    df["_ip"] = df["Indicator"].map(_to_ip)
    df["_subnet24"] = df["_ip"].map(_subnet24)

    ta_col = "Threat Actor" if "Threat Actor" in df.columns else None
    if ta_col:
        df["_has_ta"] = df[ta_col].map(_has_threat_actor)
    else:
        df["_has_ta"] = False

    condensable_mask = (
        df[type_col].eq("Address")
        & df["_ip"].notna()
        & ~df["_has_ta"]
    )

    subnet_counts = df.loc[condensable_mask].groupby("_subnet24").size()
    dense_subnets = set(subnet_counts[subnet_counts >= min_hosts].index)

    dense_mask = condensable_mask & df["_subnet24"].isin(dense_subnets)
    dense_df = df[dense_mask].copy()
    keep_df = df[~dense_mask].copy()

    if dense_df.empty:
        out = df.drop(columns=["_ip", "_subnet24", "_has_ta"], errors="ignore")
        out["Host IPs"] = out["Indicator"].map(lambda x: str(x))
        return out

    numeric_max_cols = [
        c for c in [
            "Observation Yearly Count",
            "ThreatConnect Rating",
            "Observation Penalty Multiplier",
            "Botnet Flag",
            "False Positives",
            "Tagging Boost",
            "CAL Score",
            "ThreatConnect Score",
            "PRISM Score",
        ]
        if c in dense_df.columns
    ]

    agg = {c: "max" for c in numeric_max_cols}
    agg.update({
        "Indicator": lambda s: sorted(s.astype(str).tolist()),
        "Last Observed": "max",
        type_col: lambda _: "CIDR",
        "Severity": _max_severity,
        "Partners": _union_csv,
        "OpDiv": _union_csv,
        "Threat Actor": _union_csv,
        "Tagging Boost Reason": _union_csv,
        "Associated Groups": _union_csv,
        "incidents/events": _union_csv,
        "Tags": "first",
        "Explanation": "first",
    })

    if "Reported I&W?" in dense_df.columns:
        agg["Reported I&W?"] = lambda s: "Yes" if (s == "Yes").any() else "No"

    condensed = dense_df.groupby("_subnet24", as_index=False).agg(agg)
    condensed = condensed.rename(columns={"Indicator": "_member_ips"})
    condensed["Indicator"] = condensed["_subnet24"]
    condensed["Host IPs"] = condensed["_member_ips"].map(_format_host_ips)

    drop_cols = ["_subnet24", "_ip", "_has_ta", "_member_ips"]
    condensed = condensed.drop(columns=drop_cols, errors="ignore")
    keep_df = keep_df.drop(columns=["_subnet24", "_ip", "_has_ta"], errors="ignore")
    keep_df["Host IPs"] = keep_df["Indicator"].map(lambda x: str(x))

    out = pd.concat([condensed, keep_df], ignore_index=True, sort=False)

    base_cols = [c for c in df.columns if c not in drop_cols]
    ordered = []
    for col in base_cols:
        ordered.append(col)
        if col == "Indicator" and "Host IPs" in out.columns:
            ordered.append("Host IPs")
    ordered.extend([c for c in out.columns if c not in ordered])
    return out[[c for c in ordered if c in out.columns]]


_before = len(final_indicators)
final_indicators = condense_final_indicators(final_indicators)
print(f"Subnet condensation: {_before} -> {len(final_indicators)} rows (min_hosts={MIN_HOSTS_PER_SUBNET})")
final_indicators

In [ ]:
from datetime import datetime

# Build dated output path
today_str = datetime.today().strftime('%Y%m%d')  # e.g. 20260316
output_path = rf"Z:\HTOC\Data_Analytics\Data\Threat Assessment Scores\ThreatAssessI_W\ThreatAssessI_W_{today_str}.xlsx"

# Excel can't write timezone-aware datetimes; strip tz info before export
_dt_tz_cols = final_indicators.select_dtypes(include=["datetimetz"]).columns
for _c in _dt_tz_cols:
    final_indicators[_c] = final_indicators[_c].dt.tz_convert(None)

iw_col = "Reported I&W?"
if iw_col not in final_indicators.columns:
    raise KeyError(f"Missing required column '{iw_col}' for sheet split.")

final_iw_no = final_indicators[final_indicators[iw_col] == "No"].copy()
final_iw_yes = final_indicators[final_indicators[iw_col] == "Yes"].copy()

# Write to one workbook with two named sheets
with pd.ExcelWriter(output_path, engine="xlsxwriter") as writer:
    final_iw_no.to_excel(writer, index=False, sheet_name="I&W_No")
    final_iw_yes.to_excel(writer, index=False, sheet_name="I&W_Yes")

    workbook = writer.book
    wrap_fmt = workbook.add_format({"text_wrap": True, "valign": "top"})

    for sheet_name, sheet_df in [("I&W_No", final_iw_no), ("I&W_Yes", final_iw_yes)]:
        worksheet = writer.sheets[sheet_name]
        worksheet.set_column(0, len(final_indicators.columns) - 1, 18)

        if "Explanation" in final_indicators.columns:
            _exp_idx = final_indicators.columns.get_loc("Explanation")
            worksheet.set_column(_exp_idx, _exp_idx, 100, wrap_fmt)

        if "Associated Groups" in final_indicators.columns:
            _ag_idx = final_indicators.columns.get_loc("Associated Groups")
            worksheet.set_column(_ag_idx, _ag_idx, 45, wrap_fmt)

        if "Host IPs" in final_indicators.columns:
            _host_idx = final_indicators.columns.get_loc("Host IPs")
            worksheet.set_column(_host_idx, _host_idx, 40, wrap_fmt)
            for row_idx, host_ips in enumerate(sheet_df["Host IPs"].fillna(""), start=1):
                line_count = max(1, str(host_ips).count("\n") + 1)
                worksheet.set_row(row_idx, min(15 * line_count, 400))

output_path