In [2]:
import pandas as pd
import numpy as np

In [8]:
#import data from /Users/jaytlinaskew/GitRepository/TimeSeries-Analysis/data/processed/ProcessedObservedData.csv
data = pd.read_csv(r'C:\Users\jaskew\Documents\project_repository\data\processed\ProcessedObservedData.csv')
#filter by opDiv CDC
data = data[data['OpDiv'] == 'CDC']
data.drop(columns=['curr_date', 'OpDiv','API_UserName'], inplace=True)
# Rename the index to 'date' since 'obs_date' is now the index
data.rename(columns={'obs_date': 'date'}, inplace=True)
data['date'] = pd.to_datetime(data['date'])
data.reset_index(drop=True, inplace=True)
data.head(10)
# Create a copy of the relevant columns to avoid SettingWithCopyWarning

data.head(10)

         indicator       date  observations
0    146.71.50.198 2025-01-01             1
1    149.36.49.225 2025-01-01            28
2  162.142.125.242 2025-01-01             3
3  162.142.125.247 2025-01-01             2
4  162.142.125.255 2025-01-01             3
5   185.230.63.171 2025-01-01             6
6     23.26.221.12 2025-01-01            49
7      23.26.221.2 2025-01-01            51
8      23.26.221.4 2025-01-01            36
9   34.160.111.145 2025-01-01             4

In [10]:
# check duplicates count of each indicator
duplicates_count = data.groupby('indicator').size().reset_index(name='count')
# Print the duplicates count
print(duplicates_count)

                           indicator  count
0                    102.129.153.158      2
1                     102.129.153.43      2
2                     102.129.153.71      5
3                     102.165.16.161      6
4                        104.160.6.2      1
..                               ...    ...
192  international.standardbank.com/      1
193                    pub.marq.com/      5
194        realinvestmentadvice.com/      8
195       www.emergencylighting.com/      3
196                 www.shorturl.at/     46

[197 rows x 2 columns]

In [15]:
duplicates_count[duplicates_count['indicator']== '146.71.50.198']

        indicator  count
16  146.71.50.198     37

In [14]:
# Merge the duplicates_count with the data to align the count with each indicator
data = data.merge(duplicates_count, on='indicator', how='left')

# Repeat rows based on the 'count' column
expanded_data = data.loc[data.index.repeat(data['count'])].reset_index(drop=True)

print(expanded_data.head(10))

       indicator       date  observations frequency  count
0  146.71.50.198 2025-01-01             1     daily     37
1  146.71.50.198 2025-01-01             1     daily     37
2  146.71.50.198 2025-01-01             1     daily     37
3  146.71.50.198 2025-01-01             1     daily     37
4  146.71.50.198 2025-01-01             1     daily     37
5  146.71.50.198 2025-01-01             1     daily     37
6  146.71.50.198 2025-01-01             1     daily     37
7  146.71.50.198 2025-01-01             1     daily     37
8  146.71.50.198 2025-01-01             1     daily     37
9  146.71.50.198 2025-01-01             1     daily     37

In [7]:
expanded_data.to_csv(r'C:\Users\jaskew\Documents\project_repository\notebooks\observationEventForecasting\DataPreprocessing\BlowUpData.csv', index=False)